// Generated by GitHub Copilot
const mongoose = require('mongoose')

/**
 * Singleton contribution settings document. Only one document should ever exist
 * (enforced by the `singleton` static helper). It defines the global rules that
 * govern member contributions.
 */
const contributionSettingSchema = new mongoose.Schema(
  {
    monthlyAmount: {
      type: Number,
      required: [true, 'Monthly contribution amount is required'],
      min: [1, 'Monthly amount must be at least 1'],
      default: 2000,
    },
    description: {
      type: String,
      trim: true,
      default: 'Monthly membership contribution',
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true },
)

/**
 * Retrieve the singleton settings document. Creates one with sensible defaults
 * if none exists yet.
 * @returns {Promise<import('mongoose').Document>}
 */
contributionSettingSchema.statics.getSingleton = async function () {
  let settings = await this.findOne()
  if (!settings) {
    settings = await this.create({
      monthlyAmount: 2000,
      description: 'Monthly membership contribution',
      isActive: true,
    })
  }
  return settings
}

module.exports = mongoose.model('ContributionSetting', contributionSettingSchema)