// Generated by GitHub Copilot
const mongoose = require('mongoose')

/**
 * Contribution record — one per member per month.
 * Tracks whether the member has paid their monthly contribution.
 */
const contributionSchema = new mongoose.Schema(
  {
    memberId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Member',
      required: true,
      index: true,
    },
    month: {
      type: String,
      required: true,
      match: [/^\d{4}-\d{2}$/, 'Month must be in YYYY-MM format'],
    },
    amount: {
      type: Number,
      required: true,
      min: [0, 'Amount cannot be negative'],
    },
    status: {
      type: String,
      enum: ['paid', 'unpaid'],
      default: 'unpaid',
    },
    paymentDate: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true },
)

// Ensure one record per member per month
contributionSchema.index({ memberId: 1, month: 1 }, { unique: true })

module.exports = mongoose.model('Contribution', contributionSchema)