// Generated by GitHub Copilot
const mongoose = require('mongoose')

/**
 * Loan request — tracks member applications for new loans.
 * An admin can later approve/reject these to create actual Loan records.
 */
const loanRequestSchema = new mongoose.Schema(
  {
    memberId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Member',
      required: true,
      index: true,
    },
    amount: {
      type: Number,
      required: [true, 'Loan amount is required'],
      min: [1, 'Loan amount must be at least 1'],
    },
    monthRequired: {
      type: String,
      required: [true, 'Month for which loan is required is needed'],
      match: [/^\d{4}-\d{2}$/, 'Month must be in YYYY-MM format'],
    },
    expectedReturn: {
      type: Date,
      default: null,
    },
    purpose: {
      type: String,
      required: [true, 'Purpose is required'],
      trim: true,
    },
    notes: {
      type: String,
      trim: true,
      default: '',
    },
    adminNotes: {
      type: String,
      trim: true,
      default: '',
    },
    status: {
      type: String,
      enum: ['pending', 'approved', 'rejected', 'withdrawn'],
      default: 'pending',
    },
    // Link to the Loan created when this request is approved.
    loanId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Loan',
      default: null,
    },
    // Queue priority (ms-scale). Lower = earlier. Defaults to creation time for FIFO.
    queueOrder: {
      type: Number,
      default: null,
    },
  },
  { timestamps: true },
)

module.exports = mongoose.model('LoanRequest', loanRequestSchema)