// Generated by GitHub Copilot
const mongoose = require('mongoose')

/**
 * Loan record — tracks loans issued to members.
 * Includes repayment history and remaining balance.
 */
const loanSchema = new mongoose.Schema(
  {
    memberId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Member',
      required: true,
      index: true,
    },
    amount: {
      type: Number,
      required: true,
      min: [1, 'Loan amount must be at least 1'],
    },
    remaining: {
      type: Number,
      required: true,
      min: [0, 'Remaining balance cannot be negative'],
    },
    issueDate: {
      type: Date,
      required: true,
    },
    dueDate: {
      type: Date,
      default: null,
    },
    status: {
      type: String,
      enum: ['active', 'paid', 'defaulted'],
      default: 'active',
    },
    closedAt: {
      type: Date,
      default: null,
    },
    notes: {
      type: String,
      trim: true,
      default: '',
    },
    repayments: [
      {
        amount: {
          type: Number,
          required: true,
        },
        date: {
          type: Date,
          required: true,
        },
        notes: {
          type: String,
          trim: true,
          default: '',
        },
      },
    ],
  },
  { timestamps: true },
)

module.exports = mongoose.model('Loan', loanSchema)