// Generated by GitHub Copilot
const mongoose = require('mongoose')
const bcrypt = require('bcryptjs')

/**
 * Member account schema. Passwords are hashed with bcrypt before persistence
 * and are never returned by default (`select: false`).
 */
const memberSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, 'Name is required'],
      trim: true,
    },
    mobile: {
      type: String,
      required: [true, 'Mobile number is required'],
      unique: true,
      trim: true,
      match: [/^\d{10}$/, 'Mobile number must be 10 digits'],
    },
    email: {
      type: String,
      required: [true, 'Email is required'],
      unique: true,
      lowercase: true,
      trim: true,
      match: [/^[^\s@]+@[^\s@]+\.[^\s@]+$/, 'Please provide a valid email'],
    },
    password: {
      type: String,
      required: [true, 'Password is required'],
      minlength: [6, 'Password must be at least 6 characters'],
      select: false,
    },
    joiningDate: {
      type: Date,
      default: Date.now,
    },
    status: {
      type: String,
      enum: ['Active', 'Inactive', 'Exited'],
      default: 'Active',
    },
    mustChangePassword: {
      type: Boolean,
      default: true,
    },
    role: {
      type: String,
      default: 'member',
      immutable: true,
    },
    isDeleted: {
      type: Boolean,
      default: false,
    },
    deletedAt: {
      type: Date,
      default: null,
    },
    exitedAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true },
)

// Hash the password whenever it is set or changed.
memberSchema.pre('save', async function hashPassword(next) {
  if (!this.isModified('password')) return next()
  const salt = await bcrypt.genSalt(10)
  this.password = await bcrypt.hash(this.password, salt)
  return next()
})

/**
 * Compare a plain-text password against the stored hash.
 * @param {string} candidate - Plain-text password to verify.
 * @returns {Promise<boolean>}
 */
memberSchema.methods.matchPassword = function matchPassword(candidate) {
  return bcrypt.compare(candidate, this.password)
}

module.exports = mongoose.model('Member', memberSchema)
