// Generated by GitHub Copilot
const mongoose = require('mongoose')

/**
 * Notification schema - stores in-app alerts for both admins and members.
 * Polled by the frontend; never delivered via email or push in this phase.
 * Compound index on { recipientId, isRead } keeps unread-count queries fast.
 */
const notificationSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
    },
    message: {
      type: String,
      required: [true, 'Message is required'],
      trim: true,
    },
    type: {
      type: String,
      enum: ['info', 'success', 'warning', 'alert'],
      default: 'info',
    },
    recipientId: {
      type: mongoose.Schema.Types.ObjectId,
      required: [true, 'Recipient ID is required'],
      index: true,
    },
    recipientRole: {
      type: String,
      enum: ['admin', 'member'],
      required: [true, 'Recipient role is required'],
    },
    isRead: {
      type: Boolean,
      default: false,
    },
    readAt: {
      type: Date,
      default: null,
    },
    relatedEntity: {
      type: String,
      enum: ['Member', 'Contribution', 'Loan', 'LoanRepayment', 'ContributionSetting', null],
      default: null,
    },
    relatedEntityId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
    },
  },
  { timestamps: true },
)

// Compound index for fast unread-count and per-recipient queries
notificationSchema.index({ recipientId: 1, isRead: 1 })
notificationSchema.index({ createdAt: -1 })

const Notification = mongoose.model('Notification', notificationSchema)

module.exports = Notification
