// Generated by GitHub Copilot
const mongoose = require('mongoose')

/**
 * Notification schema for in-app notifications.
 * Supports different types: success, warning, info, alert
 */
const notificationSchema = new mongoose.Schema(
  {
    recipientId: {
      type: mongoose.Schema.Types.ObjectId,
      required: [true, 'Recipient ID is required'],
      ref: 'Member',
    },
    recipientRole: {
      type: String,
      enum: ['member', 'admin'],
      required: [true, 'Recipient role is required'],
      default: 'member',
    },
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },
    message: {
      type: String,
      required: [true, 'Message is required'],
      trim: true,
      maxlength: [1000, 'Message cannot exceed 1000 characters'],
    },
    type: {
      type: String,
      enum: ['success', 'warning', 'info', 'alert'],
      default: 'info',
    },
    relatedEntity: {
      type: String,
      trim: true,
      maxlength: [50, 'Entity name cannot exceed 50 characters'],
    },
    relatedEntityId: {
      type: mongoose.Schema.Types.ObjectId,
    },
    isRead: {
      type: Boolean,
      default: false,
    },
    readAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  },
)

// Index for efficient querying of notifications by recipient
notificationSchema.index({ recipientId: 1, createdAt: -1 })
notificationSchema.index({ recipientId: 1, isRead: 1, createdAt: -1 })

module.exports = mongoose.model('Notification', notificationSchema)