// Generated by GitHub Copilot
import { Routes, Route, Navigate } from 'react-router-dom'
import ProtectedRoute from './ProtectedRoute.jsx'
import DashboardLayout from '../components/layout/DashboardLayout.jsx'

// Auth
import LoginPage from '../pages/auth/LoginPage.jsx'

// Admin pages
import AdminDashboard from '../pages/admin/Dashboard.jsx'
import Members from '../pages/admin/Members.jsx'
import AddMember from '../pages/admin/AddMember.jsx'
import EditMember from '../pages/admin/EditMember.jsx'
import MemberDetails from '../pages/admin/MemberDetails.jsx'
import AdminContributions from '../pages/admin/Contributions.jsx'
import Loans from '../pages/admin/Loans.jsx'
import LoanDetails from '../pages/admin/LoanDetails.jsx'
import IssueLoan from '../pages/admin/IssueLoan.jsx'
import AdminLoanPassbook from '../pages/admin/LoanPassbook.jsx'
import Settings from '../pages/admin/Settings.jsx'
import AuditLogs from '../pages/admin/AuditLogs.jsx'
import AdminNotifications from '../pages/admin/Notifications.jsx'

// Member pages
import MemberDashboard from '../pages/member/Dashboard.jsx'
import MemberContributions from '../pages/member/Contributions.jsx'
import ContributionDetails from '../pages/member/ContributionDetails.jsx'
import MemberLoans from '../pages/member/Loans.jsx'
import MemberLoan from '../pages/member/LoanDetails.jsx'
import MemberLoanPassbook from '../pages/member/LoanPassbook.jsx'
import MemberProfile from '../pages/member/Profile.jsx'
import MemberNotifications from '../pages/member/Notifications.jsx'
import ForceChangePassword from '../pages/member/ForceChangePassword.jsx'

import NotFound from '../pages/NotFound.jsx'

/** Central route table with role-protected admin and member areas. */
export default function AppRoutes() {
  return (
    <Routes>
      <Route path="/" element={<Navigate to="/login" replace />} />
      <Route path="/login" element={<LoginPage />} />

      {/* Admin area */}
      <Route
        path="/admin"
        element={
          <ProtectedRoute role="admin">
            <DashboardLayout />
          </ProtectedRoute>
        }
      >
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<AdminDashboard />} />
        <Route path="members" element={<Members />} />
        <Route path="members/add" element={<AddMember />} />
        <Route path="members/:id" element={<MemberDetails />} />
        <Route path="members/:id/edit" element={<EditMember />} />
        <Route path="contributions" element={<AdminContributions />} />
        <Route path="loans" element={<Loans />} />
        <Route path="loans/create" element={<IssueLoan />} />
        <Route path="loans/:id" element={<LoanDetails />} />
        <Route path="passbook" element={<AdminLoanPassbook />} />
        <Route path="passbook/:loanId" element={<AdminLoanPassbook />} />
        <Route path="settings" element={<Settings />} />
        <Route path="notifications" element={<AdminNotifications />} />
        <Route path="audit-logs" element={<AuditLogs />} />
      </Route>

      {/* Force password change (standalone, no dashboard layout) */}
      <Route
        path="/member/force-change-password"
        element={
          <ProtectedRoute role="member">
            <ForceChangePassword />
          </ProtectedRoute>
        }
      />

      {/* Member area */}
      <Route
        path="/member"
        element={
          <ProtectedRoute role="member">
            <DashboardLayout />
          </ProtectedRoute>
        }
      >
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<MemberDashboard />} />
        <Route path="contributions" element={<MemberContributions />} />
        <Route path="contributions/:id" element={<ContributionDetails />} />
        <Route path="loans" element={<MemberLoans />} />
        <Route path="loans/:loanId/passbook" element={<MemberLoanPassbook />} />
        <Route path="loan" element={<MemberLoan />} />
        <Route path="profile" element={<MemberProfile />} />
        <Route path="notifications" element={<MemberNotifications />} />
      </Route>

      <Route path="*" element={<NotFound />} />
    </Routes>
  )
}
