// Generated by GitHub Copilot
import { Navigate, useLocation } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth.js'
import Loader from '../components/ui/Loader.jsx'

/**
 * Guards dashboard routes. Redirects unauthenticated users to the login page
 * and blocks access to areas that do not match the signed-in user's role.
 */
export default function ProtectedRoute({ role, children }) {
  const { user, isAuthenticated, loading } = useAuth()
  const location = useLocation()

  if (loading) {
    // Wait while a stored session token is being validated on startup.
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Loader label="Loading your session…" />
      </div>
    )
  }

  if (!isAuthenticated) {
    return <Navigate to="/login" replace state={{ from: location }} />
  }

  if (role && user.role !== role) {
    // Signed in but wrong area — send to the correct dashboard.
    return <Navigate to={`/${user.role}/dashboard`} replace />
  }

  return children
}
