// Generated by GitHub Copilot
const app = require('./src/app')
const env = require('./src/config/env')
const connectDB = require('./src/config/db')

/** Boot sequence: connect to MongoDB, then start the HTTP server. */
async function start() {
  await connectDB()

  const server = app.listen(env.port, () => {
    // eslint-disable-next-line no-console
    console.log(
      `🚀 Maqasid Bank API listening on http://localhost:${env.port} (${env.nodeEnv})`,
    )
  })

  // Graceful shutdown on fatal errors and termination signals.
  const shutdown = (signal) => {
    // eslint-disable-next-line no-console
    console.log(`\n${signal} received. Shutting down gracefully...`)
    server.close(() => process.exit(0))
  }

  process.on('unhandledRejection', (reason) => {
    // eslint-disable-next-line no-console
    console.error('Unhandled Rejection:', reason)
    server.close(() => process.exit(1))
  })
  process.on('SIGTERM', () => shutdown('SIGTERM'))
  process.on('SIGINT', () => shutdown('SIGINT'))
}

start()
