// Generated by GitHub Copilot
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { RiBankFill } from 'react-icons/ri'
import { FiMail, FiLock, FiShield, FiUser } from 'react-icons/fi'
import { useAuth } from '../../hooks/useAuth.js'
import Button from '../../components/ui/Button.jsx'
import Input from '../../components/ui/Input.jsx'

/**
 * Login screen with a role selector. Credentials are authenticated against the
 * Maqasid Bank backend; a valid login returns a JWT and routes the user to the
 * dashboard matching their role.
 */
export default function LoginPage() {
  const { login } = useAuth()
  const navigate = useNavigate()
  const [role, setRole] = useState('admin')
  const [identifier, setIdentifier] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)

  // Both fields must be filled before the form can be submitted.
  const canSubmit = identifier.trim() !== '' && password !== ''

  const submit = async (creds) => {
    setError('')
    setSubmitting(true)
    try {
      const authedUser = await login({ role, ...creds })
      // If the member must change their initial password, redirect them.
      if (authedUser.role === 'member' && authedUser.mustChangePassword) {
        navigate('/member/force-change-password', { replace: true })
      } else {
        navigate(`/${authedUser.role}/dashboard`, { replace: true })
      }
    } catch (err) {
      setError(err.message || 'Login failed. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!canSubmit) return
    submit({ identifier, password })
  }

  const roles = [
    { key: 'admin', label: 'Admin', icon: FiShield, desc: 'Manage everything' },
    { key: 'member', label: 'Member', icon: FiUser, desc: 'Personal view' },
  ]

  return (
    <div className="flex min-h-screen">
      {/* Brand panel */}
      <div className="relative hidden w-1/2 flex-col justify-between overflow-hidden bg-gradient-to-br from-indigo-600 via-blue-600 to-sky-500 p-12 text-white lg:flex">
        <div className="flex items-center gap-3">
          <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15">
            <RiBankFill className="h-6 w-6" />
          </span>
          <span className="text-lg font-bold">Maqasid Bank</span>
        </div>
        <div>
          <h1 className="text-4xl font-bold leading-tight">
            Maqasid Bank
          </h1>
          <p className="mt-4 max-w-md text-indigo-50">
            Track member contributions, manage loans and monitor your community
            fund — all in one clean, simple dashboard.
          </p>
        </div>
        <p className="text-sm text-indigo-100">
          © 2024 Maqasid Bank · All rights reserved
        </p>
        <div className="pointer-events-none absolute -right-24 top-1/3 h-72 w-72 rounded-full bg-sky-400/40 blur-3xl" />
        <div className="pointer-events-none absolute -left-20 bottom-0 h-64 w-64 rounded-full bg-indigo-400/30 blur-3xl" />
      </div>

      {/* Form panel */}
      <div className="flex w-full items-center justify-center bg-slate-50 px-6 py-12 lg:w-1/2">
        <div className="w-full max-w-md">
          <div className="mb-8 text-center lg:hidden">
            <span className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-brand-600 text-white">
              <RiBankFill className="h-6 w-6" />
            </span>
            <h1 className="text-xl font-bold text-slate-800">Maqasid Bank</h1>
          </div>

          <h2 className="text-2xl font-bold text-slate-800">Sign in</h2>
          <p className="mt-1 text-sm text-slate-500">
            Select your role and enter your credentials to continue.
          </p>

          <div className="mt-6 grid grid-cols-2 gap-3">
            {roles.map((r) => {
              const Icon = r.icon
              const active = role === r.key
              return (
                <button
                  key={r.key}
                  type="button"
                  onClick={() => setRole(r.key)}
                  aria-pressed={active}
                  className={`flex flex-col items-start gap-1 rounded-xl border p-4 text-left transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
                    active
                      ? 'border-brand-500 bg-brand-50 ring-1 ring-brand-500'
                      : 'border-slate-200 bg-white hover:border-slate-300'
                  }`}
                >
                  <Icon
                    className={`h-5 w-5 ${active ? 'text-brand-600' : 'text-slate-400'}`}
                  />
                  <span className="text-sm font-semibold text-slate-800">
                    {r.label}
                  </span>
                  <span className="text-xs text-slate-400">{r.desc}</span>
                </button>
              )
            })}
          </div>

          {error ? (
            <div
              role="alert"
              className="mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"
            >
              {error}
            </div>
          ) : null}

          <form onSubmit={handleSubmit} className="mt-6 space-y-4">
            <Input
              label="Mobile or Email"
              name="identifier"
              type="text"
              icon={FiMail}
              placeholder="you@example.com"
              value={identifier}
              onChange={(e) => setIdentifier(e.target.value)}
              autoComplete="username"
            />
            <Input
              label="Password"
              name="password"
              type="password"
              icon={FiLock}
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete="current-password"
            />

            <Button
              type="submit"
              size="lg"
              className="w-full"
              disabled={submitting || !canSubmit}
            >
              {submitting
                ? 'Signing in…'
                : `Login as ${role === 'admin' ? 'Admin' : 'Member'}`}
            </Button>
          </form>

          <p className="mt-6 text-center text-xs text-slate-400">
            Sign in with your Maqasid Bank account credentials.
          </p>
        </div>
      </div>
    </div>
  )
}
