// Generated by GitHub Copilot
import Table, { THead, TBody, TR, TH, TD } from '../ui/Table.jsx'
import Badge from '../ui/Badge.jsx'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Read-only contribution history table (month, amount, date, status). */
export default function ContributionsTable({ contributions }) {
  return (
    <Table>
      <THead>
        <TR>
          <TH>Month</TH>
          <TH className="text-right">Amount</TH>
          <TH>Payment Date</TH>
          <TH>Status</TH>
        </TR>
      </THead>
      <TBody>
        {contributions.map((c) => (
          <TR key={c.id}>
            <TD className="font-medium text-slate-800">{c.label}</TD>
            <TD className="text-right">{formatCurrency(c.amount)}</TD>
            <TD>{formatDate(c.paymentDate)}</TD>
            <TD>
              <Badge>{c.status}</Badge>
            </TD>
          </TR>
        ))}
      </TBody>
    </Table>
  )
}
