// Generated by GitHub Copilot
import { useNavigate } from 'react-router-dom'
import { FiBookOpen } from 'react-icons/fi'
import Table, { THead, TBody, TR, TH, TD } from '../ui/Table.jsx'
import Badge from '../ui/Badge.jsx'
import Button from '../ui/Button.jsx'
import { formatCurrency, formatDate } from '../../utils/format.js'

/**
 * Loans table. When `showMember` is set the member column is displayed, and an
 * optional passbook action links through to the loan passbook.
 */
export default function LoansTable({ loans, showMember = true, showPassbook = true }) {
  const navigate = useNavigate()

  return (
    <Table>
      <THead>
        <TR>
          {showMember ? <TH>Member</TH> : null}
          <TH className="text-right">Loan Amount</TH>
          <TH>Issue Date</TH>
          <TH className="text-right">Remaining</TH>
          <TH>Status</TH>
          {showPassbook ? <TH className="text-right">Passbook</TH> : null}
        </TR>
      </THead>
      <TBody>
        {loans.map((l) => (
          <TR key={l.id}>
            {showMember ? (
              <TD className="font-medium text-slate-800">{l.memberName}</TD>
            ) : null}
            <TD className="text-right font-medium">{formatCurrency(l.amount)}</TD>
            <TD>{formatDate(l.issueDate)}</TD>
            <TD className="text-right">
              {l.remaining > 0 ? (
                <span className="font-medium text-amber-600">
                  {formatCurrency(l.remaining)}
                </span>
              ) : (
                <span className="text-green-600">{formatCurrency(0)}</span>
              )}
            </TD>
            <TD>
              <Badge>{l.status}</Badge>
            </TD>
            {showPassbook ? (
              <TD className="text-right">
                <Button
                  size="sm"
                  variant="ghost"
                  icon={FiBookOpen}
                  onClick={() => navigate(`/admin/passbook/${l.id}`)}
                >
                  View
                </Button>
              </TD>
            ) : null}
          </TR>
        ))}
      </TBody>
    </Table>
  )
}
