// Generated by GitHub Copilot
import { useNavigate } from 'react-router-dom'
import { FiEye } from 'react-icons/fi'
import Table, { THead, TBody, TR, TH, TD } from '../ui/Table.jsx'
import Badge from '../ui/Badge.jsx'
import Button from '../ui/Button.jsx'
import { formatCurrency, formatDate, getInitials } from '../../utils/format.js'

const AVATAR_COLORS = ['#3563ff', '#16a34a', '#db2777', '#ea580c', '#0891b2', '#7c3aed', '#ca8a04', '#dc2626']

/** Derive a consistent avatar colour from a string (e.g. member id). */
function avatarColor(str) {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash)
  }
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length]
}

/** Renders the members list as a table with an avatar and a view action. */
export default function MembersTable({ members }) {
  const navigate = useNavigate()

  return (
    <Table>
      <THead>
        <TR>
          <TH>Member</TH>
          <TH>Mobile</TH>
          <TH>Joined</TH>
          <TH className="text-right">Contribution</TH>
          <TH className="text-right">Active Loan</TH>
          <TH>Status</TH>
          <TH className="text-right">Action</TH>
        </TR>
      </THead>
      <TBody>
        {members.map((m) => {
          const memberId = m._id || m.id
          return (
            <TR key={memberId}>
              <TD>
                <div className="flex items-center gap-3">
                  <span
                    className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-full text-xs font-semibold text-white"
                    style={{ backgroundColor: m.avatarColor || avatarColor(memberId) }}
                  >
                    {getInitials(m.name)}
                  </span>
                  <div className="min-w-0">
                    <p className="font-medium text-slate-800">{m.name}</p>
                    <p className="text-xs text-slate-400">{m.email}</p>
                  </div>
                </div>
              </TD>
              <TD>{m.mobile}</TD>
              <TD>{formatDate(m.joiningDate)}</TD>
              <TD className="text-right font-medium">
                {formatCurrency(m.totalContribution || 0)}
              </TD>
              <TD className="text-right">
                {(m.activeLoan || 0) > 0 ? (
                  <span className="font-medium text-amber-600">
                    {formatCurrency(m.activeLoan)}
                  </span>
                ) : (
                  <span className="text-slate-400">—</span>
                )}
              </TD>
              <TD>
                <Badge>{m.status}</Badge>
              </TD>
              <TD className="text-right">
                <Button
                  size="sm"
                  variant="secondary"
                  icon={FiEye}
                  onClick={() => navigate(`/admin/members/${memberId}`)}
                >
                  View
                </Button>
              </TD>
            </TR>
          )
        })}
      </TBody>
    </Table>
  )
}
