// Generated by GitHub Copilot
import Table, { THead, TBody, TR, TH, TD } from '../ui/Table.jsx'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Repayment history table for a single loan. */
export default function RepaymentTable({ repayments }) {
  return (
    <Table>
      <THead>
        <TR>
          <TH>#</TH>
          <TH>Payment Date</TH>
          <TH className="text-right">Amount Paid</TH>
        </TR>
      </THead>
      <TBody>
        {repayments.map((r, index) => (
          <TR key={r.id}>
            <TD className="text-slate-400">{index + 1}</TD>
            <TD>{formatDate(r.date)}</TD>
            <TD className="text-right font-medium text-green-600">
              {formatCurrency(r.amount)}
            </TD>
          </TR>
        ))}
      </TBody>
    </Table>
  )
}
