// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { FiArrowLeft, FiDollarSign, FiCalendar, FiCheck, FiX, FiClock } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Button from '../../components/ui/Button.jsx'
import { memberContributionApi } from '../../api/memberContributionApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'
import Loader from '../../components/ui/Loader.jsx'

/** Member contribution detail page. */
export default function ContributionDetails() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [contribution, setContribution] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const fetchContribution = async () => {
      setLoading(true)
      setError('')
      try {
        const data = await memberContributionApi.getMyContributionById(id)
        setContribution(data)
      } catch (err) {
        setError(err.message || 'Failed to load contribution details')
      } finally {
        setLoading(false)
      }
    }

    if (id) {
      fetchContribution()
    }
  }, [id])

  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <Loader label="Loading contribution details…" />
      </div>
    )
  }

  if (error) {
    return (
      <div>
        <PageHeader
          title="Contribution Details"
          description="View contribution information"
        />
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
        <Button
          variant="secondary"
          onClick={() => navigate('/member/contributions')}
          className="mt-4"
        >
          <FiArrowLeft className="mr-2 h-4 w-4" />
          Back to Contributions
        </Button>
      </div>
    )
  }

  if (!contribution) {
    return (
      <div>
        <PageHeader
          title="Contribution Details"
          description="View contribution information"
        />
        <div className="rounded-lg border border-yellow-200 bg-yellow-50 px-4 py-3 text-sm text-yellow-700">
          Contribution not found
        </div>
        <Button
          variant="secondary"
          onClick={() => navigate('/member/contributions')}
          className="mt-4"
        >
          <FiArrowLeft className="mr-2 h-4 w-4" />
          Back to Contributions
        </Button>
      </div>
    )
  }

  const detailItems = [
    {
      label: 'Month',
      value: contribution.label,
      icon: FiCalendar,
    },
    {
      label: 'Amount',
      value: formatCurrency(contribution.amount),
      icon: FiDollarSign,
    },
    {
      label: 'Status',
      value: contribution.status,
      icon: contribution.status === 'paid' ? FiCheck : FiX,
      badge: true,
    },
    {
      label: 'Payment Date',
      value: contribution.paymentDate ? formatDate(contribution.paymentDate) : 'Not paid yet',
      icon: FiClock,
    },
    {
      label: 'Created',
      value: formatDate(contribution.createdAt),
      icon: FiCalendar,
    },
    {
      label: 'Last Updated',
      value: formatDate(contribution.updatedAt),
      icon: FiClock,
    },
  ]

  return (
    <div>
      <PageHeader
        title="Contribution Details"
        description={`${contribution.label} - ${formatCurrency(contribution.amount)}`}
      />

      <Button
        variant="secondary"
        onClick={() => navigate('/member/contributions')}
        className="mb-6"
      >
        <FiArrowLeft className="mr-2 h-4 w-4" />
        Back to Contributions
      </Button>

      <Card>
        <CardBody>
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
            {detailItems.map((item) => {
              const Icon = item.icon
              return (
                <div key={item.label} className="flex items-start gap-4">
                  <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100 text-slate-600">
                    <Icon className="h-5 w-5" />
                  </span>
                  <div className="flex-1">
                    <p className="text-xs text-slate-500">{item.label}</p>
                    {item.badge ? (
                      <Badge variant={item.value === 'paid' ? 'success' : 'warning'} className="mt-1">
                        {item.value}
                      </Badge>
                    ) : (
                      <p className="mt-1 text-sm font-medium text-slate-800">{item.value}</p>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        </CardBody>
      </Card>
    </div>
  )
}