// Generated by GitHub Copilot
import { useMemo, useState } from 'react'
import { FiDollarSign } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Select from '../../components/ui/Select.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import Pagination from '../../components/ui/Pagination.jsx'
import ContributionsTable from '../../components/tables/ContributionsTable.jsx'
import StatCard from '../../components/cards/StatCard.jsx'
import { useData } from '../../hooks/useData.js'
import { usePagination } from '../../hooks/usePagination.js'
import { currentMemberId } from '../../data/members.js'
import { formatCurrency } from '../../utils/format.js'

/** Member's own contribution history with a status filter. */
export default function MemberContributions() {
  const { getContributionsByMember } = useData()
  const [filter, setFilter] = useState('all')

  const all = getContributionsByMember(currentMemberId)

  const filtered = useMemo(
    () => (filter === 'all' ? all : all.filter((c) => c.status === filter)),
    [all, filter],
  )

  const { page, totalPages, pageItems, next, prev, goTo } = usePagination(
    filtered,
    10,
  )

  const totalPaid = all
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + c.amount, 0)
  const pending = all.filter((c) => c.status === 'unpaid').length

  return (
    <div>
      <PageHeader
        title="My Contributions"
        description="Your complete contribution history."
      />

      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <StatCard
          label="Total Paid"
          value={formatCurrency(totalPaid)}
          icon={FiDollarSign}
          tone="green"
        />
        <StatCard
          label="Pending Months"
          value={pending}
          icon={FiDollarSign}
          tone="amber"
        />
      </div>

      <Card>
        <CardBody className="flex items-center justify-between">
          <h3 className="text-sm font-semibold text-slate-700">History</h3>
          <Select
            name="filter"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            className="w-40"
            options={[
              { value: 'all', label: 'All' },
              { value: 'paid', label: 'Paid' },
              { value: 'unpaid', label: 'Unpaid' },
            ]}
          />
        </CardBody>

        {filtered.length === 0 ? (
          <EmptyState title="No contributions found" />
        ) : (
          <div className="px-4 pb-4">
            <ContributionsTable contributions={pageItems} />
            <Pagination
              page={page}
              totalPages={totalPages}
              onNext={next}
              onPrev={prev}
              onGoTo={goTo}
            />
          </div>
        )}
      </Card>
    </div>
  )
}
