// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiDollarSign, FiCalendar, FiCheck, FiX } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Button from '../../components/ui/Button.jsx'
import Select from '../../components/ui/Select.jsx'
import { memberContributionApi } from '../../api/memberContributionApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'
import Loader from '../../components/ui/Loader.jsx'

/** Member contributions page with summary and history. */
export default function MemberContributions() {
  const navigate = useNavigate()
  const [contributions, setContributions] = useState([])
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  // Filters
  const [yearFilter, setYearFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [currentPage, setCurrentPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)

  const fetchData = async () => {
    setLoading(true)
    setError('')
    try {
      // Fetch summary
      const summaryRes = await memberContributionApi.getMyContributionSummary()
      setSummary(summaryRes)

      // Fetch contributions with filters
      const params = { page: currentPage, limit: 10 }
      if (yearFilter) {
        // Use the year endpoint if year filter is selected
        const yearData = await memberContributionApi.getMyContributionsByYear(yearFilter)
        setContributions(yearData.contributions)
        setTotalPages(1) // Year endpoint doesn't have pagination
        setLoading(false)
        return
      }
      if (statusFilter) params.status = statusFilter

      const contributionsRes = await memberContributionApi.getMyContributions(params)
      setContributions(contributionsRes.contributions)
      setTotalPages(contributionsRes.pagination.totalPages)
    } catch (err) {
      setError(err.message || 'Failed to load contributions')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchData()
  }, [currentPage, yearFilter, statusFilter])

  const handleFilterChange = () => {
    setCurrentPage(1) // Reset to first page when filters change
  }

  const summaryCards = summary ? [
    {
      label: 'Total Contribution',
      value: formatCurrency(summary.totalContribution),
      icon: FiDollarSign,
      tone: 'green',
    },
    {
      label: 'Total Months',
      value: summary.totalMonths.toString(),
      icon: FiCalendar,
      tone: 'brand',
    },
    {
      label: 'Paid Months',
      value: summary.paidMonths.toString(),
      icon: FiCheck,
      tone: 'green',
    },
    {
      label: 'Unpaid Months',
      value: summary.unpaidMonths.toString(),
      icon: FiX,
      tone: 'red',
    },
  ] : []

  if (loading && !summary) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <Loader label="Loading contributions…" />
      </div>
    )
  }

  return (
    <div>
      <PageHeader
        title="My Contributions"
        description="View your contribution history and summary"
      />

      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* Summary Cards */}
      {summary && (
        <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {summaryCards.map((card) => {
            const Icon = card.icon
            return (
              <Card key={card.label}>
                <CardBody className="flex items-center gap-4">
                  <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600">
                    <Icon className="h-6 w-6" />
                  </span>
                  <div>
                    <p className="text-xs text-slate-500">{card.label}</p>
                    <p className="text-lg font-semibold text-slate-800">{card.value}</p>
                  </div>
                </CardBody>
              </Card>
            )
          })}
        </div>
      )}

      {/* Filters */}
      <Card className="mb-6">
        <CardBody>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <Select
              label="Year"
              value={yearFilter}
              onChange={(e) => {
                setYearFilter(e.target.value)
                handleFilterChange()
              }}
              options={[
                { value: '', label: 'All Years' },
                { value: '2026', label: '2026' },
                { value: '2025', label: '2025' },
                { value: '2024', label: '2024' },
              ]}
            />
            <Select
              label="Status"
              value={statusFilter}
              onChange={(e) => {
                setStatusFilter(e.target.value)
                handleFilterChange()
              }}
              options={[
                { value: '', label: 'All Status' },
                { value: 'paid', label: 'Paid' },
                { value: 'unpaid', label: 'Unpaid' },
              ]}
            />
            <div className="flex items-end">
              <Button
                variant="secondary"
                onClick={() => {
                  setYearFilter('')
                  setStatusFilter('')
                  handleFilterChange()
                }}
                className="w-full"
              >
                Clear Filters
              </Button>
            </div>
          </div>
        </CardBody>
      </Card>

      {/* Contributions Table */}
      <Card>
        <CardHeader title="Contribution History" subtitle={`Total: ${contributions.length} records`} />
        <CardBody className="p-0">
          {contributions.length === 0 ? (
            <div className="px-5 py-8 text-center">
              <p className="text-sm text-slate-500">No contributions found</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b border-slate-200 bg-slate-50">
                  <tr>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Month</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Amount</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Status</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Payment Date</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {contributions.map((contribution) => (
                    <tr 
                      key={contribution.id} 
                      className="hover:bg-slate-50 cursor-pointer"
                      onClick={() => navigate(`/member/contributions/${contribution.id}`)}
                    >
                      <td className="px-5 py-4 font-medium text-slate-800">{contribution.label}</td>
                      <td className="px-5 py-4 text-slate-600">{formatCurrency(contribution.amount)}</td>
                      <td className="px-5 py-4">
                        <Badge variant={contribution.status === 'paid' ? 'success' : 'warning'}>
                          {contribution.status}
                        </Badge>
                      </td>
                      <td className="px-5 py-4 text-slate-600">
                        {contribution.paymentDate ? formatDate(contribution.paymentDate) : '-'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardBody>
      </Card>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="mt-4 flex items-center justify-between">
          <Button
            variant="secondary"
            onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
            disabled={currentPage === 1}
          >
            Previous
          </Button>
          <span className="text-sm text-slate-600">
            Page {currentPage} of {totalPages}
          </span>
          <Button
            variant="secondary"
            onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
            disabled={currentPage === totalPages}
          >
            Next
          </Button>
        </div>
      )}
    </div>
  )
}