// Generated by GitHub Copilot
import { FiDollarSign, FiCreditCard, FiClock } from 'react-icons/fi'
import StatCard from '../../components/cards/StatCard.jsx'
import Card, { CardHeader, CardBody } from '../../components/ui/Card.jsx'
import PageHeader from '../../components/ui/PageHeader.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import ContributionsTable from '../../components/tables/ContributionsTable.jsx'
import { StatCardSkeleton } from '../../components/ui/Skeleton.jsx'
import { useData } from '../../hooks/useData.js'
import { useSettings } from '../../hooks/useSettings.js'
import { useSimulatedLoading } from '../../hooks/useSimulatedLoading.js'
import { currentMemberId } from '../../data/members.js'
import { formatCurrency } from '../../utils/format.js'

/** Member landing dashboard with personal KPIs and recent contributions. */
export default function MemberDashboard() {
  const { getMemberById, getContributionsByMember, getLoansByMember } = useData()
  const { monthlyAmount } = useSettings()
  const loading = useSimulatedLoading()

  const member = getMemberById(currentMemberId)
  const contributions = getContributionsByMember(currentMemberId)
  const loans = getLoansByMember(currentMemberId)
  const activeLoan = loans.find((l) => l.status === 'active')

  const nextDue = contributions.find((c) => c.status === 'unpaid')

  const cards = [
    {
      label: 'Total Contribution',
      value: formatCurrency(member?.totalContribution ?? 0),
      icon: FiDollarSign,
      tone: 'green',
    },
    {
      label: 'Current Loan Balance',
      value: formatCurrency(activeLoan?.remaining ?? 0),
      icon: FiCreditCard,
      tone: 'amber',
    },
    {
      label: 'Next Contribution Due',
      value: nextDue ? nextDue.label : 'Up to date',
      icon: FiClock,
      tone: 'brand',
    },
  ]

  return (
    <div>
      <PageHeader
        title={`Welcome, ${member?.name?.split(' ')[0] ?? 'Member'}`}
        description="Here is a snapshot of your account."
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {loading
          ? Array.from({ length: 3 }).map((_, i) => <StatCardSkeleton key={i} />)
          : cards.map((c) => <StatCard key={c.label} {...c} />)}
      </div>

      <div className="mt-4 rounded-xl border border-brand-100 bg-brand-50 px-5 py-4">
        <p className="text-sm text-brand-700">
          Your monthly contribution is{' '}
          <span className="font-semibold">{formatCurrency(monthlyAmount)}</span>.
          {nextDue
            ? ` Payment for ${nextDue.label} is pending.`
            : ' You are all caught up. Thank you!'}
        </p>
      </div>

      <Card className="mt-6">
        <CardHeader
          title="Recent Contributions"
          subtitle="Your latest payment history"
        />
        <CardBody className="p-0">
          {contributions.length === 0 ? (
            <EmptyState title="No contributions yet" />
          ) : (
            <ContributionsTable contributions={contributions.slice(0, 6)} />
          )}
        </CardBody>
      </Card>
    </div>
  )
}
