// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { FiDollarSign, FiCreditCard, FiClock, FiUser } from 'react-icons/fi'
import StatCard from '../../components/cards/StatCard.jsx'
import Card, { CardHeader, CardBody } from '../../components/ui/Card.jsx'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Badge from '../../components/ui/Badge.jsx'
import { StatCardSkeleton } from '../../components/ui/Skeleton.jsx'
import { memberDashboardApi } from '../../api/memberDashboardApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'
import Loader from '../../components/ui/Loader.jsx'

/** Member landing dashboard with real data from API. */
export default function MemberDashboard() {
  const [dashboard, setDashboard] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const fetchDashboard = async () => {
      setLoading(true)
      setError('')
      try {
        const data = await memberDashboardApi.getMyDashboard()
        setDashboard(data)
      } catch (err) {
        setError(err.message || 'Failed to load dashboard')
      } finally {
        setLoading(false)
      }
    }
    fetchDashboard()
  }, [])

  // Check if user just changed password
  const [showPasswordSuccess, setShowPasswordSuccess] = useState(false)

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search)
    if (urlParams.get('passwordChanged') === 'true') {
      setShowPasswordSuccess(true)
      window.history.replaceState({}, '', '/member/dashboard')
      setTimeout(() => setShowPasswordSuccess(false), 5000)
    }
  }, [])

  if (loading) {
    return (
      <div>
        <PageHeader title="Welcome" description="Loading your dashboard…" />
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
          {Array.from({ length: 3 }).map((_, i) => <StatCardSkeleton key={i} />)}
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div>
        <PageHeader title="Dashboard" description="Your account overview" />
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
      </div>
    )
  }

  if (!dashboard) {
    return <div className="flex min-h-[60vh] items-center justify-center"><Loader label="Loading…" /></div>
  }

  const { profile, totalContribution, totalLoan, remainingLoan, lastContribution, activeLoans } = dashboard

  const cards = [
    {
      label: 'Total Contribution',
      value: formatCurrency(totalContribution),
      icon: FiDollarSign,
      tone: 'green',
    },
    {
      label: 'Total Loan',
      value: formatCurrency(totalLoan),
      icon: FiCreditCard,
      tone: 'brand',
    },
    {
      label: 'Remaining Loan',
      value: formatCurrency(remainingLoan),
      icon: FiClock,
      tone: 'amber',
    },
  ]

  return (
    <div>
      <PageHeader
        title={`Welcome, ${profile?.name?.split(' ')[0] ?? 'Member'}`}
        description="Here is a snapshot of your account."
      />

      {showPasswordSuccess && (
        <div className="mb-4 rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">
          Password changed successfully! Your account is now secure.
        </div>
      )}

      {/* Profile Card */}
      <Card className="mb-6">
        <CardBody>
          <div className="flex items-center gap-4">
            <span className="flex h-14 w-14 items-center justify-center rounded-full bg-brand-100 text-brand-600">
              <FiUser className="h-7 w-7" />
            </span>
            <div className="flex-1">
              <h3 className="text-lg font-semibold text-slate-800">{profile?.name}</h3>
              <p className="text-sm text-slate-500">{profile?.email} · {profile?.mobile}</p>
              <div className="mt-1 flex items-center gap-3">
                <Badge variant={profile?.status === 'Active' ? 'success' : 'warning'}>{profile?.status}</Badge>
                <span className="text-xs text-slate-400">Joined {profile?.joiningDate ? formatDate(profile.joiningDate) : 'N/A'}</span>
              </div>
            </div>
          </div>
        </CardBody>
      </Card>

      {/* Stats Cards */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
        {cards.map((c) => <StatCard key={c.label} {...c} />)}
      </div>

      {/* Last Contribution */}
      {lastContribution && (
        <Card className="mb-6">
          <CardHeader title="Last Contribution" subtitle={lastContribution.label} />
          <CardBody>
            <div className="flex items-center justify-between">
              <div>
                <p className="text-2xl font-bold text-slate-800">{formatCurrency(lastContribution.amount)}</p>
                <p className="text-sm text-slate-500">
                  {lastContribution.paymentDate ? `Paid on ${formatDate(lastContribution.paymentDate)}` : 'Not yet paid'}
                </p>
              </div>
              <Badge variant={lastContribution.status === 'paid' ? 'success' : 'warning'}>
                {lastContribution.status}
              </Badge>
            </div>
          </CardBody>
        </Card>
      )}

      {/* Active Loans */}
      {activeLoans.length > 0 && (
        <Card>
          <CardHeader title="Active Loans" subtitle={`${activeLoans.length} active loan(s)`} />
          <CardBody className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b border-slate-200 bg-slate-50">
                  <tr>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Amount</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Remaining</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Issue Date</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Due Date</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {activeLoans.map((loan) => (
                    <tr key={loan.id} className="hover:bg-slate-50">
                      <td className="px-5 py-4 font-medium text-slate-800">{formatCurrency(loan.amount)}</td>
                      <td className="px-5 py-4 text-slate-600">{formatCurrency(loan.remaining)}</td>
                      <td className="px-5 py-4 text-slate-600">{formatDate(loan.issueDate)}</td>
                      <td className="px-5 py-4 text-slate-600">{formatDate(loan.dueDate)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardBody>
        </Card>
      )}

      {totalContribution === 0 && activeLoans.length === 0 && (
        <div className="mt-6 rounded-xl border border-blue-100 bg-blue-50 px-5 py-4">
          <p className="text-sm text-blue-700">
            💡 Your dashboard will populate once contributions and loans are recorded by the admin.
          </p>
        </div>
      )}
    </div>
  )
}