// Generated by GitHub Copilot
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiLock } from 'react-icons/fi'
import { RiBankFill } from 'react-icons/ri'
import { memberApi } from '../../api/memberApi.js'
import { useAuth } from '../../hooks/useAuth.js'
import Button from '../../components/ui/Button.jsx'
import Input from '../../components/ui/Input.jsx'

/**
 * Forces the member to change their initial password before they can access
 * any other part of the member area. This page is shown immediately after
 * first login (when `mustChangePassword` is true).
 */
export default function ForceChangePassword() {
  const { user, logout } = useAuth()
  const navigate = useNavigate()
  const [currentPassword, setCurrentPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirmNewPassword, setConfirmNewPassword] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)

  const canSubmit =
    currentPassword.trim() !== '' &&
    newPassword.trim() !== '' &&
    confirmNewPassword.trim() !== ''

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!canSubmit) return

    if (newPassword !== confirmNewPassword) {
      setError('New passwords do not match')
      return
    }

    if (newPassword.length < 6) {
      setError('New password must be at least 6 characters')
      return
    }

    setError('')
    setSubmitting(true)
    try {
      await memberApi.updatePassword({
        currentPassword,
        newPassword,
        confirmNewPassword,
      })
      navigate('/member/dashboard?passwordChanged=true', { replace: true })
    } catch (err) {
      setError(err.message || 'Failed to update password. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="flex min-h-screen">
      {/* Brand panel */}
      <div className="relative hidden w-1/2 flex-col justify-between overflow-hidden bg-gradient-to-br from-indigo-600 via-blue-600 to-sky-500 p-12 text-white lg:flex">
        <div className="flex items-center gap-3">
          <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15">
            <RiBankFill className="h-6 w-6" />
          </span>
          <span className="text-lg font-bold">Maqasid Bank</span>
        </div>
        <div>
          <h1 className="text-3xl font-bold leading-tight">
            Welcome, {user?.name?.split(' ')[0] ?? 'Member'}
          </h1>
          <p className="mt-4 max-w-md text-indigo-50">
            For security reasons, you must change your password before accessing
            your account. Please choose a strong, unique password.
          </p>
        </div>
        <p className="text-sm text-indigo-100">
          © 2024 Maqasid Bank · All rights reserved
        </p>
        <div className="pointer-events-none absolute -right-24 top-1/3 h-72 w-72 rounded-full bg-sky-400/40 blur-3xl" />
        <div className="pointer-events-none absolute -left-20 bottom-0 h-64 w-64 rounded-full bg-indigo-400/30 blur-3xl" />
      </div>

      {/* Form panel */}
      <div className="flex w-full items-center justify-center bg-slate-50 px-6 py-12 lg:w-1/2">
        <div className="w-full max-w-md">
          <div className="mb-8 text-center lg:hidden">
            <span className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-brand-600 text-white">
              <RiBankFill className="h-6 w-6" />
            </span>
            <h1 className="text-xl font-bold text-slate-800">Maqasid Bank</h1>
          </div>

          <h2 className="text-2xl font-bold text-slate-800">
            Change Your Password
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            You must set a new password to continue.
          </p>

          {error ? (
            <div
              role="alert"
              className="mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"
            >
              {error}
            </div>
          ) : null}

          <form onSubmit={handleSubmit} className="mt-6 space-y-4">
            <Input
              label="Current Password"
              name="currentPassword"
              type="password"
              icon={FiLock}
              placeholder="Enter your current password"
              value={currentPassword}
              onChange={(e) => setCurrentPassword(e.target.value)}
              autoComplete="current-password"
            />
            <Input
              label="New Password"
              name="newPassword"
              type="password"
              icon={FiLock}
              placeholder="At least 6 characters"
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              autoComplete="new-password"
            />
            <Input
              label="Confirm New Password"
              name="confirmNewPassword"
              type="password"
              icon={FiLock}
              placeholder="Re-enter your new password"
              value={confirmNewPassword}
              onChange={(e) => setConfirmNewPassword(e.target.value)}
              autoComplete="new-password"
            />

            <Button
              type="submit"
              size="lg"
              className="w-full"
              disabled={submitting || !canSubmit}
            >
              {submitting ? 'Updating…' : 'Change Password & Continue'}
            </Button>
          </form>

          <div className="mt-6 text-center">
            <button
              type="button"
              onClick={logout}
              className="text-sm text-slate-400 underline hover:text-slate-600"
            >
              Sign out
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}