// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { FiArrowLeft, FiCreditCard, FiCheckCircle, FiTrendingDown } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Button from '../../components/ui/Button.jsx'
import { memberLoanApi } from '../../api/memberLoanApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'
import Loader from '../../components/ui/Loader.jsx'

/** Member loan details with payment history from real API. */
export default function MemberLoanDetails() {
  const [summary, setSummary] = useState(null)
  const [loans, setLoans] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true)
      setError('')
      try {
        const [summaryData, loansData] = await Promise.all([
          memberLoanApi.getMyLoanSummary(),
          memberLoanApi.getMyLoans({ limit: 10 }),
        ])
        setSummary(summaryData)
        setLoans(loansData.loans || [])
      } catch (err) {
        setError(err.message || 'Failed to load loan data')
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  if (loading) {
    return <div className="flex min-h-[60vh] items-center justify-center"><Loader label="Loading loan data…" /></div>
  }

  if (error) {
    return (
      <div>
        <PageHeader title="Loan Details" description="Your loan overview." />
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
      </div>
    )
  }

  const activeLoan = loans.find((l) => l.status === 'active')

  if (!activeLoan && loans.length === 0) {
    return (
      <div>
        <PageHeader title="Loan Details" description="Your loan overview." />
        <Card>
          <CardBody className="flex flex-col items-center gap-4 py-8 text-center">
            <FiCreditCard className="h-12 w-12 text-slate-300" />
            <h3 className="text-lg font-semibold text-slate-800">No loans found</h3>
            <p className="text-sm text-slate-500">You currently have no loans. Contact the admin to apply.</p>
          </CardBody>
        </Card>
      </div>
    )
  }

  return (
    <div>
      <PageHeader title="Loan Details" description="Overview of your loans." />

      {/* Summary Cards */}
      {summary && (
        <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-4">
          <Card><CardBody className="flex items-center gap-4">
            <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiCreditCard className="h-6 w-6" /></span>
            <div><p className="text-xs text-slate-500">Total Borrowed</p><p className="text-lg font-semibold text-slate-800">{formatCurrency(summary.totalBorrowed)}</p></div>
          </CardBody></Card>
          <Card><CardBody className="flex items-center gap-4">
            <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiCheckCircle className="h-6 w-6" /></span>
            <div><p className="text-xs text-slate-500">Remaining</p><p className="text-lg font-semibold text-slate-800">{formatCurrency(summary.totalRemaining)}</p></div>
          </CardBody></Card>
          <Card><CardBody className="flex items-center gap-4">
            <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiTrendingDown className="h-6 w-6" /></span>
            <div><p className="text-xs text-slate-500">Active Loans</p><p className="text-lg font-semibold text-slate-800">{summary.activeLoans}</p></div>
          </CardBody></Card>
          <Card><CardBody className="flex items-center gap-4">
            <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiCreditCard className="h-6 w-6" /></span>
            <div><p className="text-xs text-slate-500">Closed Loans</p><p className="text-lg font-semibold text-slate-800">{summary.closedLoans}</p></div>
          </CardBody></Card>
        </div>
      )}

      {/* Loans List */}
      <Card>
        <CardHeader title="My Loans" subtitle={`${loans.length} loan(s)`} />
        <CardBody className="p-0">
          {loans.length === 0 ? (
            <div className="px-5 py-8 text-center"><p className="text-sm text-slate-500">No loans found</p></div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b border-slate-200 bg-slate-50">
                  <tr>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Issue Date</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Amount</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Remaining</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Due Date</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {loans.map((loan) => (
                    <tr key={loan.id} className="hover:bg-slate-50 cursor-pointer">
                      <td className="px-5 py-4 font-medium text-slate-800">{formatDate(loan.issueDate)}</td>
                      <td className="px-5 py-4 text-slate-600">{formatCurrency(loan.amount)}</td>
                      <td className="px-5 py-4 text-slate-600">{formatCurrency(loan.remaining)}</td>
                      <td className="px-5 py-4 text-slate-600">{formatDate(loan.dueDate)}</td>
                      <td className="px-5 py-4"><Badge variant={loan.status === 'active' ? 'success' : 'slate'}>{loan.status}</Badge></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardBody>
      </Card>
    </div>
  )
}
