// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { FiArrowLeft, FiCreditCard, FiCheckCircle, FiTrendingDown } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Button from '../../components/ui/Button.jsx'
import { memberLoanApi } from '../../api/memberLoanApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'
import Loader from '../../components/ui/Loader.jsx'

export default function LoanPassbook() {
  const { loanId } = useParams()
  const navigate = useNavigate()
  const [passbook, setPassbook] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const fetchPassbook = async () => {
      setLoading(true)
      setError('')
      try {
        const data = await memberLoanApi.getMyLoanPassbook(loanId)
        setPassbook(data)
      } catch (err) {
        setError(err.message || 'Failed to load loan passbook')
      } finally {
        setLoading(false)
      }
    }

    if (loanId) {
      fetchPassbook()
    }
  }, [loanId])

  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <Loader label="Loading loan passbook…" />
      </div>
    )
  }

  if (error) {
    return (
      <div>
        <PageHeader title="Loan Passbook" description="View loan details and payment history" />
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
        <Button variant="secondary" onClick={() => navigate('/member/loans')} className="mt-4">
          <FiArrowLeft className="mr-2 h-4 w-4" /> Back to Loans
        </Button>
      </div>
    )
  }

  if (!passbook) {
    return (
      <div>
        <PageHeader title="Loan Passbook" description="View loan details and payment history" />
        <div className="rounded-lg border border-yellow-200 bg-yellow-50 px-4 py-3 text-sm text-yellow-700">Loan not found</div>
        <Button variant="secondary" onClick={() => navigate('/member/loans')} className="mt-4">
          <FiArrowLeft className="mr-2 h-4 w-4" /> Back to Loans
        </Button>
      </div>
    )
  }

  const { loan, payments, summary } = passbook

  return (
    <div>
      <PageHeader title="Loan Passbook" description={`Loan #${loan.id} · ${formatCurrency(loan.amount)}`} />
      <Button variant="secondary" onClick={() => navigate('/member/loans')} className="mb-6">
        <FiArrowLeft className="mr-2 h-4 w-4" /> Back to Loans
      </Button>

      {/* Stats */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
        <Card><CardBody className="flex items-center gap-4">
          <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiCreditCard className="h-6 w-6" /></span>
          <div><p className="text-xs text-slate-500">Total Loan</p><p className="text-lg font-semibold text-slate-800">{formatCurrency(loan.amount)}</p></div>
        </CardBody></Card>
        <Card><CardBody className="flex items-center gap-4">
          <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiCheckCircle className="h-6 w-6" /></span>
          <div><p className="text-xs text-slate-500">Total Paid</p><p className="text-lg font-semibold text-slate-800">{formatCurrency(summary.totalPaid)}</p></div>
        </CardBody></Card>
        <Card><CardBody className="flex items-center gap-4">
          <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FiTrendingDown className="h-6 w-6" /></span>
          <div><p className="text-xs text-slate-500">Remaining</p><p className="text-lg font-semibold text-slate-800">{formatCurrency(summary.remainingBalance)}</p></div>
        </CardBody></Card>
      </div>

      {/* Loan Info */}
      <Card className="mb-6">
        <CardHeader title="Loan Information" />
        <CardBody>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div><p className="text-xs text-slate-500">Issue Date</p><p className="mt-1 text-sm font-medium text-slate-800">{formatDate(loan.issueDate)}</p></div>
            {loan.status === 'paid' ? (
              <div><p className="text-xs text-slate-500">Closure Date</p><p className="mt-1 text-sm font-medium text-slate-800">{loan.closedAt ? formatDate(loan.closedAt) : 'N/A'}</p></div>
            ) : (
              <div><p className="text-xs text-slate-500">Due Date</p><p className="mt-1 text-sm font-medium text-slate-800">{loan.dueDate ? formatDate(loan.dueDate) : 'N/A'}</p></div>
            )}
            <div><p className="text-xs text-slate-500">Status</p><div className="mt-1"><Badge variant={loan.status === 'active' ? 'success' : 'slate'}>{loan.status}</Badge></div></div>
            <div><p className="text-xs text-slate-500">Total Payments</p><p className="mt-1 text-sm font-medium text-slate-800">{summary.totalPayments}</p></div>
            {summary.lastPaymentDate && (<div><p className="text-xs text-slate-500">Last Payment</p><p className="mt-1 text-sm font-medium text-slate-800">{formatDate(summary.lastPaymentDate)}</p></div>)}
          </div>
        </CardBody>
      </Card>

      {/* Payments */}
      <Card>
        <CardHeader title="Payment History" subtitle={`${payments.length} payments`} />
        <CardBody className="p-0">
          {payments.length === 0 ? (
            <div className="px-5 py-8 text-center"><p className="text-sm text-slate-500">No payments recorded yet</p></div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b border-slate-200 bg-slate-50">
                  <tr>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">#</th>
                    <th className="px-5 py-3 text-left font-semibold text-slate-700">Date</th>
                    <th className="px-5 py-3 text-right font-semibold text-slate-700">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {payments.map((payment, index) => (
                    <tr key={payment.id} className="hover:bg-slate-50">
                      <td className="px-5 py-4 text-slate-600">{index + 1}</td>
                      <td className="px-5 py-4 font-medium text-slate-800">
                        {payment.paymentDate ? formatDate(payment.paymentDate) : 'N/A'}
                      </td>
                      <td className="px-5 py-4 text-right text-slate-600">{formatCurrency(payment.amount)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardBody>
      </Card>
    </div>
  )
}
