// Generated by GitHub Copilot
import { FiCreditCard, FiCheckCircle, FiTrendingDown } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import StatCard from '../../components/cards/StatCard.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import RepaymentTable from '../../components/tables/RepaymentTable.jsx'
import { useData } from '../../hooks/useData.js'
import { currentMemberId } from '../../data/members.js'
import { formatCurrency } from '../../utils/format.js'

/** Member loan details: totals plus repayment history for the active loan. */
export default function MemberLoanDetails() {
  const { getLoansByMember } = useData()

  const loans = getLoansByMember(currentMemberId)
  const loan = loans.find((l) => l.status === 'active') || loans[0]

  if (!loan) {
    return (
      <div>
        <PageHeader title="Loan Details" description="Your loan overview." />
        <Card>
          <EmptyState
            icon={FiCreditCard}
            title="No active loan"
            description="You currently have no loans. Contact the admin to apply."
          />
        </Card>
      </div>
    )
  }

  const paid = loan.amount - loan.remaining

  return (
    <div>
      <PageHeader
        title="Loan Details"
        description="Overview and repayment history of your loan."
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <StatCard
          label="Total Loan"
          value={formatCurrency(loan.amount)}
          icon={FiCreditCard}
          tone="brand"
        />
        <StatCard
          label="Paid Amount"
          value={formatCurrency(paid)}
          icon={FiCheckCircle}
          tone="green"
        />
        <StatCard
          label="Remaining Balance"
          value={formatCurrency(loan.remaining)}
          icon={FiTrendingDown}
          tone="amber"
        />
      </div>

      <Card className="mt-6">
        <CardHeader
          title="Payment History"
          subtitle={`Loan #${loan.id} · issued for ${formatCurrency(loan.amount)}`}
        />
        {loan.repayments.length === 0 ? (
          <EmptyState title="No repayments recorded yet" />
        ) : (
          <RepaymentTable repayments={loan.repayments} />
        )}
      </Card>
    </div>
  )
}
