// Generated by GitHub Copilot
import {
  FiUser,
  FiPhone,
  FiMail,
  FiCalendar,
  FiDollarSign,
  FiCreditCard,
} from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Badge from '../../components/ui/Badge.jsx'
import { useData } from '../../hooks/useData.js'
import { currentMemberId } from '../../data/members.js'
import { formatCurrency, formatDate, getInitials } from '../../utils/format.js'

/** Member profile page: personal details, joining date and account summary. */
export default function MemberProfile() {
  const { getMemberById, getLoansByMember } = useData()

  const member = getMemberById(currentMemberId)
  const loans = getLoansByMember(currentMemberId)
  const activeLoan = loans.find((l) => l.status === 'active')

  return (
    <div>
      <PageHeader
        title="My Profile"
        description="Your personal and account information."
      />

      <Card className="mb-6">
        <CardBody className="flex flex-col items-center gap-4 sm:flex-row sm:items-center">
          <span
            className="flex h-20 w-20 items-center justify-center rounded-full text-2xl font-semibold text-white"
            style={{ backgroundColor: member?.avatarColor }}
          >
            {getInitials(member?.name)}
          </span>
          <div className="text-center sm:text-left">
            <div className="flex items-center justify-center gap-3 sm:justify-start">
              <h2 className="text-xl font-bold text-slate-800">
                {member?.name}
              </h2>
              <Badge>{member?.status}</Badge>
            </div>
            <p className="text-sm text-slate-400">Member ID · {member?.id}</p>
          </div>
        </CardBody>
      </Card>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader title="Personal Details" />
          <CardBody>
            <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2">
              <Detail icon={FiUser} label="Full Name" value={member?.name} />
              <Detail icon={FiPhone} label="Mobile" value={member?.mobile} />
              <Detail icon={FiMail} label="Email" value={member?.email} />
              <Detail
                icon={FiCalendar}
                label="Joining Date"
                value={formatDate(member?.joiningDate)}
              />
            </dl>
          </CardBody>
        </Card>

        <Card>
          <CardHeader title="Account Summary" />
          <CardBody>
            <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2">
              <Detail
                icon={FiDollarSign}
                label="Total Contributions"
                value={formatCurrency(member?.totalContribution ?? 0)}
              />
              <Detail
                icon={FiCreditCard}
                label="Active Loan"
                value={formatCurrency(activeLoan?.remaining ?? 0)}
              />
              <Detail
                icon={FiCreditCard}
                label="Total Loans Taken"
                value={String(loans.length)}
              />
              <Detail
                icon={FiCreditCard}
                label="Loan Status"
                value={activeLoan ? 'Active' : 'None'}
              />
            </dl>
          </CardBody>
        </Card>
      </div>
    </div>
  )
}

/** Labelled detail row with an icon. */
function Detail({ icon: Icon, label, value }) {
  return (
    <div className="flex items-start gap-3">
      <span className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-500">
        <Icon className="h-4 w-4" />
      </span>
      <div>
        <dt className="text-xs text-slate-400">{label}</dt>
        <dd className="text-sm font-medium text-slate-800">{value}</dd>
      </div>
    </div>
  )
}
