// Generated by GitHub Copilot
const LoanRequest = require('../models/LoanRequest')
const ApiError = require('../utils/ApiError')
const loanService = require('./loanService')
const { sortPendingQueue } = require('../utils/loanQueue')
const { logAudit } = require('../utils/auditLogger')
const { createNotification } = require('../utils/notificationHelper')

/**
 * Get all loan requests (excluding withdrawn), annotated with queue position,
 * funding ahead, and eligibility. Also returns current available funds.
 * @returns {Promise<{ requests: object[], availableFunds: number }>}
 */
async function getAllLoanRequests() {
  const [requests, availableFunds] = await Promise.all([
    LoanRequest.find({ status: { $ne: 'withdrawn' } })
      .populate('memberId', 'name')
      .lean(),
    loanService.getAvailableFunds(),
  ])

  const pending = requests.filter((r) => r.status === 'pending')
  const ordered = sortPendingQueue(pending)
  const queueInfo = new Map()
  let cumulative = 0
  ordered.forEach((req, index) => {
    queueInfo.set(String(req._id), { position: index + 1, fundingAhead: cumulative })
    cumulative += Number(req.amount || 0)
  })

  const mapped = requests.map((doc) => {
    const info = queueInfo.get(String(doc._id))
    return {
      id: doc._id,
      memberId: doc.memberId?._id,
      memberName: doc.memberId?.name || 'Unknown',
      amount: doc.amount,
      monthRequired: doc.monthRequired,
      expectedReturn: doc.expectedReturn,
      purpose: doc.purpose,
      notes: doc.notes,
      adminNotes: doc.adminNotes,
      status: doc.status,
      loanId: doc.loanId,
      position: info?.position ?? null,
      fundingAhead: info ? info.fundingAhead : null,
      eligible: doc.status === 'pending' ? Number(doc.amount) <= availableFunds : null,
      createdAt: doc.createdAt,
    }
  })

  // Sort: pending first (by queue position), then the rest by newest.
  mapped.sort((a, b) => {
    if (a.status === 'pending' && b.status === 'pending') return a.position - b.position
    if (a.status === 'pending') return -1
    if (b.status === 'pending') return 1
    return new Date(b.createdAt) - new Date(a.createdAt)
  })

  return { requests: mapped, availableFunds }
}

/**
 * Approve a loan request: create the actual Loan (funds-checked), then mark
 * the request approved and link it to the new loan.
 * @param {string} requestId
 * @param {{ amount, monthRequired, expectedReturn, notes }} body
 * @param {object} [meta] - Audit metadata.
 * @returns {Promise<object>} Updated loan request
 */
async function approveLoanRequest(requestId, body, meta = {}) {
  const request = await LoanRequest.findById(requestId)
  if (!request) {
    throw new ApiError(404, 'Loan request not found')
  }
  if (request.status !== 'pending') {
    throw new ApiError(400, 'Only pending requests can be approved')
  }

  const amount = body.amount !== undefined ? Number(body.amount) : request.amount
  const monthRequired = body.monthRequired !== undefined ? body.monthRequired : request.monthRequired
  const expectedReturn =
    body.expectedReturn !== undefined ? body.expectedReturn || null : request.expectedReturn

  // Create the actual loan; this re-checks available funds and throws on shortfall.
  const loan = await loanService.createLoan(
    request.memberId,
    {
      amount,
      issueDate: new Date(),
      dueDate: expectedReturn,
      notes: request.purpose ? `Loan request: ${request.purpose}` : '',
    },
    meta,
  )

  request.status = 'approved'
  request.amount = amount
  request.monthRequired = monthRequired
  request.expectedReturn = expectedReturn
  request.loanId = loan._id
  if (body.notes !== undefined) request.adminNotes = body.notes
  await request.save()

  logAudit(meta, {
    action: 'LOAN_REQUEST_APPROVED',
    entity: 'LoanRequest',
    entityId: request._id,
    description: `Loan request approved and loan of ${amount} issued`,
  })

  createNotification({
    recipientId: request.memberId,
    recipientRole: 'member',
    title: 'Loan request approved',
    message: `Your loan request for ₹${Number(amount).toLocaleString('en-IN')} has been approved.`,
    type: 'success',
    relatedEntity: 'Loan',
    relatedEntityId: loan._id,
  })

  return toLoanRequest(request)
}

/**
 * Reject a loan request.
 * @param {string} requestId
 * @param {{ notes }} body
 * @param {object} [meta] - Audit metadata.
 * @returns {Promise<object>} Updated loan request
 */
async function rejectLoanRequest(requestId, body, meta = {}) {
  const request = await LoanRequest.findById(requestId)
  if (!request) {
    throw new ApiError(404, 'Loan request not found')
  }
  if (request.status !== 'pending') {
    throw new ApiError(400, 'Only pending requests can be rejected')
  }

  request.status = 'rejected'
  if (body.notes !== undefined) request.adminNotes = body.notes
  await request.save()

  logAudit(meta, {
    action: 'LOAN_REQUEST_REJECTED',
    entity: 'LoanRequest',
    entityId: request._id,
    description: 'Loan request rejected',
  })

  createNotification({
    recipientId: request.memberId,
    recipientRole: 'member',
    title: 'Loan request rejected',
    message: body.notes
      ? `Your loan request was rejected: ${body.notes}`
      : 'Your loan request was rejected.',
    type: 'warning',
    relatedEntity: 'LoanRequest',
    relatedEntityId: request._id,
  })

  return toLoanRequest(request)
}

/**
 * Move a pending request up or down the queue by swapping priority with its
 * neighbour.
 * @param {string} requestId
 * @param {'up'|'down'} direction
 * @returns {Promise<{ requests: object[], availableFunds: number }>} Updated queue
 */
async function reorderQueue(requestId, direction) {
  const pending = await LoanRequest.find({ status: 'pending' })
  const ordered = sortPendingQueue(pending)
  const index = ordered.findIndex((r) => String(r._id) === String(requestId))
  if (index === -1) {
    throw new ApiError(404, 'Pending loan request not found')
  }

  const swapIndex = direction === 'up' ? index - 1 : index + 1
  if (swapIndex < 0 || swapIndex >= ordered.length) {
    throw new ApiError(400, `Request is already at the ${direction === 'up' ? 'top' : 'bottom'} of the queue`)
  }

  const target = ordered[index]
  const neighbour = ordered[swapIndex]
  const targetOrder = target.queueOrder != null ? target.queueOrder : new Date(target.createdAt).getTime()
  const neighbourOrder = neighbour.queueOrder != null ? neighbour.queueOrder : new Date(neighbour.createdAt).getTime()

  target.queueOrder = neighbourOrder
  neighbour.queueOrder = targetOrder
  await Promise.all([target.save(), neighbour.save()])

  return getAllLoanRequests()
}

function toLoanRequest(doc) {
  return {
    id: doc._id,
    amount: doc.amount,
    monthRequired: doc.monthRequired,
    expectedReturn: doc.expectedReturn,
    purpose: doc.purpose,
    notes: doc.notes,
    adminNotes: doc.adminNotes,
    status: doc.status,
    loanId: doc.loanId,
    createdAt: doc.createdAt,
  }
}

module.exports = { getAllLoanRequests, approveLoanRequest, rejectLoanRequest, reorderQueue }