// Generated by GitHub Copilot
const AuditLog = require('../models/AuditLog')

/**
 * Retrieve paginated audit logs with optional filters.
 *
 * @param {object} filters
 * @param {string}  [filters.action]          - Filter by a specific action enum value
 * @param {string}  [filters.entity]          - Filter by entity type
 * @param {string}  [filters.performedByRole] - 'admin' or 'member'
 * @param {string}  [filters.startDate]       - ISO date string – lower bound on createdAt
 * @param {string}  [filters.endDate]         - ISO date string – upper bound on createdAt
 * @param {number}  [filters.page=1]
 * @param {number}  [filters.limit=20]
 * @returns {Promise<{ logs: object[], total: number, page: number, pages: number }>}
 */
async function getAuditLogs({ action, entity, performedByRole, startDate, endDate, page = 1, limit = 20 } = {}) {
  const filter = {}

  if (action) filter.action = action
  if (entity) filter.entity = entity
  if (performedByRole) filter.performedByRole = performedByRole

  if (startDate || endDate) {
    filter.createdAt = {}
    if (startDate) filter.createdAt.$gte = new Date(startDate)
    if (endDate) {
      const end = new Date(endDate)
      end.setHours(23, 59, 59, 999)
      filter.createdAt.$lte = end
    }
  }

  const safeLimit = Math.min(Number(limit) || 20, 100)
  const safePage = Math.max(Number(page) || 1, 1)
  const skip = (safePage - 1) * safeLimit

  const [logs, total] = await Promise.all([
    AuditLog.find(filter).sort({ createdAt: -1 }).skip(skip).limit(safeLimit).lean(),
    AuditLog.countDocuments(filter),
  ])

  return {
    logs,
    total,
    page: safePage,
    pages: Math.ceil(total / safeLimit),
  }
}

module.exports = { getAuditLogs }
