// Generated by GitHub Copilot
const ApiError = require('../utils/ApiError')
const generateToken = require('../utils/generateToken')
const Admin = require('../models/Admin')
const Member = require('../models/Member')
const { logAudit } = require('../utils/auditLogger')

/**
 * Shape an account document into a safe, API-friendly object (no password).
 * @param {object} account - Mongoose document.
 * @param {'admin'|'member'} role
 */
function toPublicUser(account, role) {
  const base = {
    id: account._id,
    name: account.name,
    email: account.email,
    role,
  }
  if (role === 'member') {
    base.mobile = account.mobile
    base.joiningDate = account.joiningDate
    base.status = account.status
    base.mustChangePassword = account.mustChangePassword
  }
  return base
}

/**
 * Authenticate an admin by email + password.
 * @returns {Promise<{ token: string, user: object }>}
 */
async function loginAdmin(email, password, meta = {}) {
  const admin = await Admin.findOne({ email: email.toLowerCase() }).select(
    '+password',
  )
  if (!admin || !(await admin.matchPassword(password))) {
    throw new ApiError(401, 'Invalid email or password')
  }
  const token = generateToken(admin._id, 'admin')
  logAudit(
    { performedBy: admin._id, performedByRole: 'admin', performedByName: admin.name, ...meta },
    { action: 'LOGIN', entity: 'Auth', description: `Admin ${admin.name} logged in` },
  )
  return { token, user: toPublicUser(admin, 'admin') }
}

/**
 * Authenticate a member by mobile/email + password.
 * @param {string} identifier - Mobile number or email.
 * @returns {Promise<{ token: string, user: object }>}
 */
async function loginMember(identifier, password, meta = {}) {
  const query = /^\d{10}$/.test(identifier)
    ? { mobile: identifier }
    : { email: identifier.toLowerCase() }

  const member = await Member.findOne(query).select('+password')
  if (!member || !(await member.matchPassword(password))) {
    throw new ApiError(401, 'Invalid email or password')
  }
  if (member.status === 'Inactive') {
    throw new ApiError(403, 'Your account is inactive. Contact the admin.')
  }
  const token = generateToken(member._id, 'member')
  logAudit(
    { performedBy: member._id, performedByRole: 'member', performedByName: member.name, ...meta },
    { action: 'LOGIN', entity: 'Auth', description: `Member ${member.name} logged in` },
  )
  return { token, user: toPublicUser(member, 'member') }
}

module.exports = { loginAdmin, loginMember, toPublicUser }
