// Generated by GitHub Copilot
const Contribution = require('../models/Contribution')
const Member = require('../models/Member')
const ContributionSetting = require('../models/ContributionSetting')
const ApiError = require('../utils/ApiError')
const { logAudit } = require('../utils/auditLogger')
const { createNotification } = require('../utils/notificationHelper')

/**
 * Generate contribution records for all active members for a given month.
 * Skips members who already have a record for that month.
 * @param {string} month - YYYY-MM format
 * @returns {Promise<{ created: number, skipped: number }>}
 */
async function generateMonthlyContributions(month, meta = {}) {
  const settings = await ContributionSetting.getSingleton()
  const activeMembers = await Member.find({ status: 'Active', isDeleted: false })

  let created = 0
  let skipped = 0

  for (const member of activeMembers) {
    const existing = await Contribution.findOne({ memberId: member._id, month })
    if (existing) {
      skipped++
      continue
    }

    await Contribution.create({
      memberId: member._id,
      month,
      amount: settings.monthlyAmount,
      status: 'unpaid',
      paymentDate: null,
    })
    created++
  }

  logAudit(meta, {
    action: 'CONTRIBUTION_RECORDED',
    entity: 'Contribution',
    description: `Generated ${created} contributions for ${month} (${skipped} skipped)`,
    metadata: { month, created, skipped },
  })

  return { created, skipped }
}

/**
 * List contributions with optional filters.
 * @param {{ month?: string, status?: string, search?: string, page?: number, limit?: number }} query
 * @returns {Promise<{ contributions: object[], pagination: object }>}
 */
async function listContributions({ month, status, search, page = 1, limit = 50 } = {}) {
  const filter = {}

  if (month) filter.month = month
  if (status) filter.status = status

  const currentPage = Math.max(1, Number(page) || 1)
  const perPage = Math.min(100, Math.max(1, Number(limit) || 50))
  const skip = (currentPage - 1) * perPage

  const [docs, total] = await Promise.all([
    Contribution.find(filter)
      .populate('memberId', 'name email mobile')
      .sort({ month: -1, createdAt: -1 })
      .skip(skip)
      .limit(perPage),
    Contribution.countDocuments(filter),
  ])

  return {
    contributions: docs.map((c) => ({
      id: c._id,
      memberId: c.memberId?._id || null,
      memberName: c.memberId?.name || 'Unknown Member',
      memberEmail: c.memberId?.email || '',
      memberMobile: c.memberId?.mobile || '',
      month: c.month,
      amount: c.amount,
      status: c.status,
      paymentDate: c.paymentDate,
    })),
    pagination: {
      page: currentPage,
      limit: perPage,
      total,
      totalPages: Math.ceil(total / perPage) || 1,
    },
  }
}

/**
 * Update a contribution's payment status.
 * @param {string} id
 * @param {string} status - 'paid' or 'unpaid'
 * @returns {Promise<object>}
 */
async function updateContributionStatus(id, status, meta = {}) {
  const contribution = await Contribution.findById(id).populate('memberId', 'status name')
  if (!contribution) throw new ApiError(404, 'Contribution not found')

  if (contribution.memberId?.status === 'Inactive') {
    throw new ApiError(400, 'Cannot update contribution status for an inactive member', [
      {
        field: 'status',
        message: 'Inactive members cannot be marked as paid or unpaid',
      },
    ])
  }

  contribution.status = status
  contribution.paymentDate = status === 'paid' ? new Date() : null
  await contribution.save()

  logAudit(meta, {
    action: 'CONTRIBUTION_STATUS_CHANGED',
    entity: 'Contribution',
    entityId: contribution._id,
    description: `Contribution for ${contribution.month} marked as ${status}`,
  })

  if (status === 'paid') {
    // Format month as "Month YYYY" (e.g., "July 2026")
    const [year, month] = contribution.month.split('-')
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    const formattedMonth = `${monthNames[parseInt(month) - 1]} ${year}`

    createNotification({
      recipientId: contribution.memberId?._id || contribution.memberId,
      recipientRole: 'member',
      title: 'Contribution received',
      message: `Your contribution for ${formattedMonth} has been marked as paid.`,
      type: 'success',
      relatedEntity: 'Contribution',
      relatedEntityId: contribution._id,
    })
  }

  return contribution
}

/**
 * Bulk update multiple contributions' payment status.
 * @param {string[]} contributionIds
 * @param {string} status - 'paid' or 'unpaid'
 * @param {object} meta
 * @returns {Promise<{ message: string, updated: number, failed: number }>}
 */
async function bulkUpdateContributionStatus(contributionIds, status, meta = {}) {
  if (!Array.isArray(contributionIds) || contributionIds.length === 0) {
    throw new ApiError(400, 'No contribution IDs provided')
  }

  const contributions = await Contribution.find({ _id: { $in: contributionIds } }).populate('memberId', 'status name')
  
  let updated = 0
  let failed = 0
  const errors = []

  for (const contribution of contributions) {
    try {
      // Check if member is inactive
      if (contribution.memberId?.status === 'Inactive') {
        failed++
        errors.push(`${contribution.memberId?.name || 'Unknown'}: Inactive member`)
        continue
      }

      // Update contribution
      contribution.status = status
      contribution.paymentDate = status === 'paid' ? new Date() : null
      await contribution.save()

      // Log audit
      logAudit(meta, {
        action: 'CONTRIBUTION_STATUS_CHANGED',
        entity: 'Contribution',
        entityId: contribution._id,
        description: `Bulk update: Contribution for ${contribution.month} marked as ${status}`,
      })

      // Send notification if paid
      if (status === 'paid') {
        const [year, month] = contribution.month.split('-')
        const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
        const formattedMonth = `${monthNames[parseInt(month) - 1]} ${year}`

        createNotification({
          recipientId: contribution.memberId?._id || contribution.memberId,
          recipientRole: 'member',
          title: 'Contribution received',
          message: `Your contribution for ${formattedMonth} has been marked as paid.`,
          type: 'success',
          relatedEntity: 'Contribution',
          relatedEntityId: contribution._id,
        })
      }

      updated++
    } catch (error) {
      failed++
      errors.push(`${contribution.memberId?.name || 'Unknown'}: ${error.message}`)
    }
  }

  let message = `Successfully updated ${updated} contribution(s) to ${status}`
  if (failed > 0) {
    message += ` (${failed} failed)`
  }

  return {
    message,
    updated,
    failed,
    errors: errors.length > 0 ? errors : undefined,
  }
}

module.exports = {
  generateMonthlyContributions,
  listContributions,
  updateContributionStatus,
  bulkUpdateContributionStatus,
}
