// Generated by GitHub Copilot
const Contribution = require('../models/Contribution')
const Member = require('../models/Member')
const ContributionSetting = require('../models/ContributionSetting')
const ApiError = require('../utils/ApiError')
const { logAudit } = require('../utils/auditLogger')
const { createNotification } = require('../utils/notificationHelper')

/**
 * Generate contribution records for all active members for a given month.
 * Skips members who already have a record for that month.
 * @param {string} month - YYYY-MM format
 * @returns {Promise<{ created: number, skipped: number }>}
 */
async function generateMonthlyContributions(month, meta = {}) {
  const settings = await ContributionSetting.getSingleton()
  const activeMembers = await Member.find({ status: 'Active', isDeleted: false })

  let created = 0
  let skipped = 0

  for (const member of activeMembers) {
    const existing = await Contribution.findOne({ memberId: member._id, month })
    if (existing) {
      skipped++
      continue
    }

    await Contribution.create({
      memberId: member._id,
      month,
      amount: settings.monthlyAmount,
      status: 'unpaid',
      paymentDate: null,
    })
    created++
  }

  logAudit(meta, {
    action: 'CONTRIBUTION_RECORDED',
    entity: 'Contribution',
    description: `Generated ${created} contributions for ${month} (${skipped} skipped)`,
    metadata: { month, created, skipped },
  })

  return { created, skipped }
}

/**
 * List contributions with optional filters.
 * @param {{ month?: string, status?: string, search?: string, page?: number, limit?: number }} query
 * @returns {Promise<{ contributions: object[], pagination: object }>}
 */
async function listContributions({ month, status, search, page = 1, limit = 50 } = {}) {
  const filter = {}

  if (month) filter.month = month
  if (status) filter.status = status

  const currentPage = Math.max(1, Number(page) || 1)
  const perPage = Math.min(100, Math.max(1, Number(limit) || 50))
  const skip = (currentPage - 1) * perPage

  const [docs, total] = await Promise.all([
    Contribution.find(filter)
      .populate('memberId', 'name email mobile')
      .sort({ month: -1, createdAt: -1 })
      .skip(skip)
      .limit(perPage),
    Contribution.countDocuments(filter),
  ])

  return {
    contributions: docs.map((c) => ({
      id: c._id,
      memberId: c.memberId._id,
      memberName: c.memberId.name,
      memberEmail: c.memberId.email,
      memberMobile: c.memberId.mobile,
      month: c.month,
      amount: c.amount,
      status: c.status,
      paymentDate: c.paymentDate,
    })),
    pagination: {
      page: currentPage,
      limit: perPage,
      total,
      totalPages: Math.ceil(total / perPage) || 1,
    },
  }
}

/**
 * Update a contribution's payment status.
 * @param {string} id
 * @param {string} status - 'paid' or 'unpaid'
 * @returns {Promise<object>}
 */
async function updateContributionStatus(id, status, meta = {}) {
  const contribution = await Contribution.findById(id)
  if (!contribution) throw new ApiError(404, 'Contribution not found')

  contribution.status = status
  contribution.paymentDate = status === 'paid' ? new Date() : null
  await contribution.save()

  logAudit(meta, {
    action: 'CONTRIBUTION_STATUS_CHANGED',
    entity: 'Contribution',
    entityId: contribution._id,
    description: `Contribution for ${contribution.month} marked as ${status}`,
  })

  if (status === 'paid') {
    createNotification({
      recipientId: contribution.memberId,
      recipientRole: 'member',
      title: 'Contribution received',
      message: `Your contribution for ${contribution.month} has been marked as paid.`,
      type: 'success',
      relatedEntity: 'Contribution',
      relatedEntityId: contribution._id,
    })
  }

  return contribution
}

module.exports = {
  generateMonthlyContributions,
  listContributions,
  updateContributionStatus,
}