// Generated by GitHub Copilot
const ContributionSetting = require('../models/ContributionSetting')
const Contribution = require('../models/Contribution')
const ApiError = require('../utils/ApiError')
const { logAudit } = require('../utils/auditLogger')

/**
 * Get the current contribution settings. Auto-creates defaults if none exist.
 * @returns {Promise<object>}
 */
async function getCurrentSettings() {
  const settings = await ContributionSetting.getSingleton()
  return settings
}

/**
 * Update the contribution settings (upsert behaviour).
 * When `monthlyAmount` changes, all existing unpaid contributions are synced
 * to the new amount so the member listing and reports reflect the current value.
 * @param {object} data - Fields to update.
 * @returns {Promise<object>}
 */
async function updateSettings(data, meta = {}) {
  let settings = await ContributionSetting.getSingleton()

  const allowedFields = [
    'monthlyAmount',
    'description',
    'isActive',
  ]

  allowedFields.forEach((field) => {
    if (data[field] !== undefined) {
      settings[field] = data[field]
    }
  })

  await settings.save()

  // Sync the new monthly amount to ALL existing contribution records so the
  // member listing (which sums paid contributions) stays consistent with the
  // universal setting. Both paid and unpaid records are updated because the
  // user expects the setting to apply universally.
  if (data.monthlyAmount !== undefined) {
    await Contribution.updateMany(
      {},
      { $set: { amount: data.monthlyAmount } },
    )
  }

  logAudit(meta, {
    action: 'SETTINGS_UPDATED',
    entity: 'ContributionSetting',
    entityId: settings._id,
    description: 'Contribution settings updated',
    metadata: data,
  })

  return settings
}

module.exports = { getCurrentSettings, updateSettings }
