// Generated by GitHub Copilot
const Contribution = require('../models/Contribution')
const Loan = require('../models/Loan')
const Member = require('../models/Member')
const LoanRepayment = require('../models/LoanRepayment')
const Settlement = require('../models/Settlement')

/**
 * Build the admin dashboard statistics from live aggregation of existing
 * collections (Contributions, Loans, Members).
 * @returns {Promise<object>}
 */
async function getAdminDashboardStats() {
  const now = new Date()
  const currentYear = now.getFullYear()
  const currentMonth = now.getMonth() + 1 // 1-indexed

  // ── 1. Member counts ────────────────────────────────────────────────
  const [totalMembers, activeMembers] = await Promise.all([
    Member.countDocuments({ isDeleted: false }),
    Member.countDocuments({ status: 'Active', isDeleted: false }),
  ])

  // ── 2. Fund aggregates ──────────────────────────────────────────────
  // totalFundsCollected: sum of ALL paid contributions, INCLUDING the
  //   negative settlement-payout records (isSettlementPayout: true) that
  //   executeSettlement writes. This makes the total fund balance reflect
  //   settlements automatically (money going out reduces the total).
  // totalSettlementPayout: sum of all settlement net amounts (reference only)
  // activeLoanPrincipal: sum of original amount of active loans (money given out)
  // activeLoanAmount: sum of remaining balance on active loans (what's still owed)
  const [totalCollected, totalSettlementPayoutAgg, activeLoanPrincipalAgg, activeLoanRemainingAgg] = await Promise.all([
    Contribution.aggregate([
      { $match: { status: 'paid' } },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Settlement.aggregate([
      { $group: { _id: null, total: { $sum: '$netAmount' } } },
    ]),
    Loan.aggregate([
      { $match: { status: 'active' } },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Loan.aggregate([
      { $match: { status: 'active' } },
      { $group: { _id: null, total: { $sum: '$remaining' } } },
    ]),
  ])

  const totalFundsCollected = totalCollected[0]?.total || 0
  const totalSettlementPayout = totalSettlementPayoutAgg[0]?.total || 0
  const totalActiveLoanPrincipal = activeLoanPrincipalAgg[0]?.total || 0
  const totalActiveLoanAmount = activeLoanRemainingAgg[0]?.total || 0
  const totalActiveLoans = await Loan.countDocuments({ status: 'active' })
  // Available balance = total fund (already net of settlement payouts) - remaining active loans
  const availableBalance = totalFundsCollected - totalActiveLoanAmount

  // ── 3. Monthly collections (last 6 months) ──────────────────────────
  const sixMonthsAgo = new Date(currentYear, currentMonth - 6, 1)
  const monthlyData = await Contribution.aggregate([
    {
      $match: {
        status: 'paid',
        paymentDate: { $gte: sixMonthsAgo },
      },
    },
    {
      $group: {
        _id: '$month',
        amount: { $sum: '$amount' },
      },
    },
    { $sort: { _id: 1 } },
  ])

  // Build a complete 6-month series (fill missing months with 0)
  const monthLabels = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ]
  const monthlyMap = new Map(monthlyData.map((r) => [r._id, r.amount]))
  const monthlyCollections = []
  for (let i = 5; i >= 0; i--) {
    const m = currentMonth - i
    const y = m <= 0 ? currentYear - 1 : currentYear
    const mm = m <= 0 ? m + 12 : m
    const key = `${y}-${String(mm).padStart(2, '0')}`
    monthlyCollections.push({
      month: `${monthLabels[mm - 1]} ${String(y).slice(2)}`,
      amount: monthlyMap.get(key) || 0,
    })
  }

  // ── 4. Loan distribution (active loans by member) ───────────────────
  // Use the original loan `amount` (principal) for the pie chart so it
  // shows how much each member borrowed, not how much they still owe.
  const activeLoans = await Loan.find({ status: 'active' })
    .populate('memberId', 'name')
    .lean()

  const loanDistribution = activeLoans.map((l) => ({
    name: l.memberId?.name || 'Unknown',
    value: l.amount,
  }))

  // ── 5. Recent activity (last 10 events: contributions + repayments) ──
  const [recentContributions, recentRepayments] = await Promise.all([
    Contribution.find({ status: 'paid' })
      .populate('memberId', 'name')
      .sort({ paymentDate: -1 })
      .limit(10)
      .lean(),
    LoanRepayment.find({})
      .populate('memberId', 'name')
      .sort({ date: -1 })
      .limit(10)
      .lean(),
  ])

  const activity = [
    ...recentContributions.map((c) => ({
      type: 'contribution',
      title: 'Contribution received',
      description: `${c.memberId?.name || 'A member'} paid for ${c.month}`,
      amount: c.amount,
      date: c.paymentDate || c.createdAt,
    })),
    ...recentRepayments.map((r) => ({
      type: 'repayment',
      title: 'Loan repayment',
      description: `${r.memberId?.name || 'A member'} made a repayment`,
      amount: r.amount,
      date: r.date,
    })),
  ]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 10)

  return {
    totalMembers,
    activeMembers,
    totalFundsCollected,
    totalSettlementPayout,
    totalActiveLoans,
    totalActiveLoanPrincipal,
    totalActiveLoanAmount,
    availableBalance,
    monthlyCollections,
    loanDistribution,
    recentActivity: activity,
  }
}

module.exports = { getAdminDashboardStats }