// Generated by GitHub Copilot
const Loan = require('../models/Loan')
const Member = require('../models/Member')
const Contribution = require('../models/Contribution')
const LoanRepayment = require('../models/LoanRepayment')
const ApiError = require('../utils/ApiError')
const { logAudit } = require('../utils/auditLogger')
const { createNotification } = require('../utils/notificationHelper')

/**
 * Get available funds for issuing new loans.
 * @returns {Promise<number>}
 */
async function getAvailableFunds() {
  const [totalCollected, activeLoans] = await Promise.all([
    Contribution.aggregate([
      { $match: { status: 'paid' } },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Loan.aggregate([
      { $match: { status: 'active' } },
      { $group: { _id: null, total: { $sum: '$remaining' } } },
    ]),
  ])

  const collected = totalCollected[0]?.total || 0
  const loaned = activeLoans[0]?.total || 0
  return collected - loaned
}

/**
 * Create a new loan for a member.
 * @param {string} memberId
 * @param {object} data - { amount, issueDate, dueDate, notes }
 * @returns {Promise<object>}
 */
async function createLoan(memberId, data, meta = {}) {
  const member = await Member.findById(memberId)
  if (!member) throw new ApiError(404, 'Member not found')

  const amount = Number(data.amount)
  const issueDate = new Date(data.issueDate)
  const dueDate = data.dueDate ? new Date(data.dueDate) : null

  if (isNaN(amount) || amount <= 0) throw new ApiError(400, 'Invalid loan amount')
  if (isNaN(issueDate.getTime())) throw new ApiError(400, 'Invalid issue date')
  if (dueDate && isNaN(dueDate.getTime())) throw new ApiError(400, 'Invalid due date')
  if (dueDate && dueDate <= issueDate) throw new ApiError(400, 'Due date must be after issue date')

  // Check available funds
  const availableFunds = await getAvailableFunds()
  if (amount > availableFunds) {
    throw new ApiError(400, `Insufficient funds. Available: ${availableFunds}, Requested: ${amount}`)
  }

  const loan = await Loan.create({
    memberId,
    amount,
    remaining: amount,
    issueDate,
    dueDate,
    status: 'active',
    notes: data.notes?.trim() || '',
    repayments: [],
  })

  logAudit(meta, {
    action: 'LOAN_ISSUED',
    entity: 'Loan',
    entityId: loan._id,
    description: `Loan of ${amount} issued to ${member.name}`,
  })

  createNotification({
    recipientId: memberId,
    recipientRole: 'member',
    title: 'Loan issued',
    message: `A loan of ₹${amount.toLocaleString('en-IN')} has been issued to you.`,
    type: 'success',
    relatedEntity: 'Loan',
    relatedEntityId: loan._id,
  })

  return loan
}

/**
 * List loans with optional filters.
 * @param {{ status?: string, memberId?: string, page?: number, limit?: number }} query
 * @returns {Promise<{ loans: object[], pagination: object }>}
 */
async function listLoans({ status, memberId, page = 1, limit = 50 } = {}) {
  const filter = {}

  if (status) filter.status = status
  if (memberId) filter.memberId = memberId

  const currentPage = Math.max(1, Number(page) || 1)
  const perPage = Math.min(100, Math.max(1, Number(limit) || 50))
  const skip = (currentPage - 1) * perPage

  const [loans, total] = await Promise.all([
    Loan.find(filter)
      .populate('memberId', 'name email mobile')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(perPage),
    Loan.countDocuments(filter),
  ])

  return {
    loans: loans.map((loan) => ({
      id: loan._id,
      memberId: loan.memberId._id,
      memberName: loan.memberId.name,
      memberEmail: loan.memberId.email,
      memberMobile: loan.memberId.mobile,
      amount: loan.amount,
      remaining: loan.remaining,
      issueDate: loan.issueDate,
      dueDate: loan.dueDate,
      status: loan.status,
      notes: loan.notes,
      repayments: loan.repayments,
    })),
    pagination: {
      page: currentPage,
      limit: perPage,
      total,
      totalPages: Math.ceil(total / perPage) || 1,
    },
  }
}

/**
 * Get loan by ID.
 * @param {string} id
 * @returns {Promise<object>}
 */
async function getLoanById(id) {
  const loan = await Loan.findById(id).populate('memberId', 'name email mobile')
  if (!loan) throw new ApiError(404, 'Loan not found')

  return {
    id: loan._id,
    memberId: loan.memberId._id,
    memberName: loan.memberId.name,
    memberEmail: loan.memberId.email,
    memberMobile: loan.memberId.mobile,
    amount: loan.amount,
    remaining: loan.remaining,
    issueDate: loan.issueDate,
    dueDate: loan.dueDate,
    status: loan.status,
    notes: loan.notes,
    repayments: loan.repayments,
  }
}

/**
 * Get all loans for a specific member.
 * @param {string} memberId
 * @returns {Promise<Array>}
 */
async function getMemberLoans(memberId) {
  const loans = await Loan.find({ memberId }).sort({ createdAt: -1 })

  return loans.map((loan) => ({
    id: loan._id,
    amount: loan.amount,
    remaining: loan.remaining,
    issueDate: loan.issueDate,
    dueDate: loan.dueDate,
    status: loan.status,
    notes: loan.notes,
    repayments: loan.repayments,
  }))
}

/**
 * Update loan status.
 * @param {string} id
 * @param {string} status - 'active', 'paid', 'defaulted'
 * @returns {Promise<object>}
 */
async function updateLoanStatus(id, status, meta = {}) {
  const loan = await Loan.findById(id)
  if (!loan) throw new ApiError(404, 'Loan not found')

  const validStatuses = ['active', 'paid', 'defaulted']
  if (!validStatuses.includes(status)) throw new ApiError(400, 'Invalid status')

  loan.status = status
  await loan.save()

  logAudit(meta, {
    action: 'LOAN_STATUS_CHANGED',
    entity: 'Loan',
    entityId: loan._id,
    description: `Loan status changed to ${status}`,
  })

  createNotification({
    recipientId: loan.memberId,
    recipientRole: 'member',
    title: 'Loan status updated',
    message: `Your loan status has been updated to "${status}".`,
    type: status === 'defaulted' ? 'alert' : 'info',
    relatedEntity: 'Loan',
    relatedEntityId: loan._id,
  })

  return loan
}

/**
 * Close a loan (mark as paid with closedAt date).
 * @param {string} id
 * @returns {Promise<object>}
 */
async function closeLoan(id, meta = {}) {
  const loan = await Loan.findById(id)
  if (!loan) throw new ApiError(404, 'Loan not found')

  if (loan.remaining > 0) {
    throw new ApiError(400, 'Cannot close loan with remaining balance')
  }

  if (loan.status === 'paid') {
    throw new ApiError(400, 'Loan is already closed')
  }

  loan.status = 'paid'
  loan.closedAt = new Date()
  await loan.save()

  logAudit(meta, {
    action: 'LOAN_STATUS_CHANGED',
    entity: 'Loan',
    entityId: loan._id,
    description: 'Loan closed (fully paid)',
  })

  createNotification({
    recipientId: loan.memberId,
    recipientRole: 'member',
    title: 'Loan fully paid',
    message: 'Congratulations! Your loan has been fully paid and closed.',
    type: 'success',
    relatedEntity: 'Loan',
    relatedEntityId: loan._id,
  })

  return loan
}

/**
 * Record a loan repayment.
 * @param {string} id
 * @param {object} data - { amount, date, notes }
 * @returns {Promise<object>}
 */
async function repayLoan(id, data) {
  const loan = await Loan.findById(id)
  if (!loan) throw new ApiError(404, 'Loan not found')

  if (loan.status === 'paid') throw new ApiError(400, 'Loan is already paid')
  if (loan.status === 'defaulted') throw new ApiError(400, 'Cannot repay a defaulted loan')

  const repaymentAmount = Number(data.amount)
  if (isNaN(repaymentAmount) || repaymentAmount <= 0) {
    throw new ApiError(400, 'Invalid repayment amount')
  }
  if (repaymentAmount > loan.remaining) {
    throw new ApiError(400, `Repayment amount exceeds remaining balance (${loan.remaining})`)
  }

  const repaymentDate = new Date(data.date)
  if (isNaN(repaymentDate.getTime())) {
    throw new ApiError(400, 'Invalid repayment date')
  }

  // Add repayment record
  loan.repayments.push({
    amount: repaymentAmount,
    date: repaymentDate,
    notes: data.notes?.trim() || '',
  })

  // Update remaining balance
  loan.remaining -= repaymentAmount

  // If fully paid, update status
  if (loan.remaining === 0) {
    loan.status = 'paid'
  }

  await loan.save()

  try {
    await LoanRepayment.create({
      loanId: loan._id,
      memberId: loan.memberId,
      amount: repaymentAmount,
      date: repaymentDate,
      notes: data.notes?.trim() || '',
    })
  } catch (error) {
    loan.repayments.pop()
    loan.remaining += repaymentAmount
    if (loan.status === 'paid' && loan.remaining > 0) {
      loan.status = 'active'
    }
    await loan.save()
    throw new ApiError(500, 'Failed to record repayment. Please try again.')
  }

  return loan
}

module.exports = {
  createLoan,
  listLoans,
  getLoanById,
  getMemberLoans,
  updateLoanStatus,
  repayLoan,
  closeLoan,
  getAvailableFunds,
}
