// Generated by GitHub Copilot
const Contribution = require('../models/Contribution')
const ApiError = require('../utils/ApiError')

/**
 * Fetch contributions for a specific member with pagination and filters.
 * @param {string} memberId
 * @param {{ page?: number, limit?: number, month?: string, status?: string, sort?: string }} query
 * @returns {Promise<{ contributions: object[], pagination: object }>}
 */
async function getMemberContributions(memberId, { page = 1, limit = 10, month, status, sort = '-month' } = {}) {
  const filter = { memberId }

  if (month) filter.month = month
  if (status) filter.status = status

  const currentPage = Math.max(1, Number(page) || 1)
  const perPage = Math.min(100, Math.max(1, Number(limit) || 10))
  const skip = (currentPage - 1) * perPage

  const [docs, total] = await Promise.all([
    Contribution.find(filter)
      .sort(sort)
      .skip(skip)
      .limit(perPage),
    Contribution.countDocuments(filter),
  ])

  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

  const contributions = docs.map((c) => {
    const [year, monthNum] = c.month.split('-')
    const label = `${monthNames[parseInt(monthNum) - 1]} ${year}`
    return {
      id: c._id,
      month: c.month,
      label,
      amount: c.amount,
      status: c.status,
      paymentDate: c.paymentDate,
    }
  })

  return {
    contributions,
    pagination: {
      page: currentPage,
      limit: perPage,
      total,
      totalPages: Math.ceil(total / perPage) || 1,
    },
  }
}

/**
 * Calculate summary statistics for a member's contributions.
 * @param {string} memberId
 * @returns {Promise<object>} Summary statistics
 */
async function getMemberContributionSummary(memberId) {
  const contributions = await Contribution.find({ memberId })

  const totalContribution = contributions
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + Number(c.amount || 0), 0)

  const totalMonths = contributions.length
  const paidMonths = contributions.filter((c) => c.status === 'paid').length
  const unpaidMonths = contributions.filter((c) => c.status === 'unpaid').length

  const paidContributions = contributions.filter((c) => c.status === 'paid' && c.paymentDate)
  const latestPaymentDate = paidContributions.length > 0
    ? paidContributions.sort((a, b) => new Date(b.paymentDate) - new Date(a.paymentDate))[0].paymentDate
    : null

  const averageMonthlyContribution = paidMonths > 0 ? totalContribution / paidMonths : 0

  return {
    totalContribution,
    totalMonths,
    latestPaymentDate,
    paidMonths,
    unpaidMonths,
    averageMonthlyContribution: Math.round(averageMonthlyContribution),
  }
}

/**
 * Get a single contribution by ID for a specific member.
 * @param {string} memberId
 * @param {string} contributionId
 * @returns {Promise<object>} Contribution details
 */
async function getMemberContributionById(memberId, contributionId) {
  const contribution = await Contribution.findOne({ _id: contributionId, memberId })
  if (!contribution) {
    throw new ApiError(404, 'Contribution not found')
  }

  const [year, month] = contribution.month.split('-')
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const label = `${monthNames[parseInt(month) - 1]} ${year}`

  return {
    id: contribution._id,
    month: contribution.month,
    label,
    amount: contribution.amount,
    status: contribution.status,
    paymentDate: contribution.paymentDate,
    createdAt: contribution.createdAt,
    updatedAt: contribution.updatedAt,
  }
}

/**
 * Get contributions by year for a specific member.
 * @param {string} memberId
 * @param {number} year
 * @returns {Promise<object>} Year contributions with statistics
 */
async function getMemberContributionsByYear(memberId, year) {
  const contributions = await Contribution.find({
    memberId,
    month: { $regex: `^${year}-` }
  }).sort({ month: 1 })

  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

  const contributionsList = contributions.map((c) => {
    const [year, month] = c.month.split('-')
    const label = `${monthNames[parseInt(month) - 1]} ${year}`
    return {
      id: c._id,
      month: c.month,
      label,
      amount: c.amount,
      status: c.status,
      paymentDate: c.paymentDate,
    }
  })

  const totalContribution = contributions
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + Number(c.amount || 0), 0)

  const paidMonths = contributions.filter((c) => c.status === 'paid').length
  const unpaidMonths = contributions.filter((c) => c.status === 'unpaid').length
  const averageMonthlyContribution = paidMonths > 0 ? totalContribution / paidMonths : 0

  return {
    year,
    contributions: contributionsList,
    statistics: {
      totalContribution,
      totalMonths: contributions.length,
      paidMonths,
      unpaidMonths,
      averageMonthlyContribution: Math.round(averageMonthlyContribution),
    }
  }
}

module.exports = { 
  getMemberContributions, 
  getMemberContributionSummary,
  getMemberContributionById,
  getMemberContributionsByYear,
}
