// Generated by GitHub Copilot
const Loan = require('../models/Loan')
const ApiError = require('../utils/ApiError')

/**
 * Map a loan document into API response shape.
 * @param {import('mongoose').Document} loan
 * @returns {object}
 */
function toMemberLoan(loan) {
  return {
    id: loan._id,
    amount: loan.amount,
    remaining: loan.remaining,
    status: loan.status,
    issueDate: loan.issueDate,
    dueDate: loan.dueDate,
    memberName: loan.memberId?.name || null,
  }
}

/**
 * Fetch loans for a specific member with pagination and filters.
 * @param {string} memberId
 * @param {{ page?: number, limit?: number, status?: string }} query
 * @returns {Promise<{ loans: object[], pagination: object }>}
 */
async function getMemberLoans(memberId, { page = 1, limit = 10, status } = {}) {
  const filter = { memberId }

  if (status === 'closed') {
    filter.status = { $in: ['paid', 'defaulted'] }
  } else if (status) {
    filter.status = status
  }

  const currentPage = Math.max(1, Number(page) || 1)
  const perPage = Math.min(100, Math.max(1, Number(limit) || 10))
  const skip = (currentPage - 1) * perPage

  const [docs, total] = await Promise.all([
    Loan.find(filter)
      .populate('memberId', 'name')
      .sort({ issueDate: -1 })
      .skip(skip)
      .limit(perPage),
    Loan.countDocuments(filter),
  ])

  const loans = docs.map(toMemberLoan)

  return {
    loans,
    pagination: {
      page: currentPage,
      limit: perPage,
      total,
      totalPages: Math.ceil(total / perPage) || 1,
    },
  }
}

/**
 * Calculate summary statistics for a member's loans.
 * @param {string} memberId
 * @returns {Promise<object>} Summary statistics
 */
async function getMemberLoanSummary(memberId) {
  const loans = await Loan.find({ memberId })

  const totalBorrowed = loans.reduce((sum, loan) => sum + Number(loan.amount || 0), 0)
  const totalRemaining = loans.reduce((sum, loan) => sum + Number(loan.remaining || 0), 0)
  const activeLoans = loans.filter((l) => l.status === 'active').length
  const closedLoans = loans.filter(
    (l) => l.status === 'paid' || l.status === 'defaulted',
  ).length

  return {
    totalBorrowed,
    totalRemaining,
    activeLoans,
    closedLoans,
    totalLoans: loans.length,
  }
}

/**
 * Get one loan by id for the authenticated member.
 * @param {string} memberId
 * @param {string} loanId
 * @returns {Promise<object>} Loan details
 */
async function getMemberLoanById(memberId, loanId) {
  const loan = await Loan.findOne({ _id: loanId, memberId }).populate('memberId', 'name')
  if (!loan) {
    throw new ApiError(404, 'Loan not found')
  }

  return toMemberLoan(loan)
}

/**
 * Get loan passbook with payment history.
 * @param {string} memberId
 * @param {string} loanId
 * @returns {Promise<object>} Loan with payments
 */
async function getMemberLoanPassbook(memberId, loanId) {
  const loan = await Loan.findOne({ _id: loanId, memberId })
    .populate('memberId', 'name')
    .populate('repayments')
  if (!loan) {
    throw new ApiError(404, 'Loan not found')
  }

  const payments = loan.repayments || []
  const totalPaid = payments.reduce((sum, p) => sum + Number(p.amount || 0), 0)
  const remainingBalance = loan.amount - totalPaid

  const paymentsList = payments.map((p) => ({
    id: p._id,
    amount: p.amount,
    paymentDate: p.paymentDate || p.createdAt || new Date().toISOString(),
    method: p.method,
    reference: p.reference,
  }))

  return {
    loan: {
      id: loan._id,
      amount: loan.amount,
      remaining: remainingBalance,
      status: loan.status,
      issueDate: loan.issueDate,
      dueDate: loan.dueDate,
      closedAt: loan.closedAt,
    },
    payments: paymentsList,
    summary: {
      totalPaid,
      remainingBalance,
      totalPayments: payments.length,
      lastPaymentDate: payments.length > 0 ? payments[payments.length - 1].paymentDate : null,
    },
  }
}

module.exports = { 
  getMemberLoans, 
  getMemberLoanSummary,
  getMemberLoanById,
  getMemberLoanPassbook,
}
