// Generated by GitHub Copilot
const Member = require('../models/Member')
const Contribution = require('../models/Contribution')
const Loan = require('../models/Loan')
const ApiError = require('../utils/ApiError')

/**
 * Aggregate dashboard data for a member.
 * @param {string} memberId
 * @returns {Promise<object>} Dashboard data
 */
async function getMemberDashboard(memberId) {
  const member = await Member.findById(memberId)
  if (!member) {
    throw new ApiError(404, 'Member not found')
  }

  const [contributions, loans] = await Promise.all([
    Contribution.find({ memberId }).sort({ month: -1 }),
    Loan.find({ memberId, status: 'active' }).sort({ issueDate: -1 }),
  ])

  const totalContribution = contributions
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + Number(c.amount || 0), 0)

  const totalLoan = loans.reduce((sum, l) => sum + Number(l.amount || 0), 0)
  const remainingLoan = loans.reduce((sum, l) => sum + Number(l.remaining || 0), 0)

  const paidContributions = contributions.filter((c) => c.status === 'paid' && c.paymentDate)
  const lastContribution = paidContributions.length > 0
    ? paidContributions.sort((a, b) => new Date(b.paymentDate) - new Date(a.paymentDate))[0]
    : null

  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

  return {
    profile: {
      name: member.name,
      email: member.email,
      mobile: member.mobile,
      joiningDate: member.joiningDate,
      status: member.status,
    },
    totalContribution,
    totalLoan,
    remainingLoan,
    lastContribution: lastContribution
      ? {
          month: lastContribution.month,
          label: (() => {
            const [y, m] = lastContribution.month.split('-')
            return `${monthNames[parseInt(m) - 1]} ${y}`
          })(),
          amount: lastContribution.amount,
          status: lastContribution.status,
          paymentDate: lastContribution.paymentDate,
        }
      : null,
    activeLoans: loans.map((l) => ({
      id: l._id,
      amount: l.amount,
      remaining: l.remaining,
      issueDate: l.issueDate,
      dueDate: l.dueDate,
    })),
  }
}

module.exports = { getMemberDashboard }