// Generated by GitHub Copilot
const Member = require('../models/Member')
const Contribution = require('../models/Contribution')
const Loan = require('../models/Loan')
const ApiError = require('../utils/ApiError')

/**
 * Aggregate dashboard data for a member.
 * @param {string} memberId
 * @returns {Promise<object>} Dashboard data
 */
async function getMemberDashboard(memberId) {
  const member = await Member.findById(memberId)
  if (!member) {
    throw new ApiError(404, 'Member not found')
  }

  const [contributions, loans, fundAgg] = await Promise.all([
    Contribution.find({ memberId }).sort({ month: -1 }),
    Loan.find({ memberId, status: 'active' }).sort({ issueDate: -1 }),
    // System-wide fund aggregations
    Promise.all([
      Contribution.aggregate([
        { $match: { status: 'paid' } },
        { $group: { _id: null, total: { $sum: '$amount' } } },
      ]),
      Loan.aggregate([
        { $match: { status: 'active' } },
        { $group: { _id: null, total: { $sum: '$remaining' } } },
      ]),
      Loan.countDocuments({ status: 'active' }),
    ]),
  ])

  const totalContribution = contributions
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + Number(c.amount || 0), 0)

  const totalLoan = loans.reduce((sum, l) => sum + Number(l.amount || 0), 0)
  const remainingLoan = loans.reduce((sum, l) => sum + Number(l.remaining || 0), 0)

  const paidContributions = contributions.filter((c) => c.status === 'paid' && c.paymentDate)
  const lastContribution = paidContributions.length > 0
    ? paidContributions.sort((a, b) => new Date(b.paymentDate) - new Date(a.paymentDate))[0]
    : null

  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

  // Calculate next contribution month
  let nextContributionMonth = null
  if (contributions.length > 0) {
    const latestMonth = contributions[0].month // Already sorted by month descending
    const [year, month] = latestMonth.split('-').map(Number)
    const nextMonth = month === 12 ? 1 : month + 1
    const nextYear = month === 12 ? year + 1 : year
    nextContributionMonth = `${nextYear}-${String(nextMonth).padStart(2, '0')}`
  }

  // System-wide fund calculations
  const [totalCollectedAgg, activeLoanRemainingAgg, totalActiveLoans] = fundAgg
  const totalFundBalance = totalCollectedAgg[0]?.total || 0
  const totalActiveLoanRemaining = activeLoanRemainingAgg[0]?.total || 0
  const availableBalance = totalFundBalance - totalActiveLoanRemaining

  return {
    profile: {
      name: member.name,
      email: member.email,
      mobile: member.mobile,
      joiningDate: member.joiningDate,
      status: member.status,
    },
    totalContribution,
    totalLoan,
    remainingLoan,
    totalFundBalance,
    availableBalance,
    totalActiveLoans,
    lastContribution: lastContribution
      ? {
          month: lastContribution.month,
          label: (() => {
            const [y, m] = lastContribution.month.split('-')
            return `${monthNames[parseInt(m) - 1]} ${y}`
          })(),
          amount: lastContribution.amount,
          status: lastContribution.status,
          paymentDate: lastContribution.paymentDate,
        }
      : null,
    nextContributionMonth,
    activeLoans: loans.map((l) => ({
      id: l._id,
      amount: l.amount,
      remaining: l.remaining,
      issueDate: l.issueDate,
      dueDate: l.dueDate,
    })),
  }
}

/**
 * Get all active loans across all members (for the fund overview modal).
 * @returns {Promise<Array>} Active loans with member name populated
 */
async function getAllActiveLoans() {
  const loans = await Loan.find({ status: 'active' })
    .populate('memberId', 'name')
    .sort({ issueDate: -1 })
    .lean()

  return loans.map((l) => ({
    id: l._id,
    memberName: l.memberId?.name || 'Unknown',
    amount: l.amount,
    remaining: l.remaining,
    issueDate: l.issueDate,
    dueDate: l.dueDate,
  }))
}

module.exports = { getMemberDashboard, getAllActiveLoans }
