// Generated by GitHub Copilot
const Member = require('../models/Member')
const ApiError = require('../utils/ApiError')
const { toPublicUser } = require('./authService')

/**
 * Fetch the logged-in member's own profile.
 * @param {string} memberId
 * @returns {Promise<object>} Public member profile.
 */
async function getProfile(memberId) {
  const member = await Member.findOne({ _id: memberId, isDeleted: false })
  if (!member) throw new ApiError(404, 'Member not found')
  return toPublicUser(member, 'member')
}

/**
 * Change the logged-in member's password.
 * Verifies the current password before accepting the new one.
 * @param {string} memberId
 * @param {string} currentPassword
 * @param {string} newPassword
 * @returns {Promise<object>} Public member profile.
 */
async function changePassword(memberId, currentPassword, newPassword) {
  const member = await Member.findOne({ _id: memberId, isDeleted: false }).select(
    '+password',
  )
  if (!member) throw new ApiError(404, 'Member not found')

  // Verify current password
  const isMatch = await member.matchPassword(currentPassword)
  if (!isMatch) {
    throw new ApiError(400, 'Current password is incorrect')
  }

  // Ensure new password is different from current
  if (currentPassword === newPassword) {
    throw new ApiError(400, 'New password must be different from current password')
  }

  // Update password (pre-save hook will hash it)
  member.password = newPassword
  member.mustChangePassword = false
  await member.save()

  return toPublicUser(member, 'member')
}

module.exports = { getProfile, changePassword }