// Generated by GitHub Copilot
const LoanRequest = require('../models/LoanRequest')
const Admin = require('../models/Admin')
const Member = require('../models/Member')
const ApiError = require('../utils/ApiError')
const loanService = require('./loanService')
const { sortPendingQueue } = require('../utils/loanQueue')
const { createNotification } = require('../utils/notificationHelper')

/**
 * Submit a new loan request for the logged-in member.
 * @param {string} memberId
 * @param {{ amount, monthRequired, expectedReturn, purpose, notes }} body
 * @returns {Promise<object>} Created loan request
 */
async function applyForLoan(memberId, body) {
  const { amount, monthRequired, expectedReturn, purpose, notes } = body

  const loanRequest = await LoanRequest.create({
    memberId,
    amount,
    monthRequired,
    expectedReturn: expectedReturn || null,
    purpose,
    notes: notes || '',
    status: 'pending',
    queueOrder: Date.now(), // FIFO: newest goes to the back of the queue
  })

  const member = await Member.findById(memberId).select('name').lean()
  notifyAdmins(loanRequest, member?.name || 'A member')

  return toLoanRequest(loanRequest)
}

/** Notify all admins that a new loan request needs review. */
async function notifyAdmins(loanRequest, memberName) {
  const admins = await Admin.find({}).select('_id').lean()
  await Promise.all(
    admins.map((admin) =>
      createNotification({
        recipientId: admin._id,
        recipientRole: 'admin',
        title: 'New loan request',
        message: `${memberName} requested a loan of ₹${Number(loanRequest.amount).toLocaleString('en-IN')}.`,
        type: 'info',
        relatedEntity: 'LoanRequest',
        relatedEntityId: loanRequest._id,
      }),
    ),
  )
}

/**
 * Get all loan requests for the logged-in member, annotated with queue
 * position, funding ahead, and a waiting-for-funds flag on pending requests.
 * @param {string} memberId
 * @returns {Promise<object[]>} List of loan requests
 */
async function getMyLoanRequests(memberId) {
  const [myRequests, pending, availableFunds] = await Promise.all([
    LoanRequest.find({ memberId }).sort({ createdAt: -1 }).lean(),
    LoanRequest.find({ status: 'pending' }).lean(),
    loanService.getAvailableFunds(),
  ])

  const ordered = sortPendingQueue(pending)
  const queueTotal = ordered.length
  const queueInfo = new Map()
  let cumulative = 0
  ordered.forEach((req, index) => {
    queueInfo.set(String(req._id), { position: index + 1, fundingAhead: cumulative })
    cumulative += Number(req.amount || 0)
  })

  return myRequests.map((doc) => {
    const info = queueInfo.get(String(doc._id))
    return {
      ...toLoanRequest(doc),
      position: info?.position ?? null,
      fundingAhead: info ? info.fundingAhead : null,
      queueTotal: doc.status === 'pending' ? queueTotal : null,
      waiting: doc.status === 'pending' ? Number(doc.amount) > availableFunds : false,
    }
  })
}

/**
 * Available funds a member can see on the apply form.
 * @returns {Promise<number>}
 */
async function getAvailableFunds() {
  return loanService.getAvailableFunds()
}

/**
 * Withdraw a loan request (set status to 'withdrawn').
 * Only allowed if current status is 'pending' or 'approved'.
 * @param {string} memberId
 * @param {string} requestId
 * @returns {Promise<object>} Updated loan request
 */
async function withdrawLoanRequest(memberId, requestId) {
  const request = await LoanRequest.findOne({ _id: requestId, memberId })
  if (!request) {
    throw new ApiError(404, 'Loan request not found')
  }

  if (request.status !== 'pending' && request.status !== 'approved') {
    throw new ApiError(400, 'Only pending or approved requests can be withdrawn')
  }

  request.status = 'withdrawn'
  await request.save()

  return toLoanRequest(request)
}

/**
 * Map a loan request document to API response shape.
 */
function toLoanRequest(doc) {
  return {
    id: doc._id,
    amount: doc.amount,
    monthRequired: doc.monthRequired,
    expectedReturn: doc.expectedReturn,
    purpose: doc.purpose,
    notes: doc.notes,
    status: doc.status,
    createdAt: doc.createdAt,
  }
}

module.exports = { applyForLoan, getMyLoanRequests, getAvailableFunds, withdrawLoanRequest }
