// Generated by GitHub Copilot
const Notification = require('../models/Notification')
const ApiError = require('../utils/ApiError')

/**
 * Get paginated notifications for the authenticated user.
 *
 * @param {string} userId       - ObjectId of the recipient
 * @param {string} role         - 'admin' or 'member'
 * @param {number} [page=1]
 * @param {number} [limit=20]
 * @returns {Promise<{ notifications: object[], total: number, page: number, pages: number, unreadCount: number }>}
 */
async function getNotifications(userId, role, page = 1, limit = 20) {
  const safeLimit = Math.min(Number(limit) || 20, 100)
  const safePage = Math.max(Number(page) || 1, 1)
  const skip = (safePage - 1) * safeLimit

  const filter = { recipientId: userId, recipientRole: role }

  const [notifications, total, unreadCount] = await Promise.all([
    Notification.find(filter).sort({ createdAt: -1 }).skip(skip).limit(safeLimit).lean(),
    Notification.countDocuments(filter),
    Notification.countDocuments({ ...filter, isRead: false }),
  ])

  return {
    notifications,
    total,
    page: safePage,
    pages: Math.ceil(total / safeLimit),
    unreadCount,
  }
}

/**
 * Return only the count of unread notifications for the authenticated user.
 *
 * @param {string} userId
 * @param {string} role
 * @returns {Promise<{ unreadCount: number }>}
 */
async function getUnreadCount(userId, role) {
  const unreadCount = await Notification.countDocuments({
    recipientId: userId,
    recipientRole: role,
    isRead: false,
  })
  return { unreadCount }
}

/**
 * Mark a single notification as read. Ensures the notification belongs to the
 * requesting user to prevent unauthorized cross-user reads.
 *
 * @param {string} notificationId
 * @param {string} userId
 * @param {string} role
 * @returns {Promise<object>} Updated notification.
 */
async function markRead(notificationId, userId, role) {
  const notification = await Notification.findOne({
    _id: notificationId,
    recipientId: userId,
    recipientRole: role,
  })
  if (!notification) throw new ApiError(404, 'Notification not found')

  if (!notification.isRead) {
    notification.isRead = true
    notification.readAt = new Date()
    await notification.save()
  }

  return notification
}

/**
 * Mark every unread notification for the authenticated user as read.
 *
 * @param {string} userId
 * @param {string} role
 * @returns {Promise<{ updated: number }>} Count of documents updated.
 */
async function markAllRead(userId, role) {
  const result = await Notification.updateMany(
    { recipientId: userId, recipientRole: role, isRead: false },
    { $set: { isRead: true, readAt: new Date() } },
  )
  return { updated: result.modifiedCount }
}

module.exports = { getNotifications, getUnreadCount, markRead, markAllRead }
