// Generated by GitHub Copilot
const Contribution = require('../models/Contribution')
const Member = require('../models/Member')
const ContributionSetting = require('../models/ContributionSetting')
const ApiError = require('../utils/ApiError')

/**
 * Get overall contribution summary.
 * @returns {Promise<object>}
 */
async function getContributionSummary() {
  const [totalCollected, totalPending, totalMembers, activeMembers] = await Promise.all([
    Contribution.aggregate([
      { $match: { status: 'paid' } },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Contribution.aggregate([
      { $match: { status: 'unpaid' } },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Member.countDocuments({ isDeleted: false }),
    Member.countDocuments({ status: 'Active', isDeleted: false }),
  ])

  const collected = totalCollected[0]?.total || 0
  const pending = totalPending[0]?.total || 0
  const totalExpected = collected + pending

  return {
    totalMembers,
    activeMembers,
    totalExpected,
    totalCollected: collected,
    totalPending: pending,
    collectionRate: totalExpected > 0 ? ((collected / totalExpected) * 100).toFixed(1) : 0,
  }
}

/**
 * Get month-wise contribution breakdown.
 * @param {number} months - Number of months to look back (default: 12)
 * @returns {Promise<Array>}
 */
async function getMonthlyBreakdown(months = 12) {
  const now = new Date()
  const startDate = new Date(now.getFullYear(), now.getMonth() - months + 1, 1)

  const monthlyData = await Contribution.aggregate([
    {
      $match: {
        createdAt: { $gte: startDate },
      },
    },
    {
      $group: {
        _id: '$month',
        totalExpected: { $sum: '$amount' },
        totalCollected: {
          $sum: {
            $cond: [{ $eq: ['$status', 'paid'] }, '$amount', 0],
          },
        },
        totalPending: {
          $sum: {
            $cond: [{ $eq: ['$status', 'unpaid'] }, '$amount', 0],
          },
        },
        paidCount: {
          $sum: {
            $cond: [{ $eq: ['$status', 'paid'] }, 1, 0],
          },
        },
        unpaidCount: {
          $sum: {
            $cond: [{ $eq: ['$status', 'unpaid'] }, 1, 0],
          },
        },
      },
    },
    { $sort: { _id: 1 } },
  ])

  return monthlyData.map((item) => ({
    month: item._id,
    totalExpected: item.totalExpected,
    totalCollected: item.totalCollected,
    totalPending: item.totalPending,
    paidCount: item.paidCount,
    unpaidCount: item.unpaidCount,
    collectionRate: item.totalExpected > 0 ? ((item.totalCollected / item.totalExpected) * 100).toFixed(1) : 0,
  }))
}

/**
 * Get individual member's contribution history.
 * @param {string} memberId
 * @param {number} months - Number of months to look back (default: 12)
 * @returns {Promise<object>}
 */
async function getMemberContributionHistory(memberId, months = 12) {
  const now = new Date()
  const startDate = new Date(now.getFullYear(), now.getMonth() - months + 1, 1)

  const member = await Member.findById(memberId)
  if (!member) throw new ApiError(404, 'Member not found')

  const contributions = await Contribution.find({
    memberId,
    createdAt: { $gte: startDate },
  }).sort({ month: -1 })

  const totalPaid = contributions
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + c.amount, 0)

  const totalPending = contributions
    .filter((c) => c.status === 'unpaid')
    .reduce((sum, c) => sum + c.amount, 0)

  return {
    member: {
      id: member._id,
      name: member.name,
      email: member.email,
      mobile: member.mobile,
      status: member.status,
    },
    contributions: contributions.map((c) => ({
      id: c._id,
      month: c.month,
      amount: c.amount,
      status: c.status,
      paymentDate: c.paymentDate,
    })),
    summary: {
      totalContributions: contributions.length,
      totalPaid,
      totalPending,
    },
  }
}

/**
 * Get defaulters - members who haven't paid for current or last month.
 * @returns {Promise<Array>}
 */
async function getDefaulters() {
  const now = new Date()
  const currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const lastMonth = `${now.getFullYear()}-${String(now.getMonth()).padStart(2, '0')}`

  // Get all active members
  const activeMembers = await Member.find({ status: 'Active', isDeleted: false }).select('_id name email mobile')

  // Get contributions for current and last month
  const contributions = await Contribution.find({
    month: { $in: [currentMonth, lastMonth] },
    status: 'paid',
  }).select('memberId')

  const paidMemberIds = new Set(contributions.map((c) => c.memberId.toString()))

  // Find members who haven't paid in either month
  const defaulters = activeMembers.filter((m) => !paidMemberIds.has(m._id.toString()))

  return defaulters.map((m) => ({
    id: m._id,
    name: m.name,
    email: m.email,
    mobile: m.mobile,
    monthsPending: 2,
  }))
}

module.exports = {
  getContributionSummary,
  getMonthlyBreakdown,
  getMemberContributionHistory,
  getDefaulters,
}