// Generated by GitHub Copilot
const Contribution = require('../models/Contribution')
const Member = require('../models/Member')
const Loan = require('../models/Loan')
const LoanRepayment = require('../models/LoanRepayment')
const ContributionSetting = require('../models/ContributionSetting')
const ApiError = require('../utils/ApiError')

/**
 * Get overall contribution summary.
 * @returns {Promise<object>}
 */
async function getContributionSummary() {
  const [totalCollected, totalMembers, activeMembers, firstContribution] = await Promise.all([
    Contribution.aggregate([
      { $match: { status: 'paid' } },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Member.countDocuments({ isDeleted: false }),
    Member.countDocuments({ status: 'Active', isDeleted: false }),
    Contribution.findOne().sort({ createdAt: 1 }).select('createdAt').lean(),
  ])

  const collected = totalCollected[0]?.total || 0

  // Expected Contributions = activeMembers × monthlyAmount × monthsSinceStart
  const settings = await ContributionSetting.getSingleton()
  const monthlyAmount = settings.monthlyAmount

  let monthsSinceStart = 1
  if (firstContribution) {
    const startDate = new Date(firstContribution.createdAt)
    const now = new Date()
    monthsSinceStart = (now.getFullYear() - startDate.getFullYear()) * 12
      + (now.getMonth() - startDate.getMonth()) + 1
    if (monthsSinceStart < 1) monthsSinceStart = 1
  }

  const expectedContributions = activeMembers * monthlyAmount * monthsSinceStart
  const pending = expectedContributions - collected
  const collectionRate = expectedContributions > 0 ? ((collected / expectedContributions) * 100).toFixed(1) : 0

  return {
    totalMembers,
    activeMembers,
    expectedContributions,
    totalCollected: collected,
    totalPending: pending > 0 ? pending : 0,
    monthsSinceStart,
    monthlyAmount,
    collectionRate,
  }
}

/**
 * Get month-wise contribution breakdown.
 * @param {number} months - Number of months to look back (default: 12)
 * @returns {Promise<Array>}
 */
async function getMonthlyBreakdown(months = 12) {
  const now = new Date()
  const startDate = new Date(now.getFullYear(), now.getMonth() - months + 1, 1)

  const monthlyData = await Contribution.aggregate([
    {
      $match: {
        createdAt: { $gte: startDate },
      },
    },
    {
      $group: {
        _id: '$month',
        totalExpected: { $sum: '$amount' },
        totalCollected: {
          $sum: {
            $cond: [{ $eq: ['$status', 'paid'] }, '$amount', 0],
          },
        },
        totalPending: {
          $sum: {
            $cond: [{ $eq: ['$status', 'unpaid'] }, '$amount', 0],
          },
        },
        paidCount: {
          $sum: {
            $cond: [{ $eq: ['$status', 'paid'] }, 1, 0],
          },
        },
        unpaidCount: {
          $sum: {
            $cond: [{ $eq: ['$status', 'unpaid'] }, 1, 0],
          },
        },
      },
    },
    { $sort: { _id: 1 } },
  ])

  return monthlyData.map((item) => ({
    month: item._id,
    totalExpected: item.totalExpected,
    totalCollected: item.totalCollected,
    totalPending: item.totalPending,
    paidCount: item.paidCount,
    unpaidCount: item.unpaidCount,
    collectionRate: item.totalExpected > 0 ? ((item.totalCollected / item.totalExpected) * 100).toFixed(1) : 0,
  }))
}

/**
 * Get individual member's contribution history.
 * @param {string} memberId
 * @param {number} months - Number of months to look back (default: 12)
 * @returns {Promise<object>}
 */
async function getMemberContributionHistory(memberId, months = 12) {
  const now = new Date()
  const startDate = new Date(now.getFullYear(), now.getMonth() - months + 1, 1)

  const member = await Member.findById(memberId)
  if (!member) throw new ApiError(404, 'Member not found')

  const contributions = await Contribution.find({
    memberId,
    createdAt: { $gte: startDate },
  }).sort({ month: -1 })

  const totalPaid = contributions
    .filter((c) => c.status === 'paid')
    .reduce((sum, c) => sum + c.amount, 0)

  const totalPending = contributions
    .filter((c) => c.status === 'unpaid')
    .reduce((sum, c) => sum + c.amount, 0)

  return {
    member: {
      id: member._id,
      name: member.name,
      email: member.email,
      mobile: member.mobile,
      status: member.status,
    },
    contributions: contributions.map((c) => ({
      id: c._id,
      month: c.month,
      amount: c.amount,
      status: c.status,
      paymentDate: c.paymentDate,
    })),
    summary: {
      totalContributions: contributions.length,
      totalPaid,
      totalPending,
    },
  }
}

/**
 * Get defaulters - members who haven't paid for current or last month.
 * @returns {Promise<Array>}
 */
async function getDefaulters() {
  const now = new Date()
  const currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const lastMonth = `${now.getFullYear()}-${String(now.getMonth()).padStart(2, '0')}`

  // Get all active members
  const activeMembers = await Member.find({ status: 'Active', isDeleted: false }).select('_id name email mobile')

  // Get contributions for current and last month
  const contributions = await Contribution.find({
    month: { $in: [currentMonth, lastMonth] },
    status: 'paid',
  }).select('memberId')

  const paidMemberIds = new Set(contributions.map((c) => c.memberId.toString()))

  // Find members who haven't paid in either month
  const defaulters = activeMembers.filter((m) => !paidMemberIds.has(m._id.toString()))

  return defaulters.map((m) => ({
    id: m._id,
    name: m.name,
    email: m.email,
    mobile: m.mobile,
    monthsPending: 2,
  }))
}

/**
 * Get loan portfolio summary.
 * @returns {Promise<object>}
 */
async function getLoanPortfolioSummary() {
  const [totalLoansIssued, totalRepaid, activeLoanAgg] = await Promise.all([
    Loan.aggregate([
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    LoanRepayment.aggregate([
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]),
    Loan.aggregate([
      { $match: { status: 'active' } },
      { $group: { _id: null, total: { $sum: '$remaining' } } },
    ]),
  ])

  const issued = totalLoansIssued[0]?.total || 0
  const repaid = totalRepaid[0]?.total || 0
  const outstanding = activeLoanAgg[0]?.total || 0
  const recoveryRate = issued > 0 ? ((repaid / issued) * 100).toFixed(1) : 0

  return {
    totalLoansIssued: issued,
    totalRepaid: repaid,
    outstandingLoans: outstanding,
    totalRecovered: repaid,
    recoveryRate,
  }
}

module.exports = {
  getContributionSummary,
  getMonthlyBreakdown,
  getMemberContributionHistory,
  getDefaulters,
  getLoanPortfolioSummary,
}
