// Generated by GitHub Copilot
import Card from '../ui/Card.jsx'
import Badge from '../ui/Badge.jsx'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Summary card for a single loan: amounts, dates and repayment progress. */
export default function LoanSummaryCard({ loan }) {
  const paid = loan.amount - loan.remaining
  const progress = loan.amount > 0 ? Math.round((paid / loan.amount) * 100) : 0

  return (
    <Card className="p-5">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-slate-500">Loan #{loan.id}</p>
          <p className="mt-1 text-2xl font-bold text-slate-800">
            {formatCurrency(loan.amount)}
          </p>
        </div>
        <Badge>{loan.status}</Badge>
      </div>

      <dl className="mt-4 grid grid-cols-2 gap-4 text-sm">
        <div>
          <dt className="text-slate-400">Member</dt>
          <dd className="font-medium text-slate-700">{loan.memberName}</dd>
        </div>
        <div>
          <dt className="text-slate-400">Issued</dt>
          <dd className="font-medium text-slate-700">
            {formatDate(loan.issueDate)}
          </dd>
        </div>
        <div>
          <dt className="text-slate-400">Paid</dt>
          <dd className="font-medium text-green-600">{formatCurrency(paid)}</dd>
        </div>
        <div>
          <dt className="text-slate-400">Remaining</dt>
          <dd className="font-medium text-amber-600">
            {formatCurrency(loan.remaining)}
          </dd>
        </div>
      </dl>

      <div className="mt-4">
        <div className="mb-1 flex items-center justify-between text-xs text-slate-500">
          <span>Repayment progress</span>
          <span className="font-medium text-slate-700">{progress}%</span>
        </div>
        <div className="h-2 overflow-hidden rounded-full bg-slate-100">
          <div
            className="h-full rounded-full bg-brand-600 transition-all"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      {loan.notes ? (
        <p className="mt-4 rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-500">
          {loan.notes}
        </p>
      ) : null}
    </Card>
  )
}
