// Generated by GitHub Copilot
import { FiCheck } from 'react-icons/fi'
import EmptyState from '../ui/EmptyState.jsx'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Vertical timeline of repayment events for a loan passbook. */
export default function PaymentTimeline({ repayments }) {
  if (!repayments || repayments.length === 0) {
    return (
      <EmptyState
        title="No repayments yet"
        description="Repayments will appear here once recorded."
      />
    )
  }

  return (
    <ol className="relative space-y-6 pl-8">
      <span
        className="absolute left-3 top-2 h-[calc(100%-1rem)] w-px bg-slate-200"
        aria-hidden="true"
      />
      {repayments.map((r) => (
        <li key={r.id} className="relative">
          <span className="absolute -left-8 flex h-6 w-6 items-center justify-center rounded-full bg-green-100 text-green-600 ring-4 ring-white">
            <FiCheck className="h-3.5 w-3.5" />
          </span>
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-medium text-slate-800">
                Repayment received
              </p>
              <p className="text-xs text-slate-400">{formatDate(r.date)}</p>
            </div>
            <span className="text-sm font-semibold text-green-600">
              {formatCurrency(r.amount)}
            </span>
          </div>
        </li>
      ))}
    </ol>
  )
}
