// Generated by GitHub Copilot
import { FiArrowUpRight, FiArrowDownRight } from 'react-icons/fi'

/**
 * Dashboard statistic card showing a label, primary value, an icon and an
 * optional trend indicator.
 */
export default function StatCard({
  label,
  value,
  icon: Icon,
  tone = 'brand',
  trend,
  trendLabel,
}) {
  const tones = {
    brand: 'bg-brand-50 text-brand-600',
    green: 'bg-green-50 text-green-600',
    amber: 'bg-amber-50 text-amber-600',
    red: 'bg-red-50 text-red-600',
    slate: 'bg-slate-100 text-slate-600',
  }
  const isUp = trend != null && trend >= 0

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition-shadow hover:shadow-md">
      <div className="flex items-start justify-between">
        <p className="text-sm font-medium text-slate-500">{label}</p>
        {Icon ? (
          <span
            className={`flex h-10 w-10 items-center justify-center rounded-lg ${tones[tone]}`}
          >
            <Icon className="h-5 w-5" aria-hidden="true" />
          </span>
        ) : null}
      </div>
      <p className="mt-3 text-2xl font-bold text-slate-800">{value}</p>
      {trend != null ? (
        <p
          className={`mt-2 flex items-center gap-1 text-xs font-medium ${
            isUp ? 'text-green-600' : 'text-red-600'
          }`}
        >
          {isUp ? (
            <FiArrowUpRight className="h-3.5 w-3.5" />
          ) : (
            <FiArrowDownRight className="h-3.5 w-3.5" />
          )}
          {Math.abs(trend)}%
          <span className="font-normal text-slate-400">{trendLabel}</span>
        </p>
      ) : null}
    </div>
  )
}
