// Generated by GitHub Copilot
import { useAuthContext } from '../context/AuthContext.jsx'

/** Convenience hook exposing auth state and actions. */
export function useAuth() {
  return useAuthContext()
}
