// Generated by GitHub Copilot
import { useDataContext } from '../context/DataContext.jsx'

/** Convenience hook exposing the in-memory data store. */
export function useData() {
  return useDataContext()
}
