// Generated by GitHub Copilot
import { useMemo, useState } from 'react'

/**
 * Client-side pagination helper for the dummy-data tables.
 * Returns the current page slice plus navigation controls.
 */
export function usePagination(items, pageSize = 8) {
  const [page, setPage] = useState(1)

  const totalPages = Math.max(1, Math.ceil(items.length / pageSize))
  const safePage = Math.min(page, totalPages)

  const pageItems = useMemo(() => {
    const start = (safePage - 1) * pageSize
    return items.slice(start, start + pageSize)
  }, [items, safePage, pageSize])

  return {
    page: safePage,
    totalPages,
    pageItems,
    setPage,
    goTo: (p) => setPage(Math.min(Math.max(1, p), totalPages)),
    next: () => setPage((p) => Math.min(p + 1, totalPages)),
    prev: () => setPage((p) => Math.max(p - 1, 1)),
  }
}
