// Generated by GitHub Copilot
import { useSettingsContext } from '../context/SettingsContext.jsx'

/** Convenience hook exposing application settings. */
export function useSettings() {
  return useSettingsContext()
}
