// Generated by GitHub Copilot
import { useEffect, useState } from 'react'

/**
 * Simulates an async data fetch so the UI can demonstrate loading skeletons.
 * Resolves to `false` after the given delay. Purely cosmetic for the prototype.
 */
export function useSimulatedLoading(delay = 600) {
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), delay)
    return () => clearTimeout(timer)
  }, [delay])

  return loading
}
