// Generated by GitHub Copilot
import { NavLink } from 'react-router-dom'
import { NAV_CONFIG } from './navConfig.js'

/**
 * Bottom navigation shown on small screens for quick access to the primary
 * destinations. Hidden on large screens where the sidebar is available.
 */
export default function MobileNav({ role }) {
  const items = (NAV_CONFIG[role] ?? []).slice(0, 4)

  return (
    <nav className="fixed inset-x-0 bottom-0 z-20 flex border-t border-slate-200 bg-white/95 backdrop-blur lg:hidden">
      {items.map((item) => {
        const Icon = item.icon
        return (
          <NavLink
            key={item.to}
            to={item.to}
            className={({ isActive }) =>
              `flex flex-1 flex-col items-center gap-1 py-2.5 text-[11px] font-medium transition-colors ${
                isActive ? 'text-brand-700' : 'text-slate-500'
              }`
            }
          >
            <Icon className="h-5 w-5" aria-hidden="true" />
            {item.label}
          </NavLink>
        )
      })}
    </nav>
  )
}
