// Generated by GitHub Copilot
import {
  FiGrid,
  FiUsers,
  FiDollarSign,
  FiCreditCard,
  FiSettings,
  FiUser,
  FiBookOpen,
  FiBell,
  FiShield,
} from 'react-icons/fi'

/** Sidebar navigation definitions keyed by role. */
export const NAV_CONFIG = {
  admin: [
    { to: '/admin/dashboard', label: 'Dashboard', icon: FiGrid },
    { to: '/admin/members', label: 'Members', icon: FiUsers },
    { to: '/admin/contributions', label: 'Contributions', icon: FiDollarSign },
    { to: '/admin/loans', label: 'Loans', icon: FiCreditCard },
    { to: '/admin/passbook/:loanId', label: 'Loan Passbook', icon: FiBookOpen },
    { to: '/admin/settlements', label: 'Settlements', icon: FiDollarSign },
    { to: '/admin/settings', label: 'Settings', icon: FiSettings },
  ],
  member: [
    { to: '/member/dashboard', label: 'Dashboard', icon: FiGrid },
    { to: '/member/contributions', label: 'Contributions', icon: FiDollarSign },
    { to: '/member/loans', label: 'Loans', icon: FiCreditCard },
    { to: '/member/profile', label: 'Profile', icon: FiUser },
  ],
}
