// Generated by GitHub Copilot
import { NavLink } from 'react-router-dom'
import { FiX } from 'react-icons/fi'
import { RiBankFill } from 'react-icons/ri'
import { NAV_CONFIG } from './navConfig.js'

/**
 * Persistent left sidebar for dashboard pages. On mobile it slides in as a
 * drawer controlled by `open` / `onClose`; on desktop it is always visible.
 */
export default function Sidebar({ role, open, onClose }) {
  const items = NAV_CONFIG[role] ?? []

  return (
    <>
      {/* Mobile backdrop */}
      {open ? (
        <div
          className="fixed inset-0 z-30 bg-slate-900/50 lg:hidden"
          onClick={onClose}
          aria-hidden="true"
        />
      ) : null}

      <aside
        className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-slate-200 bg-white transition-transform duration-200 lg:static lg:translate-x-0 ${
          open ? 'translate-x-0' : '-translate-x-full'
        }`}
      >
        <div className="flex h-16 items-center justify-between gap-2 border-b border-slate-100 px-5">
          <div className="flex items-center gap-2">
            <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-brand-600 text-white">
              <RiBankFill className="h-5 w-5" />
            </span>
            <div className="leading-tight">
              <p className="text-sm font-bold text-slate-800">Maqasid Bank</p>
              <p className="text-[11px] text-slate-400">Bank Management</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close menu"
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 lg:hidden"
          >
            <FiX className="h-5 w-5" />
          </button>
        </div>

        <nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">
          {items.map((item) => {
            const Icon = item.icon
            return (
              <NavLink
                key={item.to}
                to={item.to}
                onClick={onClose}
                className={({ isActive }) =>
                  `flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
                    isActive
                      ? 'bg-brand-50 text-brand-700'
                      : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                  }`
                }
              >
                <Icon className="h-5 w-5" aria-hidden="true" />
                {item.label}
              </NavLink>
            )
          })}
        </nav>

        <div className="border-t border-slate-100 p-4">
          <p className="rounded-lg bg-slate-50 px-3 py-2 text-center text-xs text-slate-400">
            Maqasid Bank · v1.0
          </p>
        </div>
      </aside>
    </>
  )
}
