// Generated by GitHub Copilot
import { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiMenu, FiLogOut, FiChevronDown, FiBell } from 'react-icons/fi'
import { useAuth } from '../../hooks/useAuth.js'
import { getInitials } from '../../utils/format.js'
import { notificationApi } from '../../api/notificationApi.js'

/** Top navigation bar with the sidebar toggle and a user profile menu. */
export default function TopNavbar({ onMenuClick }) {
  const { user, logout } = useAuth()
  const navigate = useNavigate()
  const [menuOpen, setMenuOpen] = useState(false)
  const [unreadCount, setUnreadCount] = useState(0)
  const intervalRef = useRef(null)

  // Poll unread notification count every 30 s.
  useEffect(() => {
    const fetchCount = async () => {
      try {
        const data = await notificationApi.getUnreadCount()
        setUnreadCount(data.unreadCount ?? 0)
      } catch {
        // Silently ignore — badge simply stays at last known value.
      }
    }

    fetchCount()
    intervalRef.current = setInterval(fetchCount, 30_000)
    return () => clearInterval(intervalRef.current)
  }, [])

  const handleNotificationClick = () => {
    navigate(user?.role === 'admin' ? '/admin/notifications' : '/member/notifications')
  }

  const handleLogout = () => {
    logout()
    navigate('/login', { replace: true })
  }

  return (
    <header className="sticky top-0 z-20 flex h-16 items-center justify-between gap-4 border-b border-slate-200 bg-white/90 px-4 backdrop-blur lg:px-6">
      <button
        type="button"
        onClick={onMenuClick}
        aria-label="Open menu"
        className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 lg:hidden"
      >
        <FiMenu className="h-5 w-5" />
      </button>

      <div className="hidden flex-1 lg:block">
        <p className="text-sm text-slate-400">
          Welcome back,{' '}
          <span className="font-semibold text-slate-700">{user?.name}</span>
        </p>
      </div>

      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={handleNotificationClick}
          aria-label={`Notifications${unreadCount > 0 ? ` (${unreadCount} unread)` : ''}`}
          className="relative rounded-lg p-2 text-slate-500 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-brand-500"
        >
          <FiBell className="h-5 w-5" />
          {unreadCount > 0 && (
            <span
              aria-hidden="true"
              className="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-red-500 text-[10px] font-bold text-white"
            >
              {unreadCount > 9 ? '9+' : unreadCount}
            </span>
          )}
        </button>

        <div className="relative">
          <button
            type="button"
            onClick={() => setMenuOpen((v) => !v)}
            aria-haspopup="menu"
            aria-expanded={menuOpen}
            className="flex items-center gap-2 rounded-lg py-1.5 pl-1.5 pr-2 hover:bg-slate-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
          >
            <span
              className="flex h-9 w-9 items-center justify-center rounded-full text-sm font-semibold text-white"
              style={{ backgroundColor: user?.avatarColor || '#3563ff' }}
            >
              {getInitials(user?.name)}
            </span>
            <span className="hidden text-left sm:block">
              <span className="block text-sm font-medium text-slate-700">
                {user?.name}
              </span>
              <span className="block text-xs capitalize text-slate-400">
                {user?.role}
              </span>
            </span>
            <FiChevronDown className="hidden h-4 w-4 text-slate-400 sm:block" />
          </button>

          {menuOpen ? (
            <>
              <div
                className="fixed inset-0 z-10"
                onClick={() => setMenuOpen(false)}
                aria-hidden="true"
              />
              <div
                role="menu"
                className="absolute right-0 z-20 mt-2 w-56 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-lg"
              >
                <div className="border-b border-slate-100 px-4 py-3">
                  <p className="text-sm font-semibold text-slate-800">
                    {user?.name}
                  </p>
                  <p className="truncate text-xs text-slate-400">
                    {user?.email}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleLogout}
                  role="menuitem"
                  className="flex w-full items-center gap-2 px-4 py-2.5 text-left text-sm text-red-600 hover:bg-red-50"
                >
                  <FiLogOut className="h-4 w-4" />
                  Sign out
                </button>
              </div>
            </>
          ) : null}
        </div>
      </div>
    </header>
  )
}
