// Generated by GitHub Copilot
const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
const morgan = require('morgan')

const env = require('./config/env')
const authRoutes = require('./routes/authRoutes')
const memberRoutes = require('./routes/memberRoutes')
const contributionSettingRoutes = require('./routes/contributionSettingRoutes')
const contributionRoutes = require('./routes/contributionRoutes')
const reportRoutes = require('./routes/reportRoutes')
const loanRoutes = require('./routes/loanRoutes')
const loanRepaymentRoutes = require('./routes/loanRepaymentRoutes')
const dashboardRoutes = require('./routes/dashboardRoutes')
const auditRoutes = require('./routes/auditRoutes')
const memberProfileRoutes = require('./routes/memberProfileRoutes')
const memberContributionRoutes = require('./routes/memberContributionRoutes')
const memberLoanRoutes = require('./routes/memberLoanRoutes')
const memberDashboardRoutes = require('./routes/memberDashboardRoutes')
const settlementRoutes = require('./routes/settlementRoutes')
const { notFound, errorHandler } = require('./middleware/errorMiddleware')

const app = express()

// ---- Security & core middleware -----------------------------------------
app.use(helmet()) // sensible secure HTTP headers
app.use(
  cors({
    origin: env.clientUrl.split(',').map((o) => o.trim()),
    credentials: true,
  }),
)
app.use(express.json({ limit: '10kb' })) // bound body size to limit abuse
app.use(express.urlencoded({ extended: true }))
if (env.nodeEnv === 'development') app.use(morgan('dev'))

// ---- Health check --------------------------------------------------------
app.get('/api/health', (req, res) => {
  res.status(200).json({
    success: true,
    message: 'Maqasid Bank API is running',
    environment: env.nodeEnv,
    timestamp: new Date().toISOString(),
  })
})

// ---- Feature routes ------------------------------------------------------
app.use('/api/auth', authRoutes)
app.use('/api/members', memberRoutes)
app.use('/api/settings', contributionSettingRoutes)
app.use('/api/contributions', contributionRoutes)
app.use('/api/reports', reportRoutes)
app.use('/api/loans', loanRoutes)
app.use('/api/loan-repayments', loanRepaymentRoutes)
app.use('/api/dashboard', dashboardRoutes)
app.use('/api/audit-logs', auditRoutes)
app.use('/api/member', memberProfileRoutes)
app.use('/api/member/contributions', memberContributionRoutes)
app.use('/api/member/loans', memberLoanRoutes)
app.use('/api/member/dashboard', memberDashboardRoutes)
app.use('/api/settlements', settlementRoutes)

// ---- Error handling (must be last) --------------------------------------
app.use(notFound)
app.use(errorHandler)

module.exports = app
