// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const adminLoanRequestService = require('../services/adminLoanRequestService')
const { buildMeta } = require('../utils/buildMeta')

/**
 * @desc    Get all loan requests (excluding withdrawn)
 * @route   GET /api/admin/loan-requests
 * @access  Private (admin)
 */
const getAllLoanRequests = asyncHandler(async (req, res) => {
  const data = await adminLoanRequestService.getAllLoanRequests()
  res.status(200).json({
    success: true,
    data,
  })
})

/**
 * @desc    Approve a loan request
 * @route   PATCH /api/admin/loan-requests/:id/approve
 * @access  Private (admin)
 */
const approveLoanRequest = asyncHandler(async (req, res) => {
  const request = await adminLoanRequestService.approveLoanRequest(req.params.id, req.body, buildMeta(req))
  res.status(200).json({
    success: true,
    data: request,
  })
})

/**
 * @desc    Reject a loan request
 * @route   PATCH /api/admin/loan-requests/:id/reject
 * @access  Private (admin)
 */
const rejectLoanRequest = asyncHandler(async (req, res) => {
  const request = await adminLoanRequestService.rejectLoanRequest(req.params.id, req.body, buildMeta(req))
  res.status(200).json({
    success: true,
    data: request,
  })
})

/**
 * @desc    Reorder a pending loan request in the queue
 * @route   PATCH /api/admin/loan-requests/:id/reorder
 * @access  Private (admin)
 */
const reorderLoanRequest = asyncHandler(async (req, res) => {
  const data = await adminLoanRequestService.reorderQueue(req.params.id, req.body.direction)
  res.status(200).json({
    success: true,
    data,
  })
})

module.exports = { getAllLoanRequests, approveLoanRequest, rejectLoanRequest, reorderLoanRequest }