// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const auditService = require('../services/auditService')

/**
 * @desc    Get paginated audit logs with optional filters
 * @route   GET /api/audit-logs
 * @access  Private (admin)
 */
const getAuditLogs = asyncHandler(async (req, res) => {
  const { action, entity, performedByRole, startDate, endDate, page, limit } = req.query
  const result = await auditService.getAuditLogs({
    action,
    entity,
    performedByRole,
    startDate,
    endDate,
    page,
    limit,
  })
  res.status(200).json({
    success: true,
    data: result,
  })
})

module.exports = { getAuditLogs }
