// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const authService = require('../services/authService')

/**
 * @desc    Authenticate an admin and issue a JWT
 * @route   POST /api/auth/admin/login
 * @access  Public
 */
const adminLogin = asyncHandler(async (req, res) => {
  const { email, password } = req.body
  const meta = { ipAddress: req.ip, userAgent: req.headers['user-agent'] }
  const { token, user } = await authService.loginAdmin(email, password, meta)
  res.status(200).json({
    success: true,
    message: 'Admin logged in successfully',
    data: { token, user },
  })
})

/**
 * @desc    Authenticate a member and issue a JWT
 * @route   POST /api/auth/member/login
 * @access  Public
 */
const memberLogin = asyncHandler(async (req, res) => {
  const { identifier, password } = req.body
  const meta = { ipAddress: req.ip, userAgent: req.headers['user-agent'] }
  const { token, user } = await authService.loginMember(identifier, password, meta)
  res.status(200).json({
    success: true,
    message: 'Member logged in successfully',
    data: { token, user },
  })
})

/**
 * @desc    Return the currently authenticated principal
 * @route   GET /api/auth/me
 * @access  Private (admin or member)
 */
const getMe = asyncHandler(async (req, res) => {
  const user = authService.toPublicUser(req.user, req.user.role)
  res.status(200).json({
    success: true,
    data: { user },
  })
})

module.exports = { adminLogin, memberLogin, getMe }
