// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const contributionService = require('../services/contributionService')
const { buildMeta } = require('../utils/buildMeta')

/**
 * @desc    Generate monthly contributions for all active members
 * @route   POST /api/contributions/generate
 * @access  Private (admin)
 */
const generateContributions = asyncHandler(async (req, res) => {
  const { month } = req.body
  const result = await contributionService.generateMonthlyContributions(month, buildMeta(req))
  res.status(201).json({
    success: true,
    message: `Generated ${result.created} contributions (${result.skipped} skipped)`,
    data: result,
  })
})

/**
 * @desc    List contributions with filters
 * @route   GET /api/contributions
 * @access  Private (admin)
 */
const listContributions = asyncHandler(async (req, res) => {
  const result = await contributionService.listContributions(req.query)
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Update contribution payment status
 * @route   PATCH /api/contributions/:id/status
 * @access  Private (admin)
 */
const updateStatus = asyncHandler(async (req, res) => {
  const { status } = req.body
  const contribution = await contributionService.updateContributionStatus(req.params.id, status, buildMeta(req))
  res.status(200).json({
    success: true,
    message: `Contribution marked as ${status}`,
    data: { contribution },
  })
})

module.exports = {
  generateContributions,
  listContributions,
  updateStatus,
}