// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const contributionSettingService = require('../services/contributionSettingService')
const { buildMeta } = require('../utils/buildMeta')

/**
 * @desc    Get the current contribution settings
 * @route   GET /api/settings/contributions
 * @access  Private (admin)
 */
const getSettings = asyncHandler(async (req, res) => {
  const settings = await contributionSettingService.getCurrentSettings()
  res.status(200).json({
    success: true,
    data: settings,
  })
})

/**
 * @desc    Update the contribution settings
 * @route   PUT /api/settings/contributions
 * @access  Private (admin)
 */
const updateSettings = asyncHandler(async (req, res) => {
  const settings = await contributionSettingService.updateSettings(req.body, buildMeta(req))
  res.status(200).json({
    success: true,
    message: 'Contribution settings updated successfully',
    data: settings,
  })
})

module.exports = { getSettings, updateSettings }