// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const contributionSettingService = require('../services/contributionSettingService')
const settingsService = require('../services/settingsService')
const { buildMeta } = require('../utils/buildMeta')

/**
 * @desc    Get the current contribution settings
 * @route   GET /api/settings/contributions
 * @access  Private (admin)
 */
const getSettings = asyncHandler(async (req, res) => {
  const settings = await contributionSettingService.getCurrentSettings()
  res.status(200).json({
    success: true,
    data: settings,
  })
})

/**
 * @desc    Update the contribution settings
 * @route   PUT /api/settings/contributions
 * @access  Private (admin)
 */
const updateSettings = asyncHandler(async (req, res) => {
  const settings = await contributionSettingService.updateSettings(req.body, buildMeta(req))
  res.status(200).json({
    success: true,
    message: 'Contribution settings updated successfully',
    data: settings,
  })
})

/**
 * @desc    Cleanup database (delete all data except admins)
 * @route   POST /api/settings/cleanup
 * @access  Private (admin)
 */
const cleanupDatabase = asyncHandler(async (req, res) => {
  const result = await settingsService.cleanupDatabase(buildMeta(req))
  res.status(200).json({
    success: true,
    message: 'Database cleaned successfully. All data except admin accounts has been deleted.',
    data: result,
  })
})

module.exports = { getSettings, updateSettings, cleanupDatabase }
