// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const dashboardService = require('../services/dashboardService')

/**
 * @desc    Get admin dashboard statistics
 * @route   GET /api/dashboard/admin
 * @access  Private (admin)
 */
const getAdminDashboard = asyncHandler(async (req, res) => {
  const data = await dashboardService.getAdminDashboardStats()
  res.status(200).json({
    success: true,
    data,
  })
})

module.exports = { getAdminDashboard }