// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const loanService = require('../services/loanService')
const { buildMeta } = require('../utils/buildMeta')

/**
 * @desc    Create a new loan
 * @route   POST /api/loans
 * @access  Private (admin)
 */
const createLoan = asyncHandler(async (req, res) => {
  const loan = await loanService.createLoan(req.body.memberId, req.body, buildMeta(req))
  res.status(201).json({
    success: true,
    message: 'Loan created successfully',
    data: { loan },
  })
})

// Get available funds
const getAvailableFunds = asyncHandler(async (req, res) => {
  const available = await loanService.getAvailableFunds()
  res.status(200).json({
    success: true,
    data: { availableFunds: available },
  })
})

/**
 * @desc    List all loans with filters
 * @route   GET /api/loans
 * @access  Private (admin)
 */
const listLoans = asyncHandler(async (req, res) => {
  const result = await loanService.listLoans(req.query)
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Get loan by ID
 * @route   GET /api/loans/:id
 * @access  Private (admin)
 */
const getLoan = asyncHandler(async (req, res) => {
  const loan = await loanService.getLoanById(req.params.id)
  res.status(200).json({
    success: true,
    data: { loan },
  })
})

/**
 * @desc    Update loan status
 * @route   PATCH /api/loans/:id/status
 * @access  Private (admin)
 */
const updateStatus = asyncHandler(async (req, res) => {
  const { status } = req.body
  const loan = await loanService.updateLoanStatus(req.params.id, status, buildMeta(req))
  res.status(200).json({
    success: true,
    message: `Loan status updated to ${status}`,
    data: { loan },
  })
})

/**
 * @desc    Record a loan repayment
 * @route   POST /api/loans/:id/repay
 * @access  Private (admin)
 */
const repayLoan = asyncHandler(async (req, res) => {
  const loan = await loanService.repayLoan(req.params.id, req.body)
  res.status(200).json({
    success: true,
    message: 'Repayment recorded successfully',
    data: { loan },
  })
})

/**
 * @desc    Close a loan
 * @route   PATCH /api/loans/:id/close
 * @access  Private (admin)
 */
const closeLoan = asyncHandler(async (req, res) => {
  const loan = await loanService.closeLoan(req.params.id, buildMeta(req))
  res.status(200).json({
    success: true,
    message: 'Loan closed successfully',
    data: { loan },
  })
})

/**
 * @desc    Get member's loans
 * @route   GET /api/members/:memberId/loans
 * @access  Private (admin)
 */
const getMemberLoans = asyncHandler(async (req, res) => {
  const loans = await loanService.getMemberLoans(req.params.memberId)
  res.status(200).json({
    success: true,
    data: { loans },
  })
})

module.exports = {
  createLoan,
  listLoans,
  getLoan,
  updateStatus,
  repayLoan,
  closeLoan,
  getMemberLoans,
  getAvailableFunds,
}
