// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const memberLoanRequestService = require('../services/memberLoanRequestService')

/**
 * @desc    Submit a new loan request
 * @route   POST /api/member/loan-requests
 * @access  Private (member)
 */
const applyForLoan = asyncHandler(async (req, res) => {
  const loanRequest = await memberLoanRequestService.applyForLoan(req.user._id, req.body)
  res.status(201).json({
    success: true,
    data: loanRequest,
  })
})

/**
 * @desc    Get available funds for the apply form
 * @route   GET /api/member/loan-requests/available-funds
 * @access  Private (member)
 */
const getAvailableFunds = asyncHandler(async (req, res) => {
  const availableFunds = await memberLoanRequestService.getAvailableFunds()
  res.status(200).json({
    success: true,
    data: { availableFunds },
  })
})

/**
 * @desc    Get logged-in member's loan requests
 * @route   GET /api/member/loan-requests
 * @access  Private (member)
 */
const getMyLoanRequests = asyncHandler(async (req, res) => {
  const requests = await memberLoanRequestService.getMyLoanRequests(req.user._id)
  res.status(200).json({
    success: true,
    data: requests,
  })
})

/**
 * @desc    Withdraw a loan request
 * @route   PATCH /api/member/loan-requests/:id/withdraw
 * @access  Private (member)
 */
const withdrawLoanRequest = asyncHandler(async (req, res) => {
  const request = await memberLoanRequestService.withdrawLoanRequest(req.user._id, req.params.id)
  res.status(200).json({
    success: true,
    data: request,
  })
})

module.exports = { applyForLoan, getAvailableFunds, getMyLoanRequests, withdrawLoanRequest }
