// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const memberLoanService = require('../services/memberLoanService')

/**
 * @desc    Get logged-in member's loans with pagination and filters
 * @route   GET /api/member/loans
 * @access  Private (member)
 */
const getMyLoans = asyncHandler(async (req, res) => {
  const { page, limit, status } = req.query
  const result = await memberLoanService.getMemberLoans(req.user._id, {
    page,
    limit,
    status,
  })
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Get logged-in member's loan summary
 * @route   GET /api/member/loans/summary
 * @access  Private (member)
 */
const getMyLoanSummary = asyncHandler(async (req, res) => {
  const summary = await memberLoanService.getMemberLoanSummary(req.user._id)
  res.status(200).json({
    success: true,
    data: summary,
  })
})

/**
 * @desc    Get a single loan by ID for the logged-in member
 * @route   GET /api/member/loans/:loanId
 * @access  Private (member)
 */
const getMyLoanById = asyncHandler(async (req, res) => {
  const loan = await memberLoanService.getMemberLoanById(req.user._id, req.params.loanId)
  res.status(200).json({
    success: true,
    data: loan,
  })
})

/**
 * @desc    Get loan passbook with payment history
 * @route   GET /api/member/loans/:loanId/passbook
 * @access  Private (member)
 */
const getMyLoanPassbook = asyncHandler(async (req, res) => {
  const passbook = await memberLoanService.getMemberLoanPassbook(req.user._id, req.params.loanId)
  res.status(200).json({
    success: true,
    data: passbook,
  })
})

module.exports = { getMyLoans, getMyLoanSummary, getMyLoanById, getMyLoanPassbook }
