// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const memberProfileService = require('../services/memberProfileService')

/**
 * @desc    Get the logged-in member's profile
 * @route   GET /api/member/profile
 * @access  Private (member)
 */
const getProfile = asyncHandler(async (req, res) => {
  const member = await memberProfileService.getProfile(req.user._id)
  res.status(200).json({
    success: true,
    data: { member },
  })
})

/**
 * @desc    Change the logged-in member's password
 * @route   PUT /api/member/profile/password
 * @access  Private (member)
 */
const updatePassword = asyncHandler(async (req, res) => {
  const { currentPassword, newPassword } = req.body
  const member = await memberProfileService.changePassword(
    req.user._id,
    currentPassword,
    newPassword,
  )
  res.status(200).json({
    success: true,
    message: 'Password updated successfully',
    data: { member },
  })
})

module.exports = { getProfile, updatePassword }