// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const memberService = require('../services/memberService')
const { buildMeta } = require('../utils/buildMeta')

/**
 * @desc    Create a new member
 * @route   POST /api/members
 * @access  Private (admin)
 */
const createMember = asyncHandler(async (req, res) => {
  const member = await memberService.createMember(req.body, buildMeta(req))
  res.status(201).json({
    success: true,
    message: 'Member created successfully',
    data: { member },
  })
})

/**
 * @desc    List members with search, status filter and pagination
 * @route   GET /api/members
 * @access  Private (admin)
 */
const listMembers = asyncHandler(async (req, res) => {
  const result = await memberService.listMembers(req.query)
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Get a single member by id
 * @route   GET /api/members/:id
 * @access  Private (admin)
 */
const getMember = asyncHandler(async (req, res) => {
  const member = await memberService.getMemberById(req.params.id)
  res.status(200).json({
    success: true,
    data: { member },
  })
})

/**
 * @desc    Update a member
 * @route   PUT /api/members/:id
 * @access  Private (admin)
 */
const updateMember = asyncHandler(async (req, res) => {
  const member = await memberService.updateMember(req.params.id, req.body, buildMeta(req))
  res.status(200).json({
    success: true,
    message: 'Member updated successfully',
    data: { member },
  })
})

/**
 * @desc    Activate or deactivate a member
 * @route   PATCH /api/members/:id/status
 * @access  Private (admin)
 */
const updateMemberStatus = asyncHandler(async (req, res) => {
  const { status } = req.body
  const member = await memberService.setMemberStatus(req.params.id, status, buildMeta(req))
  res.status(200).json({
    success: true,
    message: `Member ${status === 'Active' ? 'activated' : 'deactivated'} successfully`,
    data: { member },
  })
})

module.exports = {
  createMember,
  listMembers,
  getMember,
  updateMember,
  updateMemberStatus,
}
