// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const memberDashboardService = require('../services/memberDashboardService')

/**
 * @desc    Get logged-in member's dashboard data
 * @route   GET /api/member/dashboard
 * @access  Private (member)
 */
const getMyDashboard = asyncHandler(async (req, res) => {
  const dashboard = await memberDashboardService.getMemberDashboard(req.user._id)
  res.status(200).json({
    success: true,
    data: dashboard,
  })
})

module.exports = { getMyDashboard }