// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const memberContributionService = require('../services/memberContributionService')
const ApiError = require('../utils/ApiError')

/**
 * @desc    Get logged-in member's contributions with pagination and filters
 * @route   GET /api/member/contributions
 * @access  Private (member)
 */
const getMyContributions = asyncHandler(async (req, res) => {
  const { page, limit, month, status, sort } = req.query
  const result = await memberContributionService.getMemberContributions(req.user._id, {
    page,
    limit,
    month,
    status,
    sort,
  })
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Get logged-in member's contribution summary
 * @route   GET /api/member/contributions/summary
 * @access  Private (member)
 */
const getMyContributionSummary = asyncHandler(async (req, res) => {
  const summary = await memberContributionService.getMemberContributionSummary(req.user._id)
  res.status(200).json({
    success: true,
    data: summary,
  })
})

/**
 * @desc    Get a single contribution by ID
 * @route   GET /api/member/contributions/:id
 * @access  Private (member)
 */
const getMyContributionById = asyncHandler(async (req, res) => {
  const contribution = await memberContributionService.getMemberContributionById(
    req.user._id,
    req.params.id
  )
  res.status(200).json({
    success: true,
    data: contribution,
  })
})

/**
 * @desc    Get contributions by year
 * @route   GET /api/member/contributions/year/:year
 * @access  Private (member)
 */
const getMyContributionsByYear = asyncHandler(async (req, res) => {
  const year = parseInt(req.params.year)
  if (isNaN(year) || year < 2000 || year > 2100) {
    throw new ApiError(400, 'Invalid year. Year must be between 2000 and 2100')
  }

  const result = await memberContributionService.getMemberContributionsByYear(req.user._id, year)
  res.status(200).json({
    success: true,
    data: result,
  })
})

module.exports = { 
  getMyContributions, 
  getMyContributionSummary,
  getMyContributionById,
  getMyContributionsByYear,
}
