// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const notificationService = require('../services/notificationService')

/**
 * @desc    Get paginated notifications for the authenticated user
 * @route   GET /api/notifications
 * @access  Private (admin + member)
 */
const getNotifications = asyncHandler(async (req, res) => {
  const { page, limit } = req.query
  const result = await notificationService.getNotifications(
    req.user._id,
    req.user.role,
    page,
    limit,
  )
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Get unread notification count for the authenticated user
 * @route   GET /api/notifications/unread-count
 * @access  Private (admin + member)
 */
const getUnreadCount = asyncHandler(async (req, res) => {
  const result = await notificationService.getUnreadCount(req.user._id, req.user.role)
  res.status(200).json({
    success: true,
    data: result,
  })
})

/**
 * @desc    Mark a single notification as read
 * @route   PATCH /api/notifications/:id/read
 * @access  Private (admin + member)
 */
const markRead = asyncHandler(async (req, res) => {
  const notification = await notificationService.markRead(
    req.params.id,
    req.user._id,
    req.user.role,
  )
  res.status(200).json({
    success: true,
    message: 'Notification marked as read',
    data: { notification },
  })
})

/**
 * @desc    Mark all notifications as read for the authenticated user
 * @route   PATCH /api/notifications/read-all
 * @access  Private (admin + member)
 */
const markAllRead = asyncHandler(async (req, res) => {
  const result = await notificationService.markAllRead(req.user._id, req.user.role)
  res.status(200).json({
    success: true,
    message: 'All notifications marked as read',
    data: result,
  })
})

module.exports = { getNotifications, getUnreadCount, markRead, markAllRead }
