// Generated by GitHub Copilot
const asyncHandler = require('../utils/asyncHandler')
const reportService = require('../services/reportService')

/**
 * @desc    Get overall contribution summary
 * @route   GET /api/reports/contributions/summary
 * @access  Private (admin)
 */
const getContributionSummary = asyncHandler(async (req, res) => {
  const summary = await reportService.getContributionSummary()
  res.status(200).json({
    success: true,
    data: summary,
  })
})

/**
 * @desc    Get monthly contribution breakdown
 * @route   GET /api/reports/contributions/monthly
 * @access  Private (admin)
 */
const getMonthlyBreakdown = asyncHandler(async (req, res) => {
  const months = parseInt(req.query.months) || 12
  const data = await reportService.getMonthlyBreakdown(months)
  res.status(200).json({
    success: true,
    data,
  })
})

/**
 * @desc    Get individual member's contribution history
 * @route   GET /api/reports/contributions/member/:id
 * @access  Private (admin)
 */
const getMemberHistory = asyncHandler(async (req, res) => {
  const history = await reportService.getMemberContributionHistory(req.params.id)
  res.status(200).json({
    success: true,
    data: history,
  })
})

/**
 * @desc    Get defaulters list
 * @route   GET /api/reports/contributions/defaulters
 * @access  Private (admin)
 */
const getDefaulters = asyncHandler(async (req, res) => {
  const defaulters = await reportService.getDefaulters()
  res.status(200).json({
    success: true,
    data: defaulters,
  })
})

/**
 * @desc    Get loan portfolio summary
 * @route   GET /api/reports/loans/summary
 * @access  Private (admin)
 */
const getLoanPortfolioSummary = asyncHandler(async (req, res) => {
  const summary = await reportService.getLoanPortfolioSummary()
  res.status(200).json({
    success: true,
    data: summary,
  })
})

module.exports = {
  getContributionSummary,
  getMonthlyBreakdown,
  getMemberHistory,
  getDefaulters,
  getLoanPortfolioSummary,
}
