// Generated by GitHub Copilot
const express = require('express')
const { getAuditLogs } = require('../controllers/auditController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const { auditLogQueryRules } = require('../middleware/auditValidator')

const router = express.Router()

// All audit log routes require an authenticated admin.
router.use(protect, authorize('admin'))

// GET /api/audit-logs
router.get('/', auditLogQueryRules, validate, getAuditLogs)

module.exports = router
