// Generated by GitHub Copilot
const express = require('express')
const { adminLogin, memberLogin, getMe } = require('../controllers/authController')
const { protect } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const {
  adminLoginRules,
  memberLoginRules,
} = require('../middleware/authValidator')

const router = express.Router()

// POST /api/auth/admin/login
router.post('/admin/login', adminLoginRules, validate, adminLogin)

// POST /api/auth/member/login
router.post('/member/login', memberLoginRules, validate, memberLogin)

// GET /api/auth/me  (any authenticated role)
router.get('/me', protect, getMe)

module.exports = router
