// Generated by GitHub Copilot
const express = require('express')
const {
  generateContributions,
  listContributions,
  updateStatus,
} = require('../controllers/contributionController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const {
  generateRules,
  listQueryRules,
  statusRules,
} = require('../middleware/contributionValidator')

const router = express.Router()

// Every contribution route requires an authenticated admin.
router.use(protect, authorize('admin'))

// POST /api/contributions/generate
router.post('/generate', generateRules, validate, generateContributions)

// GET /api/contributions
router.get('/', listQueryRules, validate, listContributions)

// PATCH /api/contributions/:id/status
router.patch('/:id/status', statusRules, validate, updateStatus)

module.exports = router