// Generated by GitHub Copilot
const express = require('express')
const { getAdminDashboard } = require('../controllers/dashboardController')
const { protect, authorize } = require('../middleware/authMiddleware')

const router = express.Router()

// GET /api/dashboard/admin — admin-only
router.get('/admin', protect, authorize('admin'), getAdminDashboard)

module.exports = router