// Generated by GitHub Copilot
const express = require('express')
const {
  createLoan,
  listLoans,
  getLoan,
  updateStatus,
  repayLoan,
  closeLoan,
  getMemberLoans,
  getAvailableFunds,
} = require('../controllers/loanController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const {
  createLoanRules,
  loanQueryRules,
  statusRules,
  repayRules,
} = require('../middleware/loanValidator')

const router = express.Router()

// Every loan route requires an authenticated admin.
router.use(protect, authorize('admin'))

// POST /api/loans
router.post('/', createLoanRules, validate, createLoan)

// GET /api/loans
router.get('/', loanQueryRules, validate, listLoans)

// GET /api/loans/available-funds (must be before /:id)
router.get('/available-funds', getAvailableFunds)

// GET /api/loans/:id
router.get('/:id', getLoan)

// PATCH /api/loans/:id/status
router.patch('/:id/status', statusRules, validate, updateStatus)

// PATCH /api/loans/:id/close
router.patch('/:id/close', closeLoan)

// POST /api/loans/:id/repay
router.post('/:id/repay', repayRules, validate, repayLoan)

// GET /api/members/:memberId/loans
router.get('/member/:memberId/loans', getMemberLoans)

module.exports = router