// Generated by GitHub Copilot
const express = require('express')
const {
  createMember,
  listMembers,
  getMember,
  updateMember,
  updateMemberStatus,
  deleteMember,
} = require('../controllers/memberController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const {
  createMemberRules,
  updateMemberRules,
  statusRules,
  idParamRules,
  listQueryRules,
} = require('../middleware/memberValidator')

const router = express.Router()

// Every member-management route requires an authenticated admin.
router.use(protect, authorize('admin'))

// POST /api/members
router.post('/', createMemberRules, validate, createMember)

// GET /api/members
router.get('/', listQueryRules, validate, listMembers)

// GET /api/members/:id
router.get('/:id', idParamRules, validate, getMember)

// PUT /api/members/:id
router.put('/:id', idParamRules, updateMemberRules, validate, updateMember)

// PATCH /api/members/:id/status
router.patch('/:id/status', idParamRules, statusRules, validate, updateMemberStatus)

// DELETE /api/members/:id
router.delete('/:id', idParamRules, validate, deleteMember)

module.exports = router
