// Generated by GitHub Copilot
const express = require('express')
const {
  applyForLoan,
  getAvailableFunds,
  getMyLoanRequests,
  withdrawLoanRequest,
} = require('../controllers/memberLoanRequestController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const { applyRules, idParamRules } = require('../middleware/loanRequestValidator')

const router = express.Router()

// All member loan request routes require an authenticated member.
router.use(protect, authorize('member'))

// GET /api/member/loan-requests/available-funds — funds visible on the apply form
router.get('/available-funds', getAvailableFunds)

// POST /api/member/loan-requests — submit a new loan request
router.post('/', applyRules, validate, applyForLoan)

// GET /api/member/loan-requests — list my loan requests
router.get('/', getMyLoanRequests)

// PATCH /api/member/loan-requests/:id/withdraw — withdraw a request
router.patch('/:id/withdraw', idParamRules, validate, withdrawLoanRequest)

module.exports = router
