// Generated by GitHub Copilot
const express = require('express')
const {
  getProfile,
  updatePassword,
} = require('../controllers/memberProfileController')
const { protect, authorize } = require('../middleware/authMiddleware')
const { mustChangePwd } = require('../middleware/mustChangePwd')
const validate = require('../middleware/validate')
const { changePasswordRules } = require('../middleware/memberProfileValidator')

const router = express.Router()

// All member profile routes require an authenticated member.
router.use(protect, authorize('member'))

// Password change must be accessible even when mustChangePassword is true.
router.put('/profile/password', changePasswordRules, validate, updatePassword)

// All other profile routes require the member to have changed their initial password.
router.use(mustChangePwd)

// GET /api/member/profile
router.get('/profile', getProfile)

module.exports = router