// Generated by GitHub Copilot
const express = require('express')
const {
  getMyContributions,
  getMyContributionSummary,
  getMyContributionById,
  getMyContributionsByYear,
} = require('../controllers/memberContributionController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const { 
  contributionQueryRules,
  contributionIdParamRules,
  yearParamRules,
} = require('../middleware/memberContributionValidator')

const router = express.Router()

// All member contribution routes require an authenticated member.
router.use(protect, authorize('member'))

// GET /api/member/contributions
router.get('/', contributionQueryRules, validate, getMyContributions)

// GET /api/member/contributions/summary
router.get('/summary', getMyContributionSummary)

// GET /api/member/contributions/:id
router.get('/:id', contributionIdParamRules, validate, getMyContributionById)

// GET /api/member/contributions/year/:year
router.get('/year/:year', yearParamRules, validate, getMyContributionsByYear)

module.exports = router
