// Generated by GitHub Copilot
const express = require('express')
const { getMyDashboard } = require('../controllers/memberDashboardController')
const { protect, authorize } = require('../middleware/authMiddleware')

const router = express.Router()

// All member dashboard routes require an authenticated member.
router.use(protect, authorize('member'))

// GET /api/member/dashboard
router.get('/', getMyDashboard)

module.exports = router