// Generated by GitHub Copilot
const express = require('express')
const {
  getMyLoans,
  getMyLoanSummary,
  getMyLoanById,
  getMyLoanPassbook,
} = require('../controllers/memberLoanController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const {
  loanQueryRules,
  loanIdParamRules,
} = require('../middleware/memberLoanValidator')

const router = express.Router()

// All member loan routes require an authenticated member.
router.use(protect, authorize('member'))

// GET /api/member/loans
router.get('/', loanQueryRules, validate, getMyLoans)

// GET /api/member/loans/summary
router.get('/summary', getMyLoanSummary)

// GET /api/member/loans/:loanId
router.get('/:loanId', loanIdParamRules, validate, getMyLoanById)

// GET /api/member/loans/:loanId/passbook
router.get('/:loanId/passbook', loanIdParamRules, validate, getMyLoanPassbook)

module.exports = router
