// Generated by GitHub Copilot
const express = require('express')
const {
  getNotifications,
  getUnreadCount,
  markRead,
  markAllRead,
} = require('../controllers/notificationController')
const { protect } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const {
  notificationQueryRules,
  notificationIdRules,
} = require('../middleware/notificationValidator')

const router = express.Router()

// All notification routes require an authenticated user (admin or member).
router.use(protect)

// GET /api/notifications
router.get('/', notificationQueryRules, validate, getNotifications)

// GET /api/notifications/unread-count
// Must be declared before /:id/read to avoid 'unread-count' being treated as an id param.
router.get('/unread-count', getUnreadCount)

// PATCH /api/notifications/read-all
router.patch('/read-all', markAllRead)

// PATCH /api/notifications/:id/read
router.patch('/:id/read', notificationIdRules, validate, markRead)

module.exports = router
