// Generated by GitHub Copilot
const express = require('express')
const {
  getContributionSummary,
  getMonthlyBreakdown,
  getMemberHistory,
  getDefaulters,
  getLoanPortfolioSummary,
} = require('../controllers/reportController')
const { protect, authorize } = require('../middleware/authMiddleware')
const validate = require('../middleware/validate')
const { reportQueryRules } = require('../middleware/reportValidator')

const router = express.Router()

// Every report route requires an authenticated admin.
router.use(protect, authorize('admin'))

// GET /api/reports/contributions/summary
router.get('/contributions/summary', getContributionSummary)

// GET /api/reports/contributions/monthly
router.get('/contributions/monthly', reportQueryRules, validate, getMonthlyBreakdown)

// GET /api/reports/contributions/member/:id
router.get('/contributions/member/:id', getMemberHistory)

// GET /api/reports/contributions/defaulters
router.get('/contributions/defaulters', getDefaulters)

// GET /api/reports/loans/summary
router.get('/loans/summary', getLoanPortfolioSummary)

module.exports = router
