// Generated by GitHub Copilot
import { Link } from 'react-router-dom'
import { FiAlertCircle } from 'react-icons/fi'
import Button from '../components/ui/Button.jsx'

/** Fallback page for unknown routes. */
export default function NotFound() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-slate-50 px-6 text-center">
      <span className="flex h-14 w-14 items-center justify-center rounded-full bg-amber-100 text-amber-600">
        <FiAlertCircle className="h-7 w-7" />
      </span>
      <div>
        <h1 className="text-3xl font-bold text-slate-800">404</h1>
        <p className="mt-1 text-slate-500">
          The page you are looking for does not exist.
        </p>
      </div>
      <Link to="/login">
        <Button>Back to login</Button>
      </Link>
    </div>
  )
}
