// Generated by GitHub Copilot

/**
 * Operational error carrying an HTTP status code. Thrown throughout the app
 * and translated into a consistent JSON response by the error middleware.
 */
class ApiError extends Error {
  /**
   * @param {number} statusCode - HTTP status code.
   * @param {string} message - Human-readable error message.
   * @param {Array} [errors] - Optional list of field-level validation errors.
   */
  constructor(statusCode, message, errors = []) {
    super(message)
    this.statusCode = statusCode
    this.errors = errors
    this.isOperational = true
    Error.captureStackTrace(this, this.constructor)
  }
}

module.exports = ApiError
