// Generated by GitHub Copilot
const AuditLog = require('../models/AuditLog')

/**
 * Fire-and-forget audit log helper.
 *
 * @param {object} meta - Caller identity extracted from req.user in the controller.
 * @param {string|null} meta.performedBy       - ObjectId of the acting user (null for failed logins)
 * @param {string|null} meta.performedByRole   - 'admin' or 'member'
 * @param {string|null} meta.performedByName   - Denormalized display name
 * @param {string|null} meta.ipAddress         - req.ip
 * @param {string|null} meta.userAgent         - req.headers['user-agent']
 * @param {object} payload - Details about the action being logged.
 * @param {string} payload.action              - One of the AuditLog action enum values
 * @param {string} payload.entity              - One of the AuditLog entity enum values
 * @param {string|null} [payload.entityId]     - The affected document's ObjectId
 * @param {string} [payload.description]       - Human-readable description
 * @param {object|null} [payload.metadata]     - Extra context (e.g. changed fields)
 *
 * NOTE: This function never throws. Audit failures are caught silently so they
 * never disrupt the main request/response cycle.
 */
const logAudit = async (meta = {}, payload = {}) => {
  try {
    const {
      performedBy = null,
      performedByRole = null,
      performedByName = null,
      ipAddress = null,
      userAgent = null,
    } = meta

    const {
      action,
      entity,
      entityId = null,
      description = '',
      metadata = null,
    } = payload

    await AuditLog.create({
      action,
      entity,
      entityId,
      performedBy,
      performedByRole,
      performedByName,
      description,
      ipAddress,
      userAgent,
      metadata,
    })
  } catch (err) {
    if (process.env.NODE_ENV !== 'production') {
      console.error('[auditLogger] Failed to write audit log:', err.message)
    }
  }
}

module.exports = { logAudit }
