// Generated by GitHub Copilot
/**
 * Extract audit identity meta from an authenticated Express request.
 * Call this only after `protect` middleware has populated req.user.
 * For unauthenticated routes (login), pass only ipAddress + userAgent and
 * let the service populate performedBy/Name/Role from its return value.
 *
 * @param {import('express').Request} req
 * @returns {{ performedBy: string|null, performedByRole: string|null, performedByName: string|null, ipAddress: string|null, userAgent: string|null }}
 */
function buildMeta(req) {
  return {
    performedBy: req.user?._id || null,
    performedByRole: req.user?.role || null,
    performedByName: req.user?.name || null,
    ipAddress: req.ip || null,
    userAgent: req.headers?.['user-agent'] || null,
  }
}

module.exports = { buildMeta }
