// Generated by GitHub Copilot
const jwt = require('jsonwebtoken')
const env = require('../config/env')

/**
 * Sign a JWT for an authenticated principal.
 * @param {string} id - Mongo document id of the user.
 * @param {'admin'|'member'} role - Role used for authorization checks.
 * @returns {string} Signed JWT.
 */
function generateToken(id, role) {
  return jwt.sign({ id, role }, env.jwtSecret, {
    expiresIn: env.jwtExpiresIn,
  })
}

module.exports = generateToken
