// Generated by GitHub Copilot

/** Effective queue priority: explicit queueOrder, else creation time (FIFO). */
function effectiveOrder(req) {
  return req.queueOrder != null ? req.queueOrder : new Date(req.createdAt).getTime()
}

/** Return a copy of pending requests sorted by queue priority (earliest first). */
function sortPendingQueue(docs) {
  return [...docs].sort(
    (a, b) =>
      effectiveOrder(a) - effectiveOrder(b) ||
      new Date(a.createdAt) - new Date(b.createdAt),
  )
}

module.exports = { effectiveOrder, sortPendingQueue }
