// Generated by GitHub Copilot
const Notification = require('../models/Notification')

/**
 * Fire-and-forget notification creation helper.
 *
 * @param {object} options
 * @param {string}      options.recipientId        - ObjectId of the admin or member to notify
 * @param {string}      options.recipientRole       - 'admin' or 'member'
 * @param {string}      options.title               - Short notification title
 * @param {string}      options.message             - Full notification message
 * @param {string}      [options.type='info']       - 'info' | 'success' | 'warning' | 'alert'
 * @param {string|null} [options.relatedEntity]     - Entity type (e.g. 'Loan')
 * @param {string|null} [options.relatedEntityId]   - ObjectId of the related document
 *
 * NOTE: This function never throws. Notification failures are caught silently so
 * they never disrupt the main request/response cycle.
 */
const createNotification = async ({
  recipientId,
  recipientRole,
  title,
  message,
  type = 'info',
  relatedEntity = null,
  relatedEntityId = null,
} = {}) => {
  try {
    await Notification.create({
      recipientId,
      recipientRole,
      title,
      message,
      type,
      relatedEntity,
      relatedEntityId,
    })
  } catch (err) {
    if (process.env.NODE_ENV !== 'production') {
      console.error('[notificationHelper] Failed to create notification:', err.message)
    }
  }
}

module.exports = { createNotification }
