// Generated by GitHub Copilot
// Seed script — creates one default admin and two sample members.
// Usage: npm run seed
/* eslint-disable no-console */
const mongoose = require('mongoose')
const connectDB = require('../config/db')
const Admin = require('../models/Admin')
const Member = require('../models/Member')
const Loan = require('../models/Loan')
const LoanRepayment = require('../models/LoanRepayment')

const adminSeed = {
  name: 'Maqasid Admin',
  email: 'admin@maqasidbank.local',
  password: 'Admin@123',
}

const membersSeed = [
  {
    name: 'Rahul Sharma',
    mobile: '9876543210',
    email: 'rahul.sharma@example.com',
    password: 'Member@123',
    joiningDate: new Date('2023-01-15'),
    status: 'Active',
  },
  {
    name: 'Priya Patel',
    mobile: '9823456781',
    email: 'priya.patel@example.com',
    password: 'Member@123',
    joiningDate: new Date('2023-02-01'),
    status: 'Active',
  },
]

async function seed() {
  await connectDB()

  try {
    await Promise.all([
      Admin.deleteMany({}),
      Member.deleteMany({}),
      Loan.deleteMany({}),
      LoanRepayment.deleteMany({}),
    ])

    const admin = await Admin.create(adminSeed)
    await Member.create(membersSeed)

    console.log('✅ Seed complete')
    console.log('----------------------------------------')
    console.log('Admin login:')
    console.log(`  email:    ${admin.email}`)
    console.log(`  password: ${adminSeed.password}`)
    console.log('----------------------------------------')
    console.log('Member logins (mobile or email):')
    membersSeed.forEach((m, i) => {
      console.log(`  ${i + 1}. ${m.name}`)
      console.log(`     mobile:   ${m.mobile}`)
      console.log(`     email:    ${m.email}`)
      console.log(`     password: Member@123`)
    })
    console.log('----------------------------------------')
  } catch (error) {
    console.error('❌ Seed failed:', error.message)
    process.exitCode = 1
  } finally {
    await mongoose.disconnect()
  }
}

seed()
