// Generated by GitHub Copilot
import { apiRequest } from './client.js'

/** Audit log API — admin only. */
export const auditApi = {
  /**
   * Fetch paginated audit logs with optional filters.
   * @param {{ action?: string, entity?: string, performedByRole?: string, startDate?: string, endDate?: string, page?: number, limit?: number }} params
   */
  getLogs: (params = {}) => {
    const qs = new URLSearchParams()
    Object.entries(params).forEach(([k, v]) => {
      if (v != null && v !== '') qs.append(k, v)
    })
    const query = qs.toString()
    return apiRequest(`/audit-logs${query ? `?${query}` : ''}`).then((r) => r.data)
  },
}
