// Generated by GitHub Copilot
import { apiRequest } from './client.js'

// Auth endpoints (Phase 1). Each helper returns the inner `data` object from
// the backend's `{ success, message, data }` envelope.
export const authApi = {
  /** Log in an admin with email + password. Resolves to `{ token, user }`. */
  loginAdmin: ({ email, password }) =>
    apiRequest('/auth/admin/login', {
      method: 'POST',
      body: { email, password },
      auth: false,
    }).then((r) => r.data),

  /** Log in a member with mobile-or-email + password. Resolves to `{ token, user }`. */
  loginMember: ({ identifier, password }) =>
    apiRequest('/auth/member/login', {
      method: 'POST',
      body: { identifier, password },
      auth: false,
    }).then((r) => r.data),

  /** Fetch the currently authenticated user. Resolves to `{ user }`. */
  getMe: () => apiRequest('/auth/me').then((r) => r.data),
}
