// Generated by GitHub Copilot
// Lightweight fetch wrapper for the Maqasid Bank backend API. Handles the
// base URL, JSON encoding, bearer-token injection and error normalization.

const TOKEN_KEY = 'maqasid_token'

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'

/** Read the persisted JWT (or null when signed out). */
export const getToken = () => localStorage.getItem(TOKEN_KEY)

/** Persist the JWT so the session survives reloads. */
export const setToken = (token) => localStorage.setItem(TOKEN_KEY, token)

/** Remove the stored JWT on logout or when the session is invalid. */
export const clearToken = () => localStorage.removeItem(TOKEN_KEY)

/**
 * Perform an API request and return the parsed JSON body.
 *
 * Security: the token is only attached when `auth` is true, and is sent via the
 * standard Authorization header rather than a query string to avoid leaking it
 * into logs. Non-2xx responses throw an Error carrying the server message,
 * HTTP status and any field-level validation errors.
 *
 * @param {string} path API path beginning with a slash, e.g. "/auth/me".
 * @param {{ method?: string, body?: unknown, auth?: boolean }} [options]
 * @returns {Promise<any>} Parsed JSON payload.
 */
export async function apiRequest(path, { method = 'GET', body, auth = true } = {}) {
  const headers = { 'Content-Type': 'application/json' }

  if (auth) {
    const token = getToken()
    if (token) headers.Authorization = `Bearer ${token}`
  }

  let res
  try {
    res = await fetch(`${BASE_URL}${path}`, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    })
  } catch {
    // Network failure / server unreachable.
    throw new Error('Cannot reach the server. Please try again.')
  }

  let payload = null
  try {
    payload = await res.json()
  } catch {
    // Empty or non-JSON body — leave payload as null.
  }

  if (!res.ok) {
    const error = new Error(payload?.message || `Request failed (${res.status})`)
    error.status = res.status
    error.errors = payload?.errors
    throw error
  }

  return payload
}
