// Generated by GitHub Copilot
import { apiRequest } from './client.js'

// Contribution management endpoints (Phase 4).
export const contributionApi = {
  /** Generate monthly contributions for all active members. */
  generate: (month) =>
    apiRequest('/contributions/generate', {
      method: 'POST',
      body: { month },
    }).then((r) => r.data),

  /** List contributions with optional filters. */
  list: (params = {}) =>
    apiRequest(`/contributions?${new URLSearchParams(params)}`).then((r) => r.data),

  /** Update contribution payment status. */
  updateStatus: (id, status) =>
    apiRequest(`/contributions/${id}/status`, {
      method: 'PATCH',
      body: { status },
    }).then((r) => r.data),

  /** Bulk update multiple contributions. */
  bulkUpdate: (contributionIds, status) =>
    apiRequest('/contributions/bulk-update', {
      method: 'POST',
      body: { contributionIds, status },
    }).then((r) => r.data),
}
