// Generated by GitHub Copilot
import { apiRequest } from './client.js'

// Dashboard statistics endpoints (Phase 8).
export const dashboardApi = {
  /** Get admin dashboard statistics. */
  getAdminStats: () =>
    apiRequest('/dashboard/admin').then((r) => r.data),
}