// Generated by GitHub Copilot
import { apiRequest } from './client.js'

// Loan management endpoints (Phase 6).
export const loanApi = {
  /** Create a new loan. */
  create: (data) =>
    apiRequest('/loans', {
      method: 'POST',
      body: data,
    }).then((r) => r.data),

  /** List all loans with optional filters. */
  list: (params = {}) =>
    apiRequest(`/loans?${new URLSearchParams(params)}`).then((r) => r.data),

  /** Get loan by ID. */
  getById: (id) =>
    apiRequest(`/loans/${id}`).then((r) => r.data),

  /** Update loan status. */
  updateStatus: (id, status) =>
    apiRequest(`/loans/${id}/status`, {
      method: 'PATCH',
      body: { status },
    }).then((r) => r.data),

  /** Record a loan repayment. */
  repay: (id, data) =>
    apiRequest(`/loans/${id}/repay`, {
      method: 'POST',
      body: data,
    }).then((r) => r.data),

  /** Close a loan (mark as paid with closedAt date). */
  close: (id) =>
    apiRequest(`/loans/${id}/close`, {
      method: 'PATCH',
    }).then((r) => r.data),

  /** Get member's loans. */
  getMemberLoans: (memberId) =>
    apiRequest(`/members/${memberId}/loans`).then((r) => r.data),

  /** Get available funds for issuing loans. */
  getAvailableFunds: () =>
    apiRequest('/loans/available-funds').then((r) => r.data),

  /** Get all loan requests (admin). */
  getLoanRequests: () =>
    apiRequest('/admin/loan-requests').then((r) => r.data),

  /** Approve a loan request (admin). */
  approveLoanRequest: (id, data) =>
    apiRequest(`/admin/loan-requests/${id}/approve`, { method: 'PATCH', body: data }).then((r) => r.data),

  /** Reject a loan request (admin). */
  rejectLoanRequest: (id, data) =>
    apiRequest(`/admin/loan-requests/${id}/reject`, { method: 'PATCH', body: data }).then((r) => r.data),

  /** Reorder a pending loan request in the queue (admin). */
  reorderLoanRequest: (id, direction) =>
    apiRequest(`/admin/loan-requests/${id}/reorder`, { method: 'PATCH', body: { direction } }).then((r) => r.data),
}
