// Generated by GitHub Copilot
import { apiRequest } from './client.js'

// Member management endpoints (Phase 2).
export const memberApi = {
  /** Create a new member. Resolves to `{ member }`. */
  create: (data) =>
    apiRequest('/members', {
      method: 'POST',
      body: data,
    }).then((r) => r.data),

  /** List members with optional search, status filter and pagination. Resolves to `{ members, pagination }`. */
  list: (params = {}) =>
    apiRequest(`/members?${new URLSearchParams(params)}`).then((r) => r.data),

  /** Get a single member by id. Resolves to `{ member }`. */
  getById: (id) =>
    apiRequest(`/members/${id}`).then((r) => r.data),

  /** Update a member. Resolves to `{ member }`. */
  update: (id, data) =>
    apiRequest(`/members/${id}`, {
      method: 'PUT',
      body: data,
    }).then((r) => r.data),

  /** Activate or deactivate a member. Resolves to `{ member }`. */
  setStatus: (id, status) =>
    apiRequest(`/members/${id}/status`, {
      method: 'PATCH',
      body: { status },
    }).then((r) => r.data),

  /** Soft-delete a member. Resolves to `{ member }`. */
  delete: (id) =>
    apiRequest(`/members/${id}`, {
      method: 'DELETE',
    }).then((r) => r.data),
}