// Generated by GitHub Copilot
import { apiRequest } from './client.js'

/** Member loan endpoints. */
export const memberLoanApi = {
  /** Fetch logged-in member's loans with pagination and filters. */
  getMyLoans: (params = {}) =>
    apiRequest(`/member/loans?${new URLSearchParams(params)}`).then((r) => r.data),

  /** Fetch a single logged-in member loan by ID. */
  getMyLoanById: (loanId) =>
    apiRequest(`/member/loans/${loanId}`).then((r) => r.data),

  /** Fetch logged-in member's loan summary statistics. */
  getMyLoanSummary: () =>
    apiRequest('/member/loans/summary').then((r) => r.data),

  /** Fetch loan passbook with payment history. */
  getMyLoanPassbook: (loanId) =>
    apiRequest(`/member/loans/${loanId}/passbook`).then((r) => r.data),

  /** Submit a new loan request. */
  applyForLoan: (body) =>
    apiRequest('/member/loan-requests', { method: 'POST', body }).then((r) => r.data),

  /** Fetch available funds shown on the apply form. */
  getAvailableFunds: () =>
    apiRequest('/member/loan-requests/available-funds').then((r) => r.data.availableFunds),

  /** Fetch all loan requests for the logged-in member. */
  getMyLoanRequests: () =>
    apiRequest('/member/loan-requests').then((r) => r.data),

  /** Withdraw a pending or approved loan request. */
  withdrawLoanRequest: (requestId) =>
    apiRequest(`/member/loan-requests/${requestId}/withdraw`, { method: 'PATCH' }).then((r) => r.data),
}
