// Generated by GitHub Copilot
import { apiRequest } from './client.js'

/** Member loan endpoints. */
export const memberLoanApi = {
  /** Fetch logged-in member's loans with pagination and filters. */
  getMyLoans: (params = {}) =>
    apiRequest(`/member/loans?${new URLSearchParams(params)}`).then((r) => r.data),

  /** Fetch a single logged-in member loan by ID. */
  getMyLoanById: (loanId) =>
    apiRequest(`/member/loans/${loanId}`).then((r) => r.data),

  /** Fetch logged-in member's loan summary statistics. */
  getMyLoanSummary: () =>
    apiRequest('/member/loans/summary').then((r) => r.data),

  /** Fetch loan passbook with payment history. */
  getMyLoanPassbook: (loanId) =>
    apiRequest(`/member/loans/${loanId}/passbook`).then((r) => r.data),
}
