// Generated by GitHub Copilot
import { apiRequest } from './client.js'

/** Member endpoints (admin management + member self-service). */
export const memberApi = {
  /** List members with pagination. Resolves to `{ members, pagination }`. */
  list: (query = {}) =>
    apiRequest('/members', {
      search: query.search,
      status: query.status,
      page: query.page,
      limit: query.limit,
    }).then((r) => r.data),

  /** Create a new member. Resolves to `{ member }`. */
  create: (data) =>
    apiRequest('/members', {
      method: 'POST',
      body: data,
    }).then((r) => r.data),

  /** Fetch a single member by ID. Resolves to `{ member }`. */
  getById: (id) => apiRequest(`/members/${id}`).then((r) => r.data),

  /** Update a member. Resolves to `{ member }`. */
  update: (id, data) =>
    apiRequest(`/members/${id}`, {
      method: 'PUT',
      body: data,
    }).then((r) => r.data),

  /** Update member status (Active/Inactive). Resolves to `{ member }`. */
  setStatus: (id, status) =>
    apiRequest(`/members/${id}/status`, {
      method: 'PATCH',
      body: { status },
    }).then((r) => r.data),

  /** Soft-delete a member. */
  delete: (id) =>
    apiRequest(`/members/${id}`, {
      method: 'DELETE',
    }).then((r) => r.data),

  // ---- Member self-service endpoints ----

  /** Fetch the logged-in member's profile. Resolves to `{ member }`. */
  getProfile: () => apiRequest('/member/profile').then((r) => r.data),

  /** Change the logged-in member's password. */
  updatePassword: ({ currentPassword, newPassword, confirmNewPassword }) =>
    apiRequest('/member/profile/password', {
      method: 'PUT',
      body: { currentPassword, newPassword, confirmNewPassword },
    }).then((r) => r.data),
}
