// Generated by GitHub Copilot
import { apiRequest } from './client.js'

/** Member contribution endpoints. */
export const memberContributionApi = {
  /** Fetch logged-in member's contributions with pagination and filters. */
  getMyContributions: (params = {}) =>
    apiRequest(`/member/contributions?${new URLSearchParams(params)}`).then((r) => r.data),

  /** Fetch logged-in member's contribution summary statistics. */
  getMyContributionSummary: () =>
    apiRequest('/member/contributions/summary').then((r) => r.data),

  /** Fetch a single contribution by ID. */
  getMyContributionById: (id) =>
    apiRequest(`/member/contributions/${id}`).then((r) => r.data),

  /** Fetch contributions by year. */
  getMyContributionsByYear: (year) =>
    apiRequest(`/member/contributions/year/${year}`).then((r) => r.data),
}
