// Generated by GitHub Copilot
import { apiRequest } from './client.js'

/** In-app notification API — available to both admin and member roles. */
export const notificationApi = {
  /** Get paginated notifications for the current user. */
  getNotifications: (params = {}) => {
    const qs = new URLSearchParams()
    Object.entries(params).forEach(([k, v]) => {
      if (v != null && v !== '') qs.append(k, v)
    })
    const query = qs.toString()
    return apiRequest(`/notifications${query ? `?${query}` : ''}`).then((r) => r.data)
  },

  /** Get the count of unread notifications for the current user. */
  getUnreadCount: () =>
    apiRequest('/notifications/unread-count').then((r) => r.data),

  /** Mark a single notification as read. */
  markRead: (id) =>
    apiRequest(`/notifications/${id}/read`, { method: 'PATCH' }).then((r) => r.data),

  /** Mark all notifications as read for the current user. */
  markAllRead: () =>
    apiRequest('/notifications/read-all', { method: 'PATCH' }).then((r) => r.data),
}
