// Generated by GitHub Copilot
import { apiRequest } from './client.js'

// Contribution reports endpoints (Phase 5).
export const reportApi = {
  /** Get overall contribution summary. */
  getSummary: () =>
    apiRequest('/reports/contributions/summary').then((r) => r.data),

  /** Get monthly breakdown for the last N months. */
  getMonthlyBreakdown: (months = 12) =>
    apiRequest(`/reports/contributions/monthly?months=${months}`).then((r) => r.data),

  /** Get individual member's contribution history. */
  getMemberHistory: (memberId, months = 12) =>
    apiRequest(`/reports/contributions/member/${memberId}?months=${months}`).then((r) => r.data),

  /** Get defaulters list. */
  getDefaulters: () =>
    apiRequest('/reports/contributions/defaulters').then((r) => r.data),

  /** Get loan portfolio summary. */
  getLoanPortfolioSummary: () =>
    apiRequest('/reports/loans/summary').then((r) => r.data),
}
