// Generated by GitHub Copilot
// Small formatting helpers shared across the UI.

/** Format a number as Indian Rupees, e.g. 45000 -> "₹45,000". */
export function formatCurrency(value) {
  const num = Number(value) || 0
  return `₹${num.toLocaleString('en-IN')}`
}

/** Format an ISO date (YYYY-MM-DD) as "05 Jun 2024". Returns "—" when empty. */
export function formatDate(iso) {
  if (!iso) return '—'
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return '—'
  return date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

/** Return the initials for a name, e.g. "Rahul Sharma" -> "RS". */
export function getInitials(name = '') {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0].toUpperCase())
    .join('')
}
