// Generated by GitHub Copilot
// Centralised, validated access to environment variables. Fail fast on boot
// if a required secret is missing so misconfiguration is caught immediately.
require('dotenv').config()

/**
 * Read an environment variable, throwing when a required one is absent.
 * @param {string} key - Variable name.
 * @param {string} [fallback] - Optional default for non-critical values.
 * @returns {string}
 */
function required(key, fallback) {
  const value = process.env[key] ?? fallback
  if (value === undefined || value === '') {
    throw new Error(`Missing required environment variable: ${key}`)
  }
  return value
}

const env = {
  port: Number(process.env.PORT || 5000),
  nodeEnv: process.env.NODE_ENV || 'development',
  clientUrl: process.env.CLIENT_URL || 'http://localhost:5173,http://localhost:5174',
  mongoUri: required('MONGO_URI', 'mongodb://127.0.0.1:27017/maqasid_bank'),
  // Optional comma-separated DNS servers used to resolve the Atlas SRV record
  // on networks whose default resolver refuses SRV queries (querySrv ECONNREFUSED).
  dnsServers: process.env.DNS_SERVERS || '',
  jwtSecret: required('JWT_SECRET'),
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || '1d',
}

module.exports = env
