// Generated by GitHub Copilot
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react'
import { authApi } from '../api/authApi.js'
import { clearToken, getToken, setToken } from '../api/client.js'

const AuthContext = createContext(null)

/**
 * Provides authentication state backed by the Maqasid Bank API (Phase 1).
 * The JWT is persisted in localStorage so sessions survive reloads, and the
 * current user is re-hydrated from `GET /api/auth/me` on startup.
 */
export function AuthProvider({ children }) {
  const [user, setUser] = useState(null)
  // `loading` is true while we validate a stored token on first mount, so
  // guarded routes wait instead of bouncing the user to /login prematurely.
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const token = getToken()
    if (!token) {
      setLoading(false)
      return undefined
    }

    let active = true
    authApi
      .getMe()
      .then((data) => {
        if (active) setUser(data.user)
      })
      .catch(() => {
        // Token expired or invalid — clear it so the user can sign in again.
        clearToken()
      })
      .finally(() => {
        if (active) setLoading(false)
      })

    return () => {
      active = false
    }
  }, [])

  /**
   * Authenticate against the backend and persist the session.
   * @param {{ role: 'admin' | 'member', identifier: string, password: string }} creds
   * @returns {Promise<object>} The authenticated user profile.
   */
  const login = useCallback(async ({ role, identifier, password }) => {
    const data =
      role === 'admin'
        ? await authApi.loginAdmin({ email: identifier, password })
        : await authApi.loginMember({ identifier, password })

    setToken(data.token)
    setUser(data.user)
    return data.user
  }, [])

  const logout = useCallback(() => {
    clearToken()
    setUser(null)
  }, [])

  const value = useMemo(
    () => ({ user, isAuthenticated: !!user, loading, login, logout }),
    [user, loading, login, logout],
  )

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useAuthContext() {
  const ctx = useContext(AuthContext)
  if (!ctx) throw new Error('useAuthContext must be used within AuthProvider')
  return ctx
}
