// Generated by GitHub Copilot
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import { memberApi } from '../api/memberApi.js'
import { contributionApi } from '../api/contributionApi.js'
import { loanApi } from '../api/loanApi.js'
import { useAuth } from '../hooks/useAuth.js'

const DataContext = createContext(null)

/**
 * Central data store for members, contributions, loans and activity.
 * Members are fetched from the backend API. Contributions, loans and activity
 * will be connected to the API in future phases.
 */
export function DataProvider({ children }) {
  const [members, setMembers] = useState([])
  const [contributions, setContributions] = useState([])
  const [loans, setLoans] = useState([])
  const [activity, setActivity] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const { isAuthenticated, user } = useAuth()

  /** Normalize a member from the API (map _id to id, ensure status casing). */
  const normalizeMember = useCallback((m) => ({
    ...m,
    id: m._id || m.id,
    status: m.status === 'Active' ? 'active' : m.status === 'Inactive' ? 'inactive' : m.status,
  }), [])

  // Fetch members from the API when authenticated.
  useEffect(() => {
    if (!isAuthenticated) {
      setLoading(false)
      return
    }

    let active = true
    setLoading(true)
    memberApi
      .list({ limit: 100 })
      .then((data) => {
        if (active) {
          const normalized = (data.members || []).map(normalizeMember)
          setMembers(normalized)
          setLoading(false)
        }
      })
      .catch((err) => {
        if (active) {
          setError(err.message)
          setLoading(false)
        }
      })
    return () => {
      active = false
    }
  }, [isAuthenticated, normalizeMember])

  // Fetch contributions from the API when authenticated (admin only).
  useEffect(() => {
    if (!isAuthenticated || user?.role !== 'admin') return

    let active = true
    contributionApi
      .list({ limit: 100 })
      .then((data) => {
        if (active) {
          const normalized = (data.contributions || []).map((c) => {
            const [year, month] = (c.month || '').split('-')
            const monthNum = parseInt(month, 10)
            const monthLabels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            const label = monthNum > 0 && monthNum <= 12 ? `${monthLabels[monthNum - 1]} ${year}` : c.month
            return { ...c, label }
          })
          setContributions(normalized)
        }
      })
      .catch(() => {
        // Contributions API may not be ready yet; keep empty array
      })
    return () => {
      active = false
    }
  }, [isAuthenticated, user?.role])

  // Fetch loans from the API when authenticated (admin only).
  useEffect(() => {
    if (!isAuthenticated || user?.role !== 'admin') return

    let active = true
    loanApi
      .list({ limit: 100 })
      .then((data) => {
        if (active) {
          setLoans(data.loans || [])
        }
      })
      .catch(() => {
        // Loans API may not be ready yet; keep empty array
      })
    return () => {
      active = false
    }
  }, [isAuthenticated, user?.role])

  /** Add a new member via the API. Returns the created record. */
  const addMember = useCallback(async (input) => {
    const { member } = await memberApi.create(input)
    setMembers((prev) => [normalizeMember(member), ...prev])
    setActivity((prev) => [
      {
        id: `A${Date.now()}`,
        type: 'member',
        title: 'New member joined',
        description: `${member.name} joined the fund.`,
        date: member.joiningDate,
        amount: null,
      },
      ...prev,
    ])
    return member
  }, [])

  /** Toggle a member's contribution status for a given month. */
  const setContributionStatus = useCallback(async (contributionId, status) => {
    await contributionApi.updateStatus(contributionId, status)
    setContributions((prev) =>
      prev.map((c) =>
        c.id === contributionId
          ? {
              ...c,
              status,
              paymentDate: status === 'paid' ? new Date().toISOString().slice(0, 10) : null,
            }
          : c,
      ),
    )
  }, [])

  /** Assign a new active loan to a member via the API. Returns the created loan. */
  const assignLoan = useCallback(async (input) => {
    const { loan } = await loanApi.create(input)
    const normalized = {
      ...loan,
      id: loan._id || loan.id,
    }
    setLoans((prev) => [normalized, ...prev])
    setMembers((prev) =>
      prev.map((m) =>
        m.id === normalized.memberId
          ? { ...m, activeLoan: (m.activeLoan || 0) + Number(normalized.amount) }
          : m,
      ),
    )
    setActivity((prev) => [
      {
        id: `A${Date.now()}`,
        type: 'loan',
        title: 'Loan assigned',
        description: `New loan of ₹${Number(normalized.amount).toLocaleString('en-IN')} issued to ${normalized.memberName}.`,
        date: normalized.issueDate,
        amount: Number(normalized.amount),
      },
      ...prev,
    ])
    return normalized
  }, [])

  /** Update a member's status (Active/Inactive) via the API. */
  const updateMemberStatus = useCallback(async (id, status) => {
    const { member } = await memberApi.setStatus(id, status)
    setMembers((prev) =>
      prev.map((m) => (m.id === id ? { ...m, status: member.status === 'Active' ? 'active' : 'inactive' } : m)),
    )
    return member
  }, [])

  /** Update a member's fields via the API. */
  const updateMember = useCallback(async (id, data) => {
    const { member } = await memberApi.update(id, data)
    setMembers((prev) =>
      prev.map((m) => (m.id === id ? normalizeMember(member) : m)),
    )
    return member
  }, [])

  /** Soft-delete a member via the API. */
  const deleteMember = useCallback(async (id) => {
    await memberApi.delete(id)
    setMembers((prev) => prev.filter((m) => m.id !== id))
  }, [])

  // ---- Derived selectors -------------------------------------------------

  const getMemberById = useCallback(
    (id) => members.find((m) => m.id === id) ?? null,
    [members],
  )

  const getContributionsByMember = useCallback(
    (id) =>
      contributions
        .filter((c) => String(c.memberId) === String(id))
        .sort((a, b) => b.month.localeCompare(a.month)),
    [contributions],
  )

  const getLoansByMember = useCallback(
    (id) => loans.filter((l) => l.memberId === id),
    [loans],
  )

  /** Fixed "current" period for the contributions page. */
  const currentMonthStr = useMemo(() => {
    const now = new Date()
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  }, [])

  /** One "current month" row per member for the contribution management page. */
  const currentMonthContributions = useMemo(
    () =>
      members.map((member) => {
        const record = contributions.find(
          (c) => c.memberId === member.id && c.month === currentMonthStr,
        )
        return {
          member,
          contribution: record ?? null,
          status: record ? record.status : 'unpaid',
        }
      }),
    [members, contributions, currentMonthStr],
  )

  const stats = useMemo(() => {
    const totalFunds = contributions
      .filter((c) => c.status === 'paid')
      .reduce((sum, c) => sum + c.amount, 0)
    const totalActiveLoanAmount = loans
      .filter((l) => l.status === 'active')
      .reduce((sum, l) => sum + l.remaining, 0)
    return {
      totalMembers: members.length,
      activeMembers: members.filter((m) => m.status === 'active').length,
      totalFunds,
      totalActiveLoans: loans.filter((l) => l.status === 'active').length,
      totalActiveLoanAmount,
      availableBalance: totalFunds - totalActiveLoanAmount,
    }
  }, [members, contributions, loans])

  const value = useMemo(
    () => ({
      members,
      contributions,
      setContributions,
      loans,
      activity,
      stats,
      loading,
      error,
      currentMonthContributions,
      currentMonthStr,
      addMember,
      setContributionStatus,
      assignLoan,
      updateMember,
      updateMemberStatus,
      deleteMember,
      getMemberById,
      getContributionsByMember,
      getLoansByMember,
    }),
    [
      members,
      contributions,
      loans,
      activity,
      stats,
      loading,
      error,
      currentMonthContributions,
      currentMonthStr,
      addMember,
      setContributionStatus,
      assignLoan,
      setContributions,
      updateMember,
      updateMemberStatus,
      deleteMember,
      getMemberById,
      getContributionsByMember,
      getLoansByMember,
    ],
  )

  return <DataContext.Provider value={value}>{children}</DataContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useDataContext() {
  const ctx = useContext(DataContext)
  if (!ctx) throw new Error('useDataContext must be used within DataProvider')
  return ctx
}

/**
 * Build demo contribution records for the current month so the contributions
 * page is functional before the real API is wired up in Phase 4.
 */
function buildDemoContributions(members) {
  const now = new Date()
  const currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const MONTHLY_AMOUNT = 2000

  return members.map((member, index) => {
    const memberNum = parseInt(member.id.slice(-5), 10) || index
    const isPaid = memberNum % 2 === 0
    const paymentDate = isPaid
      ? `${currentMonth}-${String(5 + (memberNum % 10)).padStart(2, '0')}`
      : null

    return {
      id: `C-${member.id}-${currentMonth}`,
      memberId: member.id,
      month: currentMonth,
      label: now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' }),
      amount: MONTHLY_AMOUNT,
      paymentDate,
      status: isPaid ? 'paid' : 'unpaid',
    }
  })
}
