// Generated by GitHub Copilot
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import { settingsApi } from '../api/settingsApi.js'

const SettingsContext = createContext(null)

/**
 * Holds application-wide settings fetched from the backend API.
 * When the monthly amount is updated, it persists to the backend which also
 * syncs the new amount to all existing contribution records.
 */
export function SettingsProvider({ children }) {
  const [monthlyAmount, setMonthlyAmount] = useState(2000)
  const [loading, setLoading] = useState(true)

  // Fetch settings from the API on mount.
  useEffect(() => {
    let active = true
    settingsApi
      .get()
      .then((data) => {
        if (active && data.monthlyAmount) {
          setMonthlyAmount(data.monthlyAmount)
        }
      })
      .catch(() => {
        // API may not be ready yet; keep default
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [])

  /**
   * Persist the monthly amount to the backend. The backend also syncs the
   * new amount to all existing contribution records automatically.
   */
  const persistMonthlyAmount = useCallback(async (amount) => {
    const data = await settingsApi.update({ monthlyAmount: amount })
    setMonthlyAmount(data.monthlyAmount)
    return data
  }, [])

  const value = useMemo(
    () => ({ monthlyAmount, setMonthlyAmount: persistMonthlyAmount, loading }),
    [monthlyAmount, persistMonthlyAmount, loading],
  )

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  )
}

// eslint-disable-next-line react-refresh/only-export-components
export function useSettingsContext() {
  const ctx = useContext(SettingsContext)
  if (!ctx)
    throw new Error('useSettingsContext must be used within SettingsProvider')
  return ctx
}