// Generated by GitHub Copilot
const { query, param } = require('express-validator')

const AUDIT_ACTIONS = [
  'LOGIN',
  'MEMBER_CREATED',
  'MEMBER_UPDATED',
  'MEMBER_DELETED',
  'MEMBER_STATUS_CHANGED',
  'CONTRIBUTION_RECORDED',
  'CONTRIBUTION_STATUS_CHANGED',
  'LOAN_ISSUED',
  'LOAN_STATUS_CHANGED',
  'REPAYMENT_RECORDED',
  'SETTINGS_UPDATED',
]

const AUDIT_ENTITIES = [
  'Auth',
  'Member',
  'Contribution',
  'Loan',
  'LoanRepayment',
  'ContributionSetting',
]

/** Validation rules for GET /api/audit-logs query params. */
const auditLogQueryRules = [
  query('action')
    .optional()
    .isIn(AUDIT_ACTIONS)
    .withMessage(`action must be one of: ${AUDIT_ACTIONS.join(', ')}`),
  query('entity')
    .optional()
    .isIn(AUDIT_ENTITIES)
    .withMessage(`entity must be one of: ${AUDIT_ENTITIES.join(', ')}`),
  query('performedByRole')
    .optional()
    .isIn(['admin', 'member'])
    .withMessage('performedByRole must be admin or member'),
  query('startDate').optional().isISO8601().withMessage('startDate must be a valid ISO 8601 date'),
  query('endDate').optional().isISO8601().withMessage('endDate must be a valid ISO 8601 date'),
  query('page').optional().isInt({ min: 1 }).withMessage('page must be a positive integer').toInt(),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('limit must be between 1 and 100')
    .toInt(),
]

module.exports = { auditLogQueryRules }
