// Generated by GitHub Copilot
const jwt = require('jsonwebtoken')
const env = require('../config/env')
const ApiError = require('../utils/ApiError')
const asyncHandler = require('../utils/asyncHandler')
const Admin = require('../models/Admin')
const Member = require('../models/Member')

/**
 * Verifies the Bearer JWT, loads the matching account and attaches it to the
 * request as `req.user` (with `req.user.role`). Rejects missing/invalid tokens.
 */
const protect = asyncHandler(async (req, res, next) => {
  const header = req.headers.authorization || ''
  if (!header.startsWith('Bearer ')) {
    throw new ApiError(401, 'Not authorized, no token provided')
  }

  const token = header.split(' ')[1]

  let decoded
  try {
    decoded = jwt.verify(token, env.jwtSecret)
  } catch (err) {
    throw new ApiError(401, 'Not authorized, token is invalid or expired')
  }

  const Model = decoded.role === 'admin' ? Admin : Member
  const account = await Model.findById(decoded.id)
  if (!account) {
    throw new ApiError(401, 'Not authorized, account no longer exists')
  }

  // Block sign-in access for deactivated members.
  if (decoded.role === 'member' && account.status === 'Inactive') {
    throw new ApiError(403, 'Your account is inactive. Contact the admin.')
  }

  req.user = account
  req.user.role = decoded.role
  next()
})

/**
 * Restricts a route to the given roles. Must run after `protect`.
 * @param {...('admin'|'member')} roles - Allowed roles.
 */
function authorize(...roles) {
  return (req, res, next) => {
    if (!req.user || !roles.includes(req.user.role)) {
      return next(
        new ApiError(403, 'You do not have permission to access this resource'),
      )
    }
    return next()
  }
}

module.exports = { protect, authorize }
