// Generated by GitHub Copilot
const { body } = require('express-validator')

/** Validation chain for admin login. */
const adminLoginRules = [
  body('email')
    .trim()
    .notEmpty()
    .withMessage('Email is required')
    .bail()
    .isEmail()
    .withMessage('Provide a valid email')
    .normalizeEmail(),
  body('password')
    .notEmpty()
    .withMessage('Password is required'),
]

/** Validation chain for member login (mobile or email + password). */
const memberLoginRules = [
  body('identifier')
    .trim()
    .notEmpty()
    .withMessage('Mobile or email is required'),
  body('password')
    .notEmpty()
    .withMessage('Password is required'),
]

module.exports = { adminLoginRules, memberLoginRules }
