// Generated by GitHub Copilot
const { body, query } = require('express-validator')

/** Validation for generating monthly contributions. */
const generateRules = [
  body('month')
    .notEmpty()
    .withMessage('Month is required')
    .bail()
    .matches(/^\d{4}-\d{2}$/)
    .withMessage('Month must be in YYYY-MM format'),
]

/** Validation for listing contributions query params. */
const listQueryRules = [
  query('month').optional().matches(/^\d{4}-\d{2}$/).withMessage('Month must be in YYYY-MM format'),
  query('status')
    .optional()
    .isIn(['paid', 'unpaid'])
    .withMessage('Status must be paid or unpaid'),
  query('search').optional().trim(),
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer')
    .toInt(),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100')
    .toInt(),
]

/** Validation for updating contribution status. */
const statusRules = [
  body('status')
    .notEmpty()
    .withMessage('Status is required')
    .bail()
    .isIn(['paid', 'unpaid'])
    .withMessage('Status must be paid or unpaid'),
]

module.exports = {
  generateRules,
  listQueryRules,
  statusRules,
}