// Generated by GitHub Copilot
const ApiError = require('../utils/ApiError')
const env = require('../config/env')

/** 404 handler for unmatched routes. */
function notFound(req, res, next) {
  next(new ApiError(404, `Route not found: ${req.method} ${req.originalUrl}`))
}

/**
 * Central error handler. Normalises operational errors, Mongo duplicate-key
 * errors and Mongoose validation errors into a consistent JSON envelope.
 */
// eslint-disable-next-line no-unused-vars
function errorHandler(err, req, res, next) {
  let statusCode = err.statusCode || 500
  let message = err.message || 'Internal Server Error'
  let errors = err.errors || []

  // Mongoose bad ObjectId
  if (err.name === 'CastError') {
    statusCode = 400
    message = `Invalid ${err.path}: ${err.value}`
  }

  // Mongoose validation error
  if (err.name === 'ValidationError') {
    statusCode = 422
    message = 'Validation failed'
    errors = Object.values(err.errors).map((e) => ({
      field: e.path,
      message: e.message,
    }))
  }

  // Duplicate key (e.g. email/mobile already exists)
  if (err.code === 11000) {
    statusCode = 409
    const field = Object.keys(err.keyValue || {})[0]
    message = `${field} already exists`
    errors = [{ field, message }]
  }

  const payload = {
    success: false,
    message,
  }
  if (errors.length) payload.errors = errors
  if (env.nodeEnv === 'development') payload.stack = err.stack

  res.status(statusCode).json(payload)
}

module.exports = { notFound, errorHandler }
