// Generated by GitHub Copilot
const { body, param } = require('express-validator')

/** Ensure a YYYY-MM month is within the current month .. current + 3 months. */
function monthWithinThreeMonths(val) {
  const [y, m] = val.split('-').map(Number)
  const now = new Date()
  const current = now.getFullYear() * 12 + now.getMonth()
  const selected = y * 12 + (m - 1)
  const diff = selected - current
  if (diff < 0) throw new Error('Month cannot be in the past')
  if (diff > 3) throw new Error('Month cannot be more than 3 months ahead')
  return true
}

/** Member: submit a new loan request. */
const applyRules = [
  body('amount')
    .notEmpty().withMessage('Loan amount is required')
    .bail()
    .isFloat({ gt: 0 }).withMessage('Loan amount must be greater than 0'),
  body('monthRequired')
    .notEmpty().withMessage('Month is required')
    .bail()
    .matches(/^\d{4}-\d{2}$/).withMessage('Month must be in YYYY-MM format')
    .bail()
    .custom(monthWithinThreeMonths),
  body('purpose')
    .trim()
    .notEmpty().withMessage('Purpose is required'),
  body('expectedReturn')
    .optional({ nullable: true, checkFalsy: true })
    .isISO8601().withMessage('Expected return must be a valid date'),
  body('notes').optional({ nullable: true }).isString(),
]

/** Admin: approve a loan request (all fields optional overrides). */
const approveRules = [
  param('id').isMongoId().withMessage('Invalid loan request ID'),
  body('amount')
    .optional()
    .isFloat({ gt: 0 }).withMessage('Loan amount must be greater than 0'),
  body('monthRequired')
    .optional()
    .matches(/^\d{4}-\d{2}$/).withMessage('Month must be in YYYY-MM format'),
  body('expectedReturn')
    .optional({ nullable: true, checkFalsy: true })
    .isISO8601().withMessage('Expected return must be a valid date'),
  body('notes').optional({ nullable: true }).isString(),
]

/** Admin: reject a loan request. */
const rejectRules = [
  param('id').isMongoId().withMessage('Invalid loan request ID'),
  body('notes').optional({ nullable: true }).isString(),
]

/** Admin: move a request up/down the queue. */
const reorderRules = [
  param('id').isMongoId().withMessage('Invalid loan request ID'),
  body('direction')
    .isIn(['up', 'down']).withMessage('Direction must be "up" or "down"'),
]

/** Shared :id param validation. */
const idParamRules = [
  param('id').isMongoId().withMessage('Invalid loan request ID'),
]

module.exports = { applyRules, approveRules, rejectRules, reorderRules, idParamRules }
