// Generated by GitHub Copilot
const { body, query } = require('express-validator')

/** Validation for creating a loan. */
const createLoanRules = [
  body('memberId')
    .notEmpty()
    .withMessage('Member ID is required')
    .bail()
    .isMongoId()
    .withMessage('Invalid member ID'),
  body('amount')
    .notEmpty()
    .withMessage('Loan amount is required')
    .bail()
    .isInt({ min: 1 })
    .withMessage('Loan amount must be a whole number of at least 1'),
  body('issueDate')
    .notEmpty()
    .withMessage('Issue date is required')
    .bail()
    .isISO8601()
    .withMessage('Invalid issue date'),
  body('dueDate')
    .optional()
    .isISO8601()
    .withMessage('Invalid due date'),
  body('notes')
    .optional()
    .trim()
    .isLength({ max: 500 })
    .withMessage('Notes must be less than 500 characters'),
]

/** Validation for loan query parameters. */
const loanQueryRules = [
  query('status')
    .trim()
    .if((value) => value !== '')
    .isIn(['active', 'paid', 'defaulted'])
    .withMessage('Status must be active, paid, or defaulted'),
  query('memberId')
    .optional()
    .isMongoId()
    .withMessage('Invalid member ID'),
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer')
    .toInt(),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100')
    .toInt(),
]

/** Validation for updating loan status. */
const statusRules = [
  body('status')
    .notEmpty()
    .withMessage('Status is required')
    .bail()
    .isIn(['active', 'paid', 'defaulted'])
    .withMessage('Status must be active, paid, or defaulted'),
]

/** Validation for recording a repayment. */
const repayRules = [
  body('amount')
    .notEmpty()
    .withMessage('Repayment amount is required')
    .bail()
    .isInt({ min: 1 })
    .withMessage('Repayment amount must be a whole number of at least 1'),
  body('date')
    .notEmpty()
    .withMessage('Repayment date is required')
    .bail()
    .isISO8601()
    .withMessage('Invalid date'),
  body('notes')
    .optional()
    .trim()
    .isLength({ max: 500 })
    .withMessage('Notes must be less than 500 characters'),
]

module.exports = {
  createLoanRules,
  loanQueryRules,
  statusRules,
  repayRules,
}