// Generated by GitHub Copilot
const { query, param } = require('express-validator')

/** Validation chain for member contribution list query params. */
const contributionQueryRules = [
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer'),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100'),
  query('month')
    .optional()
    .matches(/^\d{4}-\d{2}$/)
    .withMessage('Month must be in YYYY-MM format'),
  query('status')
    .optional()
    .isIn(['paid', 'unpaid'])
    .withMessage('Status must be either paid or unpaid'),
  query('sort')
    .optional()
    .isIn(['-month', 'month', '-amount', 'amount', '-paymentDate', 'paymentDate'])
    .withMessage('Invalid sort field'),
]

/** Validation for contribution ID parameter. */
const contributionIdParamRules = [
  param('id')
    .isMongoId()
    .withMessage('Invalid contribution ID'),
]

/** Validation for year parameter. */
const yearParamRules = [
  param('year')
    .isInt({ min: 2000, max: 2100 })
    .withMessage('Year must be between 2000 and 2100'),
]

module.exports = { 
  contributionQueryRules,
  contributionIdParamRules,
  yearParamRules,
}
