// Generated by GitHub Copilot
const { query, param } = require('express-validator')

/** Validation chain for member loan list query params. */
const loanQueryRules = [
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer'),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100'),
  query('status')
    .optional()
    .isIn(['active', 'paid', 'defaulted', 'closed'])
    .withMessage('Status must be one of active, paid, defaulted, or closed'),
]

/** Validation for loan ID parameter. */
const loanIdParamRules = [
  param('loanId')
    .isMongoId()
    .withMessage('Invalid loan ID'),
]

module.exports = { loanQueryRules, loanIdParamRules }