// Generated by GitHub Copilot
const { body, param, query } = require('express-validator')

/** Validation for creating a member. */
const createMemberRules = [
  body('name')
    .trim()
    .notEmpty()
    .withMessage('Name is required')
    .bail()
    .isLength({ min: 2 })
    .withMessage('Name must be at least 2 characters'),
  body('mobile')
    .trim()
    .notEmpty()
    .withMessage('Mobile number is required')
    .bail()
    .matches(/^\d{10}$/)
    .withMessage('Mobile number must be exactly 10 digits'),
  body('email')
    .trim()
    .notEmpty()
    .withMessage('Email is required')
    .bail()
    .isEmail()
    .withMessage('Provide a valid email')
    .normalizeEmail(),
  body('password')
    .notEmpty()
    .withMessage('Password is required')
    .bail()
    .isLength({ min: 6 })
    .withMessage('Password must be at least 6 characters'),
  body('status')
    .optional()
    .isIn(['Active', 'Inactive'])
    .withMessage('Status must be Active or Inactive'),
  body('joiningDate')
    .optional()
    .isISO8601()
    .withMessage('Joining date must be a valid date'),
]

/** Validation for updating a member (all fields optional). */
const updateMemberRules = [
  body('name')
    .optional()
    .trim()
    .isLength({ min: 2 })
    .withMessage('Name must be at least 2 characters'),
  body('mobile')
    .optional()
    .trim()
    .matches(/^\d{10}$/)
    .withMessage('Mobile number must be exactly 10 digits'),
  body('email')
    .optional()
    .trim()
    .isEmail()
    .withMessage('Provide a valid email')
    .normalizeEmail(),
  body('password')
    .optional()
    .isLength({ min: 6 })
    .withMessage('Password must be at least 6 characters'),
  body('status')
    .optional()
    .isIn(['Active', 'Inactive'])
    .withMessage('Status must be Active or Inactive'),
  body('joiningDate')
    .optional()
    .isISO8601()
    .withMessage('Joining date must be a valid date'),
]

/** Validation for the activate/deactivate endpoint. */
const statusRules = [
  body('status')
    .notEmpty()
    .withMessage('Status is required')
    .bail()
    .isIn(['Active', 'Inactive'])
    .withMessage('Status must be Active or Inactive'),
]

/** Validation for a Mongo ObjectId route parameter. */
const idParamRules = [
  param('id').isMongoId().withMessage('Invalid member id'),
]

/** Validation for the list query parameters. */
const listQueryRules = [
  query('search').optional().trim(),
  query('status')
    .optional()
    .isIn(['Active', 'Inactive'])
    .withMessage('Status filter must be Active or Inactive'),
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer')
    .toInt(),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100')
    .toInt(),
]

module.exports = {
  createMemberRules,
  updateMemberRules,
  statusRules,
  idParamRules,
  listQueryRules,
}
