// Generated by GitHub Copilot
const ApiError = require('../utils/ApiError')

/**
 * Middleware that blocks access if the member still needs to change their
 * initial password. This should run after `protect` and `authorize('member')`
 * on every member route EXCEPT the password-change endpoint itself.
 */
function mustChangePwd(req, res, next) {
  if (req.user.role === 'member' && req.user.mustChangePassword) {
    return next(
      new ApiError(
        403,
        'You must change your password before accessing this resource',
      ),
    )
  }
  return next()
}

module.exports = { mustChangePwd }