// Generated by GitHub Copilot
const { query, param } = require('express-validator')

/** Validation for pagination query params on GET /api/notifications. */
const notificationQueryRules = [
  query('page').optional().isInt({ min: 1 }).withMessage('page must be a positive integer').toInt(),
  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('limit must be between 1 and 100')
    .toInt(),
]

/** Validate the :id param is a valid MongoDB ObjectId. */
const notificationIdRules = [
  param('id').isMongoId().withMessage('Invalid notification ID'),
]

module.exports = { notificationQueryRules, notificationIdRules }
