// Generated by GitHub Copilot
const { query } = require('express-validator')

/** Validation for report query parameters. */
const reportQueryRules = [
  query('months')
    .optional()
    .isInt({ min: 1, max: 60 })
    .withMessage('Months must be between 1 and 60')
    .toInt(),
]

module.exports = { reportQueryRules }