// Generated by GitHub Copilot
const { validationResult } = require('express-validator')
const ApiError = require('../utils/ApiError')

/**
 * Collects express-validator results and, when any rule failed, throws a 422
 * ApiError carrying the field-level details. Centralising this keeps route
 * handlers free of validation boilerplate.
 */
function validate(req, res, next) {
  const result = validationResult(req)
  if (result.isEmpty()) return next()

  const errors = result.array().map((e) => ({
    field: e.path,
    message: e.msg,
  }))
  return next(new ApiError(422, 'Validation failed', errors))
}

module.exports = validate
