// Generated by GitHub Copilot
import AppRoutes from './routes/AppRoutes.jsx'

/**
 * Root application component. Rendering is delegated to the route table,
 * which handles role-based protection for the admin and member areas.
 */
export default function App() {
  return <AppRoutes />
}
