// Generated by GitHub Copilot
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiCheckCircle, FiArrowLeft } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import Modal from '../../components/ui/Modal.jsx'
import Button from '../../components/ui/Button.jsx'
import AddMemberForm from '../../components/forms/AddMemberForm.jsx'
import { useData } from '../../hooks/useData.js'

/** Add member page. On submit it stores the member and shows a success modal. */
export default function AddMember() {
  const { addMember } = useData()
  const navigate = useNavigate()
  const [created, setCreated] = useState(null)
  const [fieldErrors, setFieldErrors] = useState({})
  const [submitError, setSubmitError] = useState('')

  const handleSubmit = async (values) => {
    try {
      setFieldErrors({})
      setSubmitError('')
      const member = await addMember(values)
      setCreated(member)
    } catch (err) {
      const nextFieldErrors = {}
      for (const e of err?.errors || []) {
        if (e?.field === 'email' || e?.field === 'mobile') {
          nextFieldErrors[e.field] = e.message
        }
      }
      setFieldErrors(nextFieldErrors)
      setSubmitError(err?.message || 'Failed to add member')
    }
  }

  return (
    <div>
      <Breadcrumb
        items={[
          { label: 'Members', to: '/admin/members' },
          { label: 'Add Member' },
        ]}
      />
      <PageHeader
        title="Add Member"
        description="Register a new member into the fund."
        action={
          <Button variant="secondary" icon={FiArrowLeft} onClick={() => navigate('/admin/members')}>
            Back
          </Button>
        }
      />

      <Card className="max-w-xl">
        <CardBody>
          <AddMemberForm
            onSubmit={handleSubmit}
            onCancel={() => navigate('/admin/members')}
            fieldErrors={fieldErrors}
            submitError={submitError}
          />
        </CardBody>
      </Card>

      <Modal
        open={!!created}
        onClose={() => navigate('/admin/members')}
        title="Member Added"
        size="sm"
        footer={
          <>
            <Button
              variant="secondary"
              onClick={() => {
                setCreated(null)
              }}
            >
              Add Another
            </Button>
            <Button onClick={() => navigate('/admin/members')}>
              View Members
            </Button>
          </>
        }
      >
        <div className="flex flex-col items-center gap-3 py-2 text-center">
          <span className="flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-green-600">
            <FiCheckCircle className="h-8 w-8" />
          </span>
          <div>
            <p className="text-base font-semibold text-slate-800">
              {created?.name} added successfully
            </p>
            <p className="mt-1 text-sm text-slate-500">
              Member ID {created?.id} has been created.
            </p>
          </div>
        </div>
      </Modal>
    </div>
  )
}
