// Generated by GitHub Copilot
import { useMemo, useState, useEffect } from 'react'
import { FiSearch, FiCheck, FiX, FiDollarSign, FiRefreshCw } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Input from '../../components/ui/Input.jsx'
import Select from '../../components/ui/Select.jsx'
import Button from '../../components/ui/Button.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Table, { THead, TBody, TR, TH, TD } from '../../components/ui/Table.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import StatCard from '../../components/cards/StatCard.jsx'
import { useData } from '../../hooks/useData.js'
import { useSettings } from '../../hooks/useSettings.js'
import { contributionApi } from '../../api/contributionApi.js'
import { formatCurrency, formatDate, getInitials } from '../../utils/format.js'

/**
 * Admin contribution management for the current month. Each row can be toggled
 * between paid and unpaid, updating the in-memory store only.
 */
export default function Contributions() {
  const { currentMonthContributions, setContributionStatus, currentMonthStr, members, setContributions } =
    useData()
  const { monthlyAmount } = useSettings()
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const [generating, setGenerating] = useState(false)
  const [generateMessage, setGenerateMessage] = useState('')

  const rows = useMemo(() => {
    const q = query.trim().toLowerCase()
    return currentMonthContributions.filter((row) => {
      const matchesQuery =
        !q ||
        row.member.name.toLowerCase().includes(q) ||
        row.member.mobile.includes(q)
      const matchesFilter = filter === 'all' || row.status === filter
      return matchesQuery && matchesFilter
    })
  }, [currentMonthContributions, query, filter])

  const paidCount = currentMonthContributions.filter(
    (r) => r.status === 'paid',
  ).length
  const unpaidCount = currentMonthContributions.length - paidCount
  const collected = paidCount * monthlyAmount

  const toggle = async (row) => {
    // If no contribution record exists, create one first
    if (!row.contribution) {
      try {
        await contributionApi.generate(currentMonthStr)
        // Refresh contributions from API
        const data = await contributionApi.list({ month: currentMonthStr, limit: 100 })
        setContributions(data.contributions || [])
        // Find the newly created contribution for this member and toggle it
        const newContribution = data.contributions.find(
          (c) => c.memberId === row.member.id || c.memberId === row.member._id
        )
        if (newContribution) {
          await setContributionStatus(newContribution.id, 'paid')
        }
      } catch {
        // Error handled by API client
      }
      return
    }
    const newStatus = row.status === 'paid' ? 'unpaid' : 'paid'
    await setContributionStatus(row.contribution.id, newStatus)
  }

  const handleGenerate = async () => {
    setGenerating(true)
    setGenerateMessage('')
    try {
      const result = await contributionApi.generate(currentMonthStr)
      // Refresh contributions from API
      const data = await contributionApi.list({ month: currentMonthStr, limit: 100 })
      // Update the contributions in DataContext
      setContributions(data.contributions || [])
      // Show success message
      setGenerateMessage(result.message || 'Contributions generated successfully')
      // Clear message after 5 seconds
      setTimeout(() => setGenerateMessage(''), 5000)
    } catch {
      // Error handled by API client
    } finally {
      setGenerating(false)
    }
  }

  // Auto-generate contributions for current month if none exist
  useEffect(() => {
    const hasCurrentMonthContributions = currentMonthContributions.some(
      (row) => row.contribution !== null
    )
    if (!hasCurrentMonthContributions && members.length > 0 && !generating) {
      handleGenerate()
    }
  }, [members.length, currentMonthContributions.length])

  const [year, month] = currentMonthStr.split('-')
  const monthLabel = new Date(`${year}-${month}-01`).toLocaleDateString('en-IN', {
    month: 'long',
    year: 'numeric',
  })

  return (
    <div>
      <PageHeader
        title="Contribution Management"
        description={`Track monthly contributions for ${monthLabel}.`}
      />

      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
        <StatCard
          label="Collected This Month"
          value={formatCurrency(collected)}
          icon={FiDollarSign}
          tone="green"
        />
        <StatCard
          label="Paid Members"
          value={paidCount}
          icon={FiCheck}
          tone="brand"
        />
        <StatCard
          label="Pending Members"
          value={unpaidCount}
          icon={FiX}
          tone="amber"
        />
      </div>

      <div className="mb-6">
        <Button
          icon={FiRefreshCw}
          onClick={handleGenerate}
          disabled={generating}
        >
          {generating ? 'Generating...' : 'Generate Monthly Contributions'}
        </Button>
        <p className="mt-2 text-xs text-slate-500">
          This creates contribution records for all active members for {monthLabel}.
        </p>
        {generateMessage && (
          <div className="mt-3 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">
            {generateMessage}
          </div>
        )}
      </div>

      <Card>
        <CardBody>
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
            <Input
              name="search"
              icon={FiSearch}
              placeholder="Search by name or mobile"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="flex-1"
            />
            <Select
              name="filter"
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
              className="sm:w-44"
              options={[
                { value: 'all', label: 'All' },
                { value: 'paid', label: 'Paid' },
                { value: 'unpaid', label: 'Unpaid' },
              ]}
            />
          </div>
        </CardBody>

        {rows.length === 0 ? (
          <EmptyState title="No members match your filters" />
        ) : (
          <Table>
            <THead>
              <TR>
                <TH>Member Name</TH>
                <TH>Current Month Status</TH>
                <TH>Paid Date</TH>
                <TH className="text-right">Action</TH>
              </TR>
            </THead>
            <TBody>
              {rows.map((row) => (
                <TR key={row.member.id || row.member._id}>
                  <TD>
                    <div className="flex items-center gap-3">
                      <span
                        className="flex h-9 w-9 items-center justify-center rounded-full text-xs font-semibold text-white"
                      style={{ backgroundColor: row.member.avatarColor || '#3563ff' }}
                      >
                        {getInitials(row.member.name)}
                      </span>
                      <div>
                        <p className="font-medium text-slate-800">
                          {row.member.name}
                        </p>
                        <p className="text-xs text-slate-400">
                          {row.member.mobile}
                        </p>
                      </div>
                    </div>
                  </TD>
                  <TD>
                    <Badge>{row.status}</Badge>
                  </TD>
                  <TD>{formatDate(row.contribution?.paymentDate)}</TD>
                  <TD className="text-right">
                    {row.status === 'paid' ? (
                      <Button
                        size="sm"
                        variant="secondary"
                        icon={FiX}
                        onClick={() => toggle(row)}
                      >
                        Mark Unpaid
                      </Button>
                    ) : (
                      <Button
                        size="sm"
                        variant="success"
                        icon={FiCheck}
                        onClick={() => toggle(row)}
                      >
                        Mark as Paid
                      </Button>
                    )}
                  </TD>
                </TR>
              ))}
            </TBody>
          </Table>
        )}
      </Card>
    </div>
  )
}
