// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import {
  FiUsers,
  FiDollarSign,
  FiCreditCard,
  FiTrendingUp,
} from 'react-icons/fi'
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
} from 'recharts'
import StatCard from '../../components/cards/StatCard.jsx'
import Card, { CardHeader, CardBody } from '../../components/ui/Card.jsx'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Badge from '../../components/ui/Badge.jsx'
import { StatCardSkeleton } from '../../components/ui/Skeleton.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import { dashboardApi } from '../../api/dashboardApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Admin landing dashboard: KPIs, charts and recent activity from live API. */
export default function AdminDashboard() {
  const location = useLocation()
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    let active = true
    setLoading(true)
    dashboardApi
      .getAdminStats()
      .then((result) => {
        if (active) {
          setData(result)
          setLoading(false)
        }
      })
      .catch(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [location.pathname])

  const cards = [
    {
      label: 'Active Members',
      value: data?.activeMembers ?? 0,
      icon: FiUsers,
      tone: 'brand',
    },
    {
      label: 'Total Fund Amount',
      value: data ? formatCurrency(data.totalFundsCollected) : '—',
      icon: FiDollarSign,
      tone: 'green',
    },
    {
      label: 'Active Loans',
      value: data?.totalActiveLoans ?? 0,
      icon: FiCreditCard,
      tone: 'amber',
    },
    {
      label: 'Loan Given',
      value: data ? formatCurrency(data.totalActiveLoanPrincipal) : '—',
      icon: FiTrendingUp,
      tone: 'slate',
    },
    {
      label: 'Available Balance',
      value: data ? formatCurrency(data.availableBalance) : '—',
      icon: FiTrendingUp,
      tone: 'slate',
    },
  ]

  return (
    <div>
      <PageHeader
        title="Dashboard"
        description="Overview of your community fund at a glance."
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5">
        {loading
          ? Array.from({ length: 5 }).map((_, i) => <StatCardSkeleton key={i} />)
          : cards.map((c) => <StatCard key={c.label} {...c} />)}
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6">
        <Card>
          <CardHeader
            title="Monthly Collections"
            subtitle="Contributions received over the last 6 months"
          />
          <CardBody>
            {loading ? (
              <div className="flex h-72 items-center justify-center text-sm text-slate-400">Loading chart...</div>
            ) : data?.monthlyCollections?.length ? (
              <div className="h-72 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={data.monthlyCollections} margin={{ top: 8, right: 8, left: -12 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#eef2f7" vertical={false} />
                    <XAxis dataKey="month" tick={{ fontSize: 12, fill: '#94a3b8' }} axisLine={false} tickLine={false} />
                    <YAxis tick={{ fontSize: 12, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={(v) => `${v / 1000}k`} />
                    <Tooltip
                      cursor={{ fill: '#f1f5f9' }}
                      formatter={(v) => [formatCurrency(v), 'Collected']}
                      contentStyle={{ borderRadius: 12, border: '1px solid #e2e8f0', fontSize: 13 }}
                    />
                    <Bar dataKey="amount" fill="#3563ff" radius={[6, 6, 0, 0]} maxBarSize={44} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            ) : (
              <EmptyState title="No contribution data yet" />
            )}
          </CardBody>
        </Card>
      </div>

      <Card className="mt-6">
        <CardHeader
          title="Recent Activity"
          subtitle="Latest fund movements and updates"
        />
        <CardBody className="p-0">
          {loading ? (
            <div className="px-5 py-8 text-center text-sm text-slate-400">Loading activity...</div>
          ) : data?.recentActivity?.length ? (
            <ul className="divide-y divide-slate-100">
              {data.recentActivity.map((item, idx) => (
                <li
                  key={idx}
                  className="flex items-center justify-between gap-4 px-5 py-3.5"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium text-slate-800">
                      {item.title}
                    </p>
                    <p className="truncate text-xs text-slate-500">
                      {item.description}
                    </p>
                  </div>
                  <div className="flex flex-shrink-0 flex-col items-end gap-1">
                    {item.amount != null ? (
                      <span className="text-sm font-semibold text-slate-700">
                        {formatCurrency(item.amount)}
                      </span>
                    ) : (
                      <Badge tone="brand">New</Badge>
                    )}
                    <span className="text-xs text-slate-400">
                      {formatDate(item.date)}
                    </span>
                  </div>
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState title="No recent activity" />
          )}
        </CardBody>
      </Card>
    </div>
  )
}