// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { FiCheckCircle, FiArrowLeft } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import Modal from '../../components/ui/Modal.jsx'
import Button from '../../components/ui/Button.jsx'
import EditMemberForm from '../../components/forms/EditMemberForm.jsx'
import { useData } from '../../hooks/useData.js'

/** Edit member page. Pre-fills the form with existing data and updates via API. */
export default function EditMember() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { getMemberById, updateMember } = useData()
  const [updated, setUpdated] = useState(false)
  const [loading, setLoading] = useState(true)

  const member = getMemberById(id)

  useEffect(() => {
    if (member) setLoading(false)
  }, [member])

  const handleSubmit = async (values) => {
    try {
      await updateMember(id, values)
      setUpdated(true)
    } catch {
      // Error handled by API client
    }
  }

  if (!member && !loading) {
    return (
      <div>
        <Breadcrumb
          items={[
            { label: 'Members', to: '/admin/members' },
            { label: 'Edit Member' },
            { label: 'Not found' },
          ]}
        />
        <PageHeader title="Member not found" />
      </div>
    )
  }

  return (
    <div>
      <Breadcrumb
        items={[
          { label: 'Members', to: '/admin/members' },
          { label: member?.name || 'Edit Member' },
          { label: 'Edit' },
        ]}
      />
      <PageHeader
        title="Edit Member"
        description={`Update details for ${member?.name || '...'}`}
        action={
          <Button variant="secondary" icon={FiArrowLeft} onClick={() => navigate(`/admin/members/${id}`)}>
            Back
          </Button>
        }
      />

      <Card className="max-w-xl">
        <CardBody>
          {loading ? (
            <p className="text-sm text-slate-500">Loading member data...</p>
          ) : (
            <EditMemberForm
              member={member}
              onSubmit={handleSubmit}
              onCancel={() => navigate(`/admin/members/${id}`)}
            />
          )}
        </CardBody>
      </Card>

      <Modal
        open={updated}
        onClose={() => navigate(`/admin/members/${id}`)}
        title="Member Updated"
        size="sm"
        footer={
          <Button onClick={() => navigate(`/admin/members/${id}`)}>
            View Member
          </Button>
        }
      >
        <div className="flex flex-col items-center gap-3 py-2 text-center">
          <span className="flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-green-600">
            <FiCheckCircle className="h-8 w-8" />
          </span>
          <div>
            <p className="text-base font-semibold text-slate-800">
              {member?.name} updated successfully
            </p>
          </div>
        </div>
      </Modal>
    </div>
  )
}