// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiCheck, FiArrowLeft } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import Button from '../../components/ui/Button.jsx'
import Input from '../../components/ui/Input.jsx'
import Select from '../../components/ui/Select.jsx'
import Modal from '../../components/ui/Modal.jsx'
import { useData } from '../../hooks/useData.js'
import { loanApi } from '../../api/loanApi.js'
import { formatCurrency } from '../../utils/format.js'

/** Issue a new loan to a member. */
export default function IssueLoan() {
  const navigate = useNavigate()
  const { members } = useData()
  const [formData, setFormData] = useState({
    memberId: '',
    amount: '',
    issueDate: new Date().toISOString().slice(0, 10),
    dueDate: '',
    notes: '',
  })
  const [availableFunds, setAvailableFunds] = useState(0)
  const [errors, setErrors] = useState({})
  const [submitting, setSubmitting] = useState(false)
  const [success, setSuccess] = useState(false)

  const activeMembers = members.filter((m) => m.status === 'active')

  useEffect(() => {
    loanApi.getAvailableFunds().then((res) => setAvailableFunds(res.availableFunds))
  }, [])

  const validate = () => {
    const next = {}
    if (!formData.memberId) next.memberId = 'Select a member'
    if (!formData.amount || Number(formData.amount) <= 0) next.amount = 'Enter a valid amount'
    if (!formData.issueDate) next.issueDate = 'Issue date is required'
    if (formData.dueDate && formData.dueDate <= formData.issueDate) next.dueDate = 'Due date must be after issue date'
    if (Number(formData.amount) > availableFunds) next.amount = `Loan amount cannot exceed available balance (₹${availableFunds.toLocaleString('en-IN')})`
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!validate()) return
    setSubmitting(true)
    try {
      // Build payload — only include dueDate if provided
      const payload = { ...formData }
      if (!payload.dueDate) delete payload.dueDate
      await loanApi.create(payload)
      setSuccess(true)
      setTimeout(() => navigate('/admin/loans'), 1500)
    } catch (err) {
      setErrors({ submit: err.message || 'Failed to create loan' })
    } finally {
      setSubmitting(false)
    }
  }

  if (success) {
    return (
      <Modal
        open={success}
        onClose={() => navigate('/admin/loans')}
        title="Loan Issued Successfully"
        footer={[
          <Button key="close" variant="primary" onClick={() => navigate('/admin/loans')}>
            View Loans
          </Button>,
        ]}
      >
        <div className="space-y-3 text-center">
          <p className="text-lg font-semibold text-green-600">✓ Loan created successfully</p>
          <p className="text-slate-600">
            Loan of ₹{Number(formData.amount).toLocaleString('en-IN')} has been issued to the member.
          </p>
        </div>
      </Modal>
    )
  }

  return (
    <div>
      <Breadcrumb
        items={[
          { label: 'Loans', to: '/admin/loans' },
          { label: 'Issue Loan' },
        ]}
      />
      <PageHeader
        title="Issue New Loan"
        description="Create a new loan for a member"
        action={
          <Button variant="secondary" icon={FiArrowLeft} onClick={() => navigate('/admin/loans')}>
            Back
          </Button>
        }
      />

      <Card className="max-w-xl">
        <CardBody>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Select
              label="Member"
              name="memberId"
              value={formData.memberId}
              onChange={(e) => setFormData((prev) => ({ ...prev, memberId: e.target.value }))}
              error={errors.memberId}
              options={[
                { value: '', label: 'Select a member' },
                ...activeMembers.map((m) => ({ value: m.id, label: `${m.name} (${m.email})` })),
              ]}
            />

            <div className="rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-700">
              Available funds: ₹{availableFunds.toLocaleString('en-IN')}
            </div>

            <Input
              label="Loan Amount (₹)"
              name="amount"
              type="number"
              icon={FiCheck}
              placeholder="Enter loan amount"
              value={formData.amount}
              onChange={(e) => setFormData((prev) => ({ ...prev, amount: e.target.value }))}
              error={errors.amount}
            />

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Input
                label="Issue Date"
                name="issueDate"
                type="date"
                value={formData.issueDate}
                onChange={(e) => setFormData((prev) => ({ ...prev, issueDate: e.target.value }))}
                error={errors.issueDate}
              />
              <Input
                label="Due Date (optional)"
                name="dueDate"
                type="date"
                min={formData.issueDate}
                value={formData.dueDate}
                onChange={(e) => setFormData((prev) => ({ ...prev, dueDate: e.target.value }))}
              />
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Notes (optional)</label>
              <textarea
                value={formData.notes}
                onChange={(e) => setFormData((prev) => ({ ...prev, notes: e.target.value }))}
                rows={3}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Any additional notes..."
              />
            </div>

            {errors.submit && (
              <div className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{errors.submit}</div>
            )}

            <div className="flex justify-end gap-3 pt-2">
              <Button type="button" variant="secondary" onClick={() => navigate('/admin/loans')}>
                Cancel
              </Button>
              <Button type="submit" disabled={submitting}>
                {submitting ? 'Issuing...' : 'Issue Loan'}
              </Button>
            </div>
          </form>
        </CardBody>
      </Card>
    </div>
  )
}