// Generated by GitHub Copilot
import { useState, useEffect, useMemo, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { FiBookOpen, FiTrendingDown, FiUsers } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Select from '../../components/ui/Select.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import { useData } from '../../hooks/useData.js'
import { loanApi } from '../../api/loanApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'

/**
 * Loan passbook. Shows all loans for a selected member with repayment history.
 * A selector lets the admin switch between members.
 */
export default function LoanPassbook() {
  const { loanId } = useParams()
  const navigate = useNavigate()
  const { members, getLoansByMember, refetchLoans } = useData()
  const [memberLoans, setMemberLoans] = useState([])
  const [loading, setLoading] = useState(false)

  const [selectedMemberId, setSelectedMemberId] = useState('')

  // Fetch loans for selected member from API
  const fetchMemberLoans = useCallback(async (memberId) => {
    if (!memberId) {
      setMemberLoans([])
      return
    }
    setLoading(true)
    try {
      const data = await loanApi.list({ memberId, limit: 100 })
      setMemberLoans(data.loans || [])
    } catch (err) {
      console.error('Failed to fetch member loans:', err)
      setMemberLoans([])
    } finally {
      setLoading(false)
    }
  }, [])

  // Fetch loans when member selection changes
  useEffect(() => {
    if (selectedMemberId) {
      fetchMemberLoans(selectedMemberId)
    } else {
      setMemberLoans([])
    }
  }, [selectedMemberId, fetchMemberLoans])

  // If loanId is provided in URL, find the member and select them
  useEffect(() => {
    if (loanId && !selectedMemberId) {
      // Fetch the specific loan to get the memberId
      loanApi.getById(loanId).then((res) => {
        if (res.loan) {
          setSelectedMemberId(res.loan.memberId)
        }
      }).catch(() => {
        // If loan not found, just leave selection empty
      })
    }
  }, [loanId, selectedMemberId])

  // Get the selected member details
  const selectedMember = members.find((m) => m.id === selectedMemberId)

  const handleMemberChange = (value) => {
    setSelectedMemberId(value)
    // No navigation needed - just update the view
  }

  // Calculate totals for all loans of the selected member
  const totalBorrowed = memberLoans.reduce((sum, l) => sum + Number(l.amount || 0), 0)
  const totalRemaining = memberLoans.reduce((sum, l) => sum + Number(l.remaining || 0), 0)
  const totalRepaid = totalBorrowed - totalRemaining

  return (
    <div>
      <Breadcrumb items={[{ label: 'Loans', to: '/admin/loans' }, { label: 'Passbook' }]} />

      <PageHeader
        title="Loan Passbook"
        description="Select a member to view their loan passbook."
        action={
          <Select
            name="member"
            value={selectedMemberId}
            onChange={(e) => handleMemberChange(e.target.value)}
            className="w-64"
            options={[
              { value: '', label: 'Select a member...' },
              ...members.map((m) => ({
                value: m.id,
                label: `${m.name} (${m.email})`,
              })),
            ]}
          />
        }
      />

      {!selectedMemberId ? (
        <Card>
          <EmptyState
            icon={FiUsers}
            title="No member selected"
            description="Choose a member to view their loan passbook."
          />
        </Card>
      ) : memberLoans.length === 0 ? (
        <Card>
          <EmptyState
            icon={FiBookOpen}
            title="No loans found"
            description={`${selectedMember?.name || 'This member'} has not taken any loans yet.`}
          />
        </Card>
      ) : (
        <div className="space-y-6">
          {/* Member Info Card */}
          <Card>
            <CardHeader title={`${selectedMember?.name || 'Member'}'s Loans`} subtitle={`${memberLoans.length} loan(s) found`} />
            <CardBody>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                <div>
                  <p className="text-xs text-slate-500">Total Borrowed</p>
                  <p className="mt-1 text-lg font-semibold text-slate-800">{formatCurrency(totalBorrowed)}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500">Total Repaid</p>
                  <p className="mt-1 text-lg font-semibold text-green-600">{formatCurrency(totalRepaid)}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500">Remaining Balance</p>
                  <p className="mt-1 text-lg font-semibold text-amber-600">{formatCurrency(totalRemaining)}</p>
                </div>
              </div>
            </CardBody>
          </Card>

          {/* Loans List */}
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            {memberLoans.map((loan) => (
              <Card key={loan.id} className="cursor-pointer hover:border-brand-300" onClick={() => navigate(`/admin/loans/${loan.id}`)}>
                <CardBody>
                  <div className="mb-3 flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium text-slate-800">Loan #{loan.id.slice(-6)}</p>
                      <p className="text-xs text-slate-500">Issued: {formatDate(loan.issueDate)}</p>
                    </div>
                    <span className={`inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium ${
                      loan.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-slate-100 text-slate-800'
                    }`}>
                      {loan.status}
                    </span>
                  </div>
                  
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-slate-600">Loan Amount</span>
                      <span className="font-medium text-slate-800">{formatCurrency(loan.amount)}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-slate-600">Remaining</span>
                      <span className="font-medium text-amber-600">{formatCurrency(loan.remaining)}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-slate-600">Repaid</span>
                      <span className="font-medium text-green-600">{formatCurrency(loan.amount - loan.remaining)}</span>
                    </div>
                    {loan.dueDate && (
                      <div className="flex justify-between text-sm">
                        <span className="text-slate-600">Due Date</span>
                        <span className="font-medium text-slate-800">{formatDate(loan.dueDate)}</span>
                      </div>
                    )}
                  </div>

                  {loan.repayments && loan.repayments.length > 0 && (
                    <div className="mt-4 border-t border-slate-100 pt-3">
                      <p className="mb-2 text-xs font-medium text-slate-700">
                        Recent Payments ({loan.repayments.length})
                      </p>
                      <div className="space-y-1.5">
                        {loan.repayments.slice(-3).map((payment, idx) => (
                          <div key={idx} className="flex justify-between text-xs">
                            <span className="text-slate-600">{formatDate(payment.paymentDate)}</span>
                            <span className="font-medium text-slate-800">{formatCurrency(payment.amount)}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </CardBody>
              </Card>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
