// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiPlus, FiSearch, FiCreditCard, FiCheck, FiX, FiClock, FiChevronUp, FiChevronDown } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Button from '../../components/ui/Button.jsx'
import Input from '../../components/ui/Input.jsx'
import Select from '../../components/ui/Select.jsx'
import Badge from '../../components/ui/Badge.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import Modal from '../../components/ui/Modal.jsx'
import { useData } from '../../hooks/useData.js'
import { loanApi } from '../../api/loanApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Admin loans list with search, status filter and pagination. */
export default function Loans() {
  const navigate = useNavigate()
  const [loans, setLoans] = useState([])
  const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)

  // Loan requests
  const [loanRequests, setLoanRequests] = useState([])
  const [loanRequestsLoading, setLoanRequestsLoading] = useState(false)
  const [availableFunds, setAvailableFunds] = useState(null)
  const [approveModalOpen, setApproveModalOpen] = useState(false)
  const [rejectModalOpen, setRejectModalOpen] = useState(false)
  const [selectedRequest, setSelectedRequest] = useState(null)
  const [adminNotes, setAdminNotes] = useState('')
  const [editedAmount, setEditedAmount] = useState('')
  const [editedMonth, setEditedMonth] = useState('')
  const [editedReturn, setEditedReturn] = useState('')
  const [actionLoading, setActionLoading] = useState(false)
  const [successMessage, setSuccessMessage] = useState('')

  const fetchLoanRequests = async () => {
    setLoanRequestsLoading(true)
    try {
      const data = await loanApi.getLoanRequests()
      setLoanRequests(data.requests || [])
      setAvailableFunds(data.availableFunds ?? null)
    } catch {
      // silently fail
    } finally {
      setLoanRequestsLoading(false)
    }
  }

  const handleReorder = async (requestId, direction) => {
    try {
      const data = await loanApi.reorderLoanRequest(requestId, direction)
      setLoanRequests(data.requests || [])
      setAvailableFunds(data.availableFunds ?? null)
    } catch (err) {
      console.error('Failed to reorder loan request:', err)
    }
  }

  useEffect(() => {
    let active = true
    setLoading(true)
    loanApi
      .list({ status: status === 'all' ? '' : status, page, limit: 10 })
      .then((data) => {
        if (active) {
          setLoans(data.loans || [])
          setTotalPages(data.pagination.totalPages || 1)
          setLoading(false)
        }
      })
      .catch(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [status, page])

  const refreshLoans = async () => {
    try {
      const data = await loanApi.list({ status: status === 'all' ? '' : status, page, limit: 10 })
      setLoans(data.loans || [])
      setTotalPages(data.pagination.totalPages || 1)
    } catch {
      // silently fail
    }
  }

  useEffect(() => {
    fetchLoanRequests()
  }, [])

  const filtered = loans.filter((loan) => {
    if (!query.trim()) return true
    const q = query.trim().toLowerCase()
    return (
      loan.memberName.toLowerCase().includes(q) ||
      loan.memberEmail.toLowerCase().includes(q) ||
      loan.memberMobile.includes(q)
    )
  })

  const getLoanStatusBadge = (loanStatus) => {
    const variants = {
      active: 'brand',
      paid: 'green',
      defaulted: 'red',
    }
    return <Badge tone={variants[loanStatus] || 'slate'}>{loanStatus}</Badge>
  }

  const getRequestStatusTone = (status) => {
    const variants = {
      pending: 'amber',
      approved: 'green',
      rejected: 'red',
      withdrawn: 'slate',
    }
    return variants[status] || 'slate'
  }

  const formatMonth = (ym) => {
    if (!ym) return '—'
    const [y, m] = ym.split('-')
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    return `${monthNames[parseInt(m) - 1]} ${y}`
  }

  const openApproveModal = (req) => {
    setSelectedRequest(req)
    setEditedAmount(req.amount.toString())
    setEditedMonth(req.monthRequired)
    setEditedReturn(req.expectedReturn || '')
    setAdminNotes('')
    setApproveModalOpen(true)
  }

  const openRejectModal = (req) => {
    setSelectedRequest(req)
    setAdminNotes('')
    setRejectModalOpen(true)
  }

  const handleApprove = async () => {
    if (!selectedRequest) return
    setActionLoading(true)
    try {
      await loanApi.approveLoanRequest(selectedRequest.id, {
        amount: Number(editedAmount),
        monthRequired: editedMonth,
        expectedReturn: editedReturn || null,
        notes: adminNotes,
      })
      setApproveModalOpen(false)
      setSuccessMessage('Loan request approved successfully.')
      setTimeout(() => setSuccessMessage(''), 5000)
      await Promise.all([fetchLoanRequests(), refreshLoans()])
    } catch (err) {
      console.error('Failed to approve loan request:', err)
    } finally {
      setActionLoading(false)
    }
  }

  const handleReject = async () => {
    if (!selectedRequest) return
    setActionLoading(true)
    try {
      await loanApi.rejectLoanRequest(selectedRequest.id, {
        notes: adminNotes,
      })
      setRejectModalOpen(false)
      setSuccessMessage('Loan request rejected.')
      setTimeout(() => setSuccessMessage(''), 5000)
      await fetchLoanRequests()
    } catch (err) {
      console.error('Failed to reject loan request:', err)
    } finally {
      setActionLoading(false)
    }
  }

  return (
    <div>
      <PageHeader
        title="Loans"
        description={`${loans.length} loans in the system`}
        action={
          <Button icon={FiPlus} onClick={() => navigate('/admin/loans/create')}>
            Issue Loan
          </Button>
        }
      />

      <Card className="mb-6">
        <CardBody>
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
            <Input
              name="search"
              icon={FiSearch}
              placeholder="Search by member name, email or mobile"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="flex-1"
            />
            <Select
              name="status"
              value={status}
              onChange={(e) => setStatus(e.target.value)}
              className="sm:w-44"
              options={[
                { value: 'all', label: 'All statuses' },
                { value: 'active', label: 'Active' },
                { value: 'paid', label: 'Paid' },
                { value: 'defaulted', label: 'Defaulted' },
              ]}
            />
          </div>
        </CardBody>
      </Card>

      <Card>
        <CardBody>
          {loading ? (
            <p className="text-center text-slate-500">Loading loans...</p>
          ) : filtered.length === 0 ? (
            <EmptyState
              icon={FiCreditCard}
              title="No loans found"
              description="Try adjusting your search or filter."
            />
          ) : (
            <>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-slate-200">
                      <th className="px-4 py-3 text-left font-semibold text-slate-700">Member</th>
                      <th className="px-4 py-3 text-right font-semibold text-slate-700">Amount</th>
                      <th className="px-4 py-3 text-right font-semibold text-slate-700">Remaining</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-700">Issue Date</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-700">Due Date</th>
                      <th className="px-4 py-3 text-center font-semibold text-slate-700">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map((loan) => (
                      <tr
                        key={loan.id}
                        className="cursor-pointer border-b border-slate-100 hover:bg-slate-50"
                        onClick={() => navigate(`/admin/loans/${loan.id}`)}
                      >
                        <td className="px-4 py-3">
                          <div>
                            <p className="font-medium text-slate-800">{loan.memberName}</p>
                            <p className="text-xs text-slate-400">{loan.memberEmail}</p>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-right text-slate-600">{formatCurrency(loan.amount)}</td>
                        <td className="px-4 py-3 text-right font-semibold text-slate-800">{formatCurrency(loan.remaining)}</td>
                        <td className="px-4 py-3 text-slate-600">{formatDate(loan.issueDate)}</td>
                        <td className="px-4 py-3 text-slate-600">{loan.dueDate ? formatDate(loan.dueDate) : '-'}</td>
                        <td className="px-4 py-3 text-center">{getLoanStatusBadge(loan.status)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {totalPages > 1 && (
                <div className="mt-4 flex items-center justify-between">
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                    disabled={page === 1}
                  >
                    Previous
                  </Button>
                  <span className="text-sm text-slate-600">
                    Page {page} of {totalPages}
                  </span>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                    disabled={page === totalPages}
                  >
                    Next
                  </Button>
                </div>
              )}
            </>
          )}
        </CardBody>
      </Card>

      {/* Loan Requests */}
      <Card className="mt-6">
        <CardBody>
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h3 className="text-lg font-semibold text-slate-800">Loan Requests</h3>
              <p className="text-sm text-slate-500">Review and manage member loan applications</p>
            </div>
            <div className="rounded-lg border border-green-100 bg-green-50 px-4 py-2 text-right">
              <p className="text-xs text-green-700">Available funds</p>
              <p className="text-base font-semibold text-green-800">
                {availableFunds === null ? '—' : formatCurrency(availableFunds)}
              </p>
            </div>
          </div>
          {loanRequestsLoading ? (
            <p className="py-8 text-center text-sm text-slate-500">Loading requests...</p>
          ) : loanRequests.length === 0 ? (
            <p className="py-8 text-center text-sm text-slate-500">No loan requests found</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-slate-200">
                    <th className="px-4 py-3 text-left font-semibold text-slate-700">Queue</th>
                    <th className="px-4 py-3 text-left font-semibold text-slate-700">Member</th>
                    <th className="px-4 py-3 text-right font-semibold text-slate-700">Amount</th>
                    <th className="px-4 py-3 text-left font-semibold text-slate-700">Month Required</th>
                    <th className="px-4 py-3 text-left font-semibold text-slate-700">Expected Return</th>
                    <th className="px-4 py-3 text-left font-semibold text-slate-700">Purpose</th>
                    <th className="px-4 py-3 text-center font-semibold text-slate-700">Status</th>
                    <th className="px-4 py-3 text-center font-semibold text-slate-700">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {loanRequests.map((req) => (
                    <tr key={req.id} className="border-b border-slate-100 hover:bg-slate-50">
                      <td className="px-4 py-3">
                        {req.status === 'pending' && req.position ? (
                          <div className="flex items-center gap-2">
                            <span className="font-semibold text-slate-800">#{req.position}</span>
                            <div className="flex flex-col">
                              <button
                                type="button"
                                title="Move up"
                                onClick={() => handleReorder(req.id, 'up')}
                                className="text-slate-400 hover:text-slate-700"
                              >
                                <FiChevronUp className="h-3.5 w-3.5" />
                              </button>
                              <button
                                type="button"
                                title="Move down"
                                onClick={() => handleReorder(req.id, 'down')}
                                className="text-slate-400 hover:text-slate-700"
                              >
                                <FiChevronDown className="h-3.5 w-3.5" />
                              </button>
                            </div>
                          </div>
                        ) : (
                          <span className="text-xs text-slate-400">—</span>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        <p className="font-medium text-slate-800">{req.memberName}</p>
                      </td>
                      <td className="px-4 py-3 text-right text-slate-600">{formatCurrency(req.amount)}</td>
                      <td className="px-4 py-3 text-slate-600">{formatMonth(req.monthRequired)}</td>
                      <td className="px-4 py-3 text-slate-600">{req.expectedReturn ? formatDate(req.expectedReturn) : '—'}</td>
                      <td className="px-4 py-3 text-slate-600 capitalize">{req.purpose}</td>
                      <td className="px-4 py-3 text-center">
                        <Badge tone={getRequestStatusTone(req.status)}>{req.status}</Badge>
                        {req.status === 'pending' && req.eligible === false && (
                          <span className="mt-1 flex items-center justify-center gap-1 text-xs text-amber-600">
                            <FiClock className="h-3 w-3" /> Waiting for funds
                          </span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-center">
                        {req.status === 'pending' ? (
                          <div className="flex items-center justify-center gap-2">
                            <button
                              type="button"
                              onClick={() => openApproveModal(req)}
                              className="inline-flex items-center gap-1 rounded-md border border-green-200 bg-green-50 px-2.5 py-1 text-xs font-medium text-green-700 transition-colors hover:bg-green-100"
                            >
                              <FiCheck className="h-3 w-3" /> Approve
                            </button>
                            <button
                              type="button"
                              onClick={() => openRejectModal(req)}
                              className="inline-flex items-center gap-1 rounded-md border border-red-200 bg-red-50 px-2.5 py-1 text-xs font-medium text-red-700 transition-colors hover:bg-red-100"
                            >
                              <FiX className="h-3 w-3" /> Reject
                            </button>
                          </div>
                        ) : (
                          <span className="text-xs text-slate-400">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardBody>
      </Card>

      {/* Approve Modal */}
      <Modal
        open={approveModalOpen}
        onClose={() => setApproveModalOpen(false)}
        title="Approve Loan Request"
        footer={
          <>
            <Button variant="secondary" onClick={() => setApproveModalOpen(false)} disabled={actionLoading}>
              Cancel
            </Button>
            <Button onClick={handleApprove} disabled={actionLoading}>
              {actionLoading ? 'Approving…' : 'Approve'}
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <div className="flex items-center justify-between rounded-lg border border-green-100 bg-green-50 px-4 py-2">
            <span className="text-sm text-green-700">Available funds</span>
            <span className="text-sm font-semibold text-green-800">
              {availableFunds === null ? '—' : formatCurrency(availableFunds)}
            </span>
          </div>
          <Input
            label="Loan Amount (₹)"
            name="amount"
            type="number"
            value={editedAmount}
            onChange={(e) => setEditedAmount(e.target.value)}
          />
          {availableFunds !== null && Number(editedAmount) > availableFunds && (
            <p className="flex items-center gap-1 text-xs text-amber-600">
              <FiClock className="h-3 w-3" /> Amount exceeds available funds. Approval will be blocked until funds are sufficient.
            </p>
          )}
          <Input
            label="Month Required"
            name="monthRequired"
            type="month"
            value={editedMonth}
            onChange={(e) => setEditedMonth(e.target.value)}
          />
          <Input
            label="Expected Return Date"
            name="expectedReturn"
            type="date"
            value={editedReturn}
            onChange={(e) => setEditedReturn(e.target.value)}
          />
          <div>
            <label className="mb-1.5 block text-sm font-medium text-slate-700">Admin Notes</label>
            <textarea
              rows={3}
              className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
              placeholder="Add any notes for the member"
              value={adminNotes}
              onChange={(e) => setAdminNotes(e.target.value)}
            />
          </div>
        </div>
      </Modal>

      {/* Reject Modal */}
      <Modal
        open={rejectModalOpen}
        onClose={() => setRejectModalOpen(false)}
        title="Reject Loan Request"
        footer={
          <>
            <Button variant="secondary" onClick={() => setRejectModalOpen(false)} disabled={actionLoading}>
              Cancel
            </Button>
            <Button variant="danger" onClick={handleReject} disabled={actionLoading}>
              {actionLoading ? 'Rejecting…' : 'Reject'}
            </Button>
          </>
        }
      >
        <div>
          <label className="mb-1.5 block text-sm font-medium text-slate-700">Reason for Rejection (Notes)</label>
          <textarea
            rows={4}
            className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
            placeholder="Please provide a reason for rejecting this loan request"
            value={adminNotes}
            onChange={(e) => setAdminNotes(e.target.value)}
          />
        </div>
      </Modal>
    </div>
  )
}
