// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { FiArrowLeft, FiCheck, FiDollarSign, FiMail, FiBell } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import Button from '../../components/ui/Button.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Modal from '../../components/ui/Modal.jsx'
import { useData } from '../../hooks/useData.js'
import { loanApi } from '../../api/loanApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Loan detail view with repayment history and record repayment option. */
export default function LoanDetails() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [loan, setLoan] = useState(null)
  const [loading, setLoading] = useState(true)
  const [repayModalOpen, setRepayModalOpen] = useState(false)
  const [repayAmount, setRepayAmount] = useState('')
  const [repayDate, setRepayDate] = useState(new Date().toISOString().slice(0, 10))
  const [repayNotes, setRepayNotes] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [message, setMessage] = useState('')
  const [closing, setClosing] = useState(false)

  useEffect(() => {
    let active = true
    setLoading(true)
    loanApi
      .getById(id)
      .then((res) => {
        if (active) {
          setLoan(res.loan)
          setLoading(false)
        }
      })
      .catch(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [id])

  const handleRepay = async (e) => {
    e.preventDefault()
    setSubmitting(true)
    setMessage('')
    try {
      const result = await loanApi.repay(id, {
        amount: Number(repayAmount),
        date: repayDate,
        notes: repayNotes,
      })
      setLoan(result.loan)
      setRepayModalOpen(false)
      setRepayAmount('')
      setRepayNotes('')
      setMessage('Repayment recorded successfully')
      setTimeout(() => setMessage(''), 3000)
    } catch {
      setMessage('Failed to record repayment')
    } finally {
      setSubmitting(false)
    }
  }

  const handleCloseLoan = async () => {
    if (!window.confirm('Are you sure you want to close this loan?')) return
    setClosing(true)
    setMessage('')
    try {
      const result = await loanApi.close(id)
      setLoan(result.loan)
      setMessage('Loan closed successfully')
      setTimeout(() => setMessage(''), 3000)
    } catch {
      setMessage('Failed to close loan')
    } finally {
      setClosing(false)
    }
  }

  const handleNotify = (type) => {
    setMessage(`${type === 'email' ? 'Email' : 'App'} notification sent successfully`)
    setTimeout(() => setMessage(''), 3000)
  }

  if (loading) {
    return (
      <div>
        <Breadcrumb items={[{ label: 'Loans', to: '/admin/loans' }, { label: 'Loading...' }]} />
        <PageHeader title="Loading..." />
      </div>
    )
  }

  if (!loan) {
    return (
      <div>
        <Breadcrumb items={[{ label: 'Loans', to: '/admin/loans' }, { label: 'Not found' }]} />
        <PageHeader title="Loan not found" />
      </div>
    )
  }

  const isFullyPaid = loan.remaining === 0
  const progressPercent = loan.amount > 0 ? ((loan.amount - loan.remaining) / loan.amount) * 100 : 0

  return (
    <div>
      <Breadcrumb
        items={[
          { label: 'Loans', to: '/admin/loans' },
          { label: loan.memberName },
        ]}
      />

      <PageHeader
        title="Loan Details"
        description={`Loan for ${loan.memberName}`}
        action={
          <Button variant="secondary" icon={FiArrowLeft} onClick={() => navigate('/admin/loans')}>
            Back
          </Button>
        }
      />

      {message && (
        <div className="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{message}</div>
      )}

      {/* Loan Summary */}
      <Card className="mb-6">
        <CardBody>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <p className="text-sm text-slate-400">Member</p>
              <p className="font-semibold text-slate-800">{loan.memberName}</p>
              <p className="text-xs text-slate-500">{loan.memberEmail}</p>
            </div>
            <div>
              <p className="text-sm text-slate-400">Loan Amount</p>
              <p className="font-semibold text-slate-800">{formatCurrency(loan.amount)}</p>
            </div>
            <div>
              <p className="text-sm text-slate-400">Remaining Balance</p>
              <p className="font-semibold text-slate-800">{formatCurrency(loan.remaining)}</p>
            </div>
            <div>
              <p className="text-sm text-slate-400">Status</p>
              <Badge tone={isFullyPaid ? 'green' : loan.status === 'active' ? 'brand' : 'red'}>
                {loan.status}
              </Badge>
            </div>
          </div>

          {/* Progress Bar */}
          <div className="mt-4">
            <div className="flex items-center justify-between text-sm">
              <span className="text-slate-600">Repayment Progress</span>
              <span className="font-semibold text-slate-800">{progressPercent.toFixed(1)}%</span>
            </div>
            <div className="mt-2 h-3 w-full rounded-full bg-slate-200">
              <div
                className="h-3 rounded-full bg-brand-500 transition-all"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div>
              <p className="text-sm text-slate-400">Issue Date</p>
              <p className="text-sm font-medium text-slate-800">{formatDate(loan.issueDate)}</p>
            </div>
            {loan.dueDate && (
              <div>
                <p className="text-sm text-slate-400">Due Date</p>
                <p className="text-sm font-medium text-slate-800">{formatDate(loan.dueDate)}</p>
              </div>
            )}
          </div>

          {loan.notes && (
            <div className="mt-4">
              <p className="text-sm text-slate-400">Notes</p>
              <p className="text-sm text-slate-800">{loan.notes}</p>
            </div>
          )}
        </CardBody>
      </Card>

      {/* Repayment History */}
      <Card className="mb-6">
        <CardBody>
          <h3 className="mb-4 text-base font-semibold text-slate-800">Repayment History</h3>
          {loan.repayments.length === 0 ? (
            <p className="text-sm text-slate-500">No repayments yet.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-slate-200">
                    <th className="pb-2 text-left font-semibold text-slate-700">Date</th>
                    <th className="pb-2 text-right font-semibold text-slate-700">Amount</th>
                    <th className="pb-2 text-left font-semibold text-slate-700">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {loan.repayments.map((repayment, idx) => (
                    <tr key={idx} className="border-b border-slate-100">
                      <td className="py-2 text-slate-800">{formatDate(repayment.date)}</td>
                      <td className="py-2 text-right font-semibold text-green-600">
                        {formatCurrency(repayment.amount)}
                      </td>
                      <td className="py-2 text-slate-600">{repayment.notes || '-'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardBody>
      </Card>

      {/* Action Buttons */}
      {!isFullyPaid && (
        <Card>
          <CardBody>
            <Button icon={FiDollarSign} onClick={() => setRepayModalOpen(true)}>
              Record Repayment
            </Button>
          </CardBody>
        </Card>
      )}

      {isFullyPaid && loan.status !== 'paid' && (
        <Card>
          <CardBody>
            <div className="flex flex-wrap gap-3">
              <Button icon={FiCheck} onClick={handleCloseLoan} disabled={closing}>
                {closing ? 'Closing...' : 'Close Loan'}
              </Button>
              <Button variant="secondary" icon={FiMail} onClick={() => handleNotify('email')}>
                Send Email Notification
              </Button>
              <Button variant="secondary" icon={FiBell} onClick={() => handleNotify('app')}>
                Send App Notification
              </Button>
            </div>
          </CardBody>
        </Card>
      )}

      {loan.status === 'paid' && loan.closedAt && (
        <Card>
          <CardBody>
            <div className="rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">
              Loan closed on {formatDate(loan.closedAt)}
            </div>
          </CardBody>
        </Card>
      )}

      {/* Repayment Modal */}
      <Modal
        open={repayModalOpen}
        onClose={() => !submitting && setRepayModalOpen(false)}
        title="Record Repayment"
        footer={
          <>
            <Button variant="secondary" onClick={() => setRepayModalOpen(false)} disabled={submitting}>
              Cancel
            </Button>
            <Button onClick={handleRepay} disabled={submitting}>
              {submitting ? 'Saving...' : 'Save Repayment'}
            </Button>
          </>
        }
      >
        <form onSubmit={handleRepay} className="space-y-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-slate-700">Repayment Amount (₹)</label>
            <input
              type="number"
              step="0.01"
              max={loan.remaining}
              value={repayAmount}
              onChange={(e) => setRepayAmount(e.target.value)}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              required
            />
            <p className="mt-1 text-xs text-slate-500">Maximum: {formatCurrency(loan.remaining)}</p>
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-slate-700">Repayment Date</label>
            <input
              type="date"
              value={repayDate}
              onChange={(e) => setRepayDate(e.target.value)}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              required
            />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-slate-700">Notes (optional)</label>
            <textarea
              value={repayNotes}
              onChange={(e) => setRepayNotes(e.target.value)}
              rows={3}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
            />
          </div>
        </form>
      </Modal>
    </div>
  )
}