// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiPlus, FiSearch, FiCreditCard } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Button from '../../components/ui/Button.jsx'
import Input from '../../components/ui/Input.jsx'
import Select from '../../components/ui/Select.jsx'
import Badge from '../../components/ui/Badge.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import { useData } from '../../hooks/useData.js'
import { loanApi } from '../../api/loanApi.js'
import { formatCurrency, formatDate } from '../../utils/format.js'

/** Admin loans list with search, status filter and pagination. */
export default function Loans() {
  const navigate = useNavigate()
  const [loans, setLoans] = useState([])
  const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)

  useEffect(() => {
    let active = true
    setLoading(true)
    loanApi
      .list({ status: status === 'all' ? '' : status, page, limit: 10 })
      .then((data) => {
        if (active) {
          setLoans(data.loans || [])
          setTotalPages(data.pagination.totalPages || 1)
          setLoading(false)
        }
      })
      .catch(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [status, page])

  const filtered = loans.filter((loan) => {
    if (!query.trim()) return true
    const q = query.trim().toLowerCase()
    return (
      loan.memberName.toLowerCase().includes(q) ||
      loan.memberEmail.toLowerCase().includes(q) ||
      loan.memberMobile.includes(q)
    )
  })

  const getStatusBadge = (loanStatus) => {
    const variants = {
      active: 'brand',
      paid: 'green',
      defaulted: 'red',
    }
    return <Badge tone={variants[loanStatus] || 'slate'}>{loanStatus}</Badge>
  }

  return (
    <div>
      <PageHeader
        title="Loans"
        description={`${loans.length} loans in the system`}
        action={
          <Button icon={FiPlus} onClick={() => navigate('/admin/loans/create')}>
            Issue Loan
          </Button>
        }
      />

      <Card className="mb-6">
        <CardBody>
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
            <Input
              name="search"
              icon={FiSearch}
              placeholder="Search by member name, email or mobile"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="flex-1"
            />
            <Select
              name="status"
              value={status}
              onChange={(e) => setStatus(e.target.value)}
              className="sm:w-44"
              options={[
                { value: 'all', label: 'All statuses' },
                { value: 'active', label: 'Active' },
                { value: 'paid', label: 'Paid' },
                { value: 'defaulted', label: 'Defaulted' },
              ]}
            />
          </div>
        </CardBody>
      </Card>

      <Card>
        <CardBody>
          {loading ? (
            <p className="text-center text-slate-500">Loading loans...</p>
          ) : filtered.length === 0 ? (
            <EmptyState
              icon={FiCreditCard}
              title="No loans found"
              description="Try adjusting your search or filter."
            />
          ) : (
            <>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-slate-200">
                      <th className="pb-2 text-left font-semibold text-slate-700">Member</th>
                      <th className="pb-2 text-right font-semibold text-slate-700">Amount</th>
                      <th className="pb-2 text-right font-semibold text-slate-700">Remaining</th>
                      <th className="pb-2 text-left font-semibold text-slate-700">Issue Date</th>
                      <th className="pb-2 text-left font-semibold text-slate-700">Due Date</th>
                      <th className="pb-2 text-center font-semibold text-slate-700">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map((loan) => (
                      <tr
                        key={loan.id}
                        className="cursor-pointer border-b border-slate-100 hover:bg-slate-50"
                        onClick={() => navigate(`/admin/loans/${loan.id}`)}
                      >
                        <td className="py-3">
                          <div>
                            <p className="font-medium text-slate-800">{loan.memberName}</p>
                            <p className="text-xs text-slate-400">{loan.memberEmail}</p>
                          </div>
                        </td>
                        <td className="py-3 text-right text-slate-600">{formatCurrency(loan.amount)}</td>
                        <td className="py-3 text-right font-semibold text-slate-800">{formatCurrency(loan.remaining)}</td>
                        <td className="py-3 text-slate-600">{formatDate(loan.issueDate)}</td>
                        <td className="py-3 text-slate-600">{loan.dueDate ? formatDate(loan.dueDate) : '-'}</td>
                        <td className="py-3 text-center">{getStatusBadge(loan.status)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {totalPages > 1 && (
                <div className="mt-4 flex items-center justify-between">
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                    disabled={page === 1}
                  >
                    Previous
                  </Button>
                  <span className="text-sm text-slate-600">
                    Page {page} of {totalPages}
                  </span>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                    disabled={page === totalPages}
                  >
                    Next
                  </Button>
                </div>
              )}
            </>
          )}
        </CardBody>
      </Card>
    </div>
  )
}