// Generated by GitHub Copilot
import { useState, useMemo, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  FiUser,
  FiDollarSign,
  FiCreditCard,
  FiBookOpen,
  FiPhone,
  FiMail,
  FiCalendar,
  FiArrowLeft,
  FiEdit3,
  FiCheck,
  FiToggleLeft,
  FiToggleRight,
} from 'react-icons/fi'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Tabs from '../../components/ui/Tabs.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Button from '../../components/ui/Button.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import ContributionsTable from '../../components/tables/ContributionsTable.jsx'
import LoansTable from '../../components/tables/LoansTable.jsx'
import LoanSummaryCard from '../../components/cards/LoanSummaryCard.jsx'
import PaymentTimeline from '../../components/cards/PaymentTimeline.jsx'
import SettlementModal from '../../components/cards/SettlementModal.jsx'
import { useData } from '../../hooks/useData.js'
import { formatCurrency, formatDate, getInitials } from '../../utils/format.js'

const TABS = [
  { key: 'profile', label: 'Profile', icon: FiUser },
  { key: 'contributions', label: 'Contributions', icon: FiDollarSign },
  { key: 'loans', label: 'Loans', icon: FiCreditCard },
  { key: 'passbook', label: 'Loan Passbook', icon: FiBookOpen },
]

/** Member detail view with Profile / Contributions / Loans / Passbook tabs. */
export default function MemberDetails() {
  const { id } = useParams()
  const navigate = useNavigate()
  const {
    getMemberById,
    getContributionsByMember,
    getLoansByMember,
    updateMemberStatus,
    loans: contextLoans,
  } = useData()
  const [tab, setTab] = useState('profile')
  const [togglingStatus, setTogglingStatus] = useState(false)
  const [settleModalOpen, setSettleModalOpen] = useState(false)
  const [settled, setSettled] = useState(false)
  const [message, setMessage] = useState('')
  const [loansWithRepayments, setLoansWithRepayments] = useState([])

  const member = getMemberById(id)

  const memberId = member?._id || member?.id
  const contributions = member ? getContributionsByMember(id) : []
  const loans = member ? getLoansByMember(id) : []
  const activeLoan = loans.find((l) => l.status === 'active')
  const isActive = member?.status?.toLowerCase() === 'active'
  const isExited = member?.status?.toLowerCase() === 'exited'
  const isSettled = member?.status?.toLowerCase() === 'settled'

  // Fetch loans with repayments from API (only on mount/id change)
  useEffect(() => {
    let active = true
    const fetchLoansWithRepayments = async () => {
      try {
        // Import loanApi dynamically
        const { loanApi } = await import('../../api/loanApi.js')
        const data = await loanApi.list({ memberId: id, limit: 100 })
        if (active) {
          setLoansWithRepayments(data.loans || [])
        }
      } catch (err) {
        console.error('Failed to fetch loans with repayments:', err)
      }
    }

    if (id) {
      fetchLoansWithRepayments()
    }
    return () => { active = false }
  }, [id])

  // Use loans with repayments if available, otherwise fallback to context loans
  const displayLoans = loansWithRepayments.length > 0 ? loansWithRepayments : loans

  // Combine all repayments from all loans for the passbook view
  const allRepayments = useMemo(() => {
    const repayments = []
    displayLoans.forEach((loan) => {
      if (loan.repayments && loan.repayments.length > 0) {
        loan.repayments.forEach((repayment) => {
          repayments.push({
            ...repayment,
            loanId: loan.id,
            loanStatus: loan.status,
          })
        })
      }
    })
    // Sort by date descending
    return repayments.sort((a, b) => {
      const dateA = new Date(a.paymentDate || a.date || 0)
      const dateB = new Date(b.paymentDate || b.date || 0)
      return dateB - dateA
    })
  }, [displayLoans])

  // Calculate totals across all loans
  const totalBorrowed = displayLoans.reduce((sum, l) => sum + Number(l.amount || 0), 0)
  const totalRemaining = displayLoans.reduce((sum, l) => sum + Number(l.remaining || 0), 0)
  const totalRepaid = totalBorrowed - totalRemaining

  // Show not found message after all hooks are called
  if (!member) {
    return (
      <div>
        <Breadcrumb items={[{ label: 'Members', to: '/admin/members' }, { label: 'Not found' }]} />
        <EmptyState
          title="Member not found"
          description="This member may have been removed."
          action={
            <Button onClick={() => navigate('/admin/members')} icon={FiArrowLeft}>
              Back to Members
            </Button>
          }
        />
      </div>
    )
  }

  /** Toggle member status between Active and Inactive. */
  const handleToggleStatus = async () => {
    setTogglingStatus(true)
    try {
      await updateMemberStatus(memberId, isActive ? 'Inactive' : 'Active')
    } catch {
      // Error handled by DataContext
    } finally {
      setTogglingStatus(false)
    }
  }

  return (
    <div>
      <Breadcrumb
        items={[
          { label: 'Members', to: '/admin/members' },
          { label: member.name },
        ]}
      />

      {message && (
        <div className="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{message}</div>
      )}

      <PageHeader
        title="Member Details"
        action={
          <Button
            variant="secondary"
            icon={FiArrowLeft}
            onClick={() => navigate('/admin/members')}
          >
            Back
          </Button>
        }
      />

      {/* Identity header */}
      <Card className="mb-6">
        <CardBody className="flex flex-col items-start gap-4 sm:flex-row sm:items-center">
          <span
            className="flex h-16 w-16 items-center justify-center rounded-full text-xl font-semibold text-white"
            style={{ backgroundColor: member.avatarColor || '#3563ff' }}
          >
            {getInitials(member.name)}
          </span>
          <div className="flex-1">
            <div className="flex items-center gap-3">
              <h2 className="text-xl font-bold text-slate-800">{member.name}</h2>
              <Badge>
                {isSettled ? 'Settled' : isActive ? 'Active' : 'Inactive'}
              </Badge>
            </div>
            <p className="text-sm text-slate-400">Member ID · {memberId}</p>
          </div>
          <div className="grid grid-cols-2 gap-6 text-sm sm:grid-cols-3">
            <div>
              <p className="text-slate-400">Total Contribution</p>
              <p className="font-semibold text-slate-800">
                {formatCurrency(member.totalContribution || 0)}
              </p>
            </div>
            <div>
              <p className="text-slate-400">Active Loan</p>
              <p className="font-semibold text-slate-800">
                {formatCurrency(member.activeLoan || 0)}
              </p>
            </div>
          </div>
        </CardBody>
      </Card>

      <Tabs tabs={TABS} active={tab} onChange={setTab} />

      <div className="mt-5">
        {tab === 'profile' ? (
          <Card>
            <CardBody>
              <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <Detail icon={FiUser} label="Full Name" value={member.name} />
                <Detail icon={FiPhone} label="Mobile" value={member.mobile} />
                <Detail icon={FiMail} label="Email" value={member.email} />
                <Detail
                  icon={FiCalendar}
                  label="Joining Date"
                  value={formatDate(member.joiningDate)}
                />
              </dl>
            </CardBody>
          </Card>
        ) : null}

        {tab === 'contributions' ? (
          <Card>
            {contributions.length === 0 ? (
              <EmptyState title="No contributions yet" />
            ) : (
              <ContributionsTable contributions={contributions} />
            )}
          </Card>
        ) : null}

        {tab === 'loans' ? (
          <Card>
            {loans.length === 0 ? (
              <EmptyState
                icon={FiCreditCard}
                title="No loans"
                description="This member has not taken any loans."
              />
            ) : (
              <LoansTable loans={loans} showMember={false} />
            )}
          </Card>
        ) : null}

        {tab === 'passbook' ? (
          displayLoans.length > 0 ? (
            <div className="space-y-6">
              {/* Summary Cards */}
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                <Card>
                  <CardBody>
                    <p className="text-xs text-slate-500">Total Borrowed</p>
                    <p className="mt-1 text-lg font-semibold text-slate-800">{formatCurrency(totalBorrowed)}</p>
                  <p className="mt-1 text-xs text-slate-400">{displayLoans.length} loan(s)</p>
                  </CardBody>
                </Card>
                <Card>
                  <CardBody>
                    <p className="text-xs text-slate-500">Total Repaid</p>
                    <p className="mt-1 text-lg font-semibold text-green-600">{formatCurrency(totalRepaid)}</p>
                  </CardBody>
                </Card>
                <Card>
                  <CardBody>
                    <p className="text-xs text-slate-500">Remaining Balance</p>
                    <p className="mt-1 text-lg font-semibold text-amber-600">{formatCurrency(totalRemaining)}</p>
                  </CardBody>
                </Card>
              </div>

              {/* Payment History */}
              <Card>
                <CardBody>
                  <h3 className="mb-4 text-sm font-semibold text-slate-700">
                    Payment History ({allRepayments.length} payments)
                  </h3>
                  {allRepayments.length === 0 ? (
                    <p className="text-sm text-slate-500">No payments recorded yet</p>
                  ) : (
                    <div className="overflow-x-auto">
                      <table className="w-full text-sm">
                        <thead className="border-b border-slate-200 bg-slate-50">
                          <tr>
                            <th className="px-4 py-3 text-left font-semibold text-slate-700">Date</th>
                            <th className="px-4 py-3 text-right font-semibold text-slate-700">Amount</th>
                            <th className="px-4 py-3 text-left font-semibold text-slate-700">Loan</th>
                            <th className="px-4 py-3 text-center font-semibold text-slate-700">Status</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                          {allRepayments.map((repayment, index) => (
                            <tr key={index} className="hover:bg-slate-50">
                              <td className="px-4 py-3 font-medium text-slate-800">
                                {formatDate(repayment.paymentDate || repayment.date)}
                              </td>
                              <td className="px-4 py-3 text-right text-slate-600">{formatCurrency(repayment.amount)}</td>
                              <td className="px-4 py-3 text-slate-600">
                                #{repayment.loanId?.slice(-6)}
                              </td>
                              <td className="px-4 py-3 text-center">
                                <Badge variant={repayment.loanStatus === 'active' ? 'success' : 'slate'} size="sm">
                                  {repayment.loanStatus}
                                </Badge>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </CardBody>
              </Card>
            </div>
          ) : (
            <Card>
              <EmptyState
                icon={FiBookOpen}
                title="No loans"
                description="This member has not taken any loans yet."
              />
            </Card>
          )
        ) : null}
      </div>

      {/* Action buttons */}
      <Card className="mt-6">
        <CardBody>
          {isSettled ? (
            <div className="flex items-center gap-3 rounded-lg border border-green-200 bg-green-50 px-4 py-3">
              <FiCheck className="h-5 w-5 flex-shrink-0 text-green-600" />
              <p className="text-sm font-medium text-green-900">
                This member has been settled. No further actions are available.
              </p>
            </div>
          ) : (
            <>
              <h3 className="mb-3 text-sm font-semibold text-slate-700">Actions</h3>
              <div className="flex flex-wrap gap-3">
                <Button
                  size="sm"
                  icon={isActive ? FiToggleLeft : FiToggleRight}
                  onClick={handleToggleStatus}
                  disabled={togglingStatus}
                  variant={isActive ? 'danger' : 'secondary'}
                >
                  {togglingStatus
                    ? 'Updating...'
                    : isActive
                      ? 'Deactivate Member'
                      : 'Activate Member'}
                </Button>
                <Button
                  size="sm"
                  icon={FiEdit3}
                  variant="secondary"
                  onClick={() => navigate(`/admin/members/${memberId}/edit`)}
                >
                  Edit Member
                </Button>
                {!isExited && (
                  <Button
                    size="sm"
                    icon={FiDollarSign}
                    variant="danger"
                    onClick={() => setSettleModalOpen(true)}
                  >
                    Settle Member
                  </Button>
                )}
              </div>
            </>
          )}
        </CardBody>
      </Card>

      <SettlementModal
        member={{
          id: memberId,
          name: member.name,
          email: member.email,
          mobile: member.mobile,
        }}
        open={settleModalOpen}
        onClose={() => setSettleModalOpen(false)}
        onSettled={() => {
          setSettleModalOpen(false)
          setSettled(true)
          // Show success message, then reload to refresh data
          setMessage('Member settled successfully')
          setTimeout(() => {
            window.location.reload()
          }, 2000)
        }}
      />
    </div>
  )
}

/** Small labelled detail row with an icon. */
function Detail({ icon: Icon, label, value }) {
  return (
    <div className="flex items-start gap-3">
      <span className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-500">
        <Icon className="h-4 w-4" />
      </span>
      <div>
        <dt className="text-xs text-slate-400">{label}</dt>
        <dd className="text-sm font-medium text-slate-800">{value}</dd>
      </div>
    </div>
  )
}
