// Generated by GitHub Copilot
import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  FiUser,
  FiDollarSign,
  FiCreditCard,
  FiBookOpen,
  FiPhone,
  FiMail,
  FiCalendar,
  FiArrowLeft,
  FiEdit3,
  FiTrash2,
  FiToggleLeft,
  FiToggleRight,
} from 'react-icons/fi'
import Breadcrumb from '../../components/layout/Breadcrumb.jsx'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody } from '../../components/ui/Card.jsx'
import Tabs from '../../components/ui/Tabs.jsx'
import Badge from '../../components/ui/Badge.jsx'
import Button from '../../components/ui/Button.jsx'
import Modal from '../../components/ui/Modal.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import ContributionsTable from '../../components/tables/ContributionsTable.jsx'
import LoansTable from '../../components/tables/LoansTable.jsx'
import LoanSummaryCard from '../../components/cards/LoanSummaryCard.jsx'
import PaymentTimeline from '../../components/cards/PaymentTimeline.jsx'
import SettlementModal from '../../components/cards/SettlementModal.jsx'
import { useData } from '../../hooks/useData.js'
import { formatCurrency, formatDate, getInitials } from '../../utils/format.js'

const TABS = [
  { key: 'profile', label: 'Profile', icon: FiUser },
  { key: 'contributions', label: 'Contributions', icon: FiDollarSign },
  { key: 'loans', label: 'Loans', icon: FiCreditCard },
  { key: 'passbook', label: 'Loan Passbook', icon: FiBookOpen },
]

/** Member detail view with Profile / Contributions / Loans / Passbook tabs. */
export default function MemberDetails() {
  const { id } = useParams()
  const navigate = useNavigate()
  const {
    getMemberById,
    getContributionsByMember,
    getLoansByMember,
    updateMemberStatus,
    deleteMember,
  } = useData()
  const [tab, setTab] = useState('profile')
  const [deleteModalOpen, setDeleteModalOpen] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const [togglingStatus, setTogglingStatus] = useState(false)
  const [settleModalOpen, setSettleModalOpen] = useState(false)
  const [settled, setSettled] = useState(false)

  const member = getMemberById(id)

  if (!member) {
    return (
      <div>
        <Breadcrumb items={[{ label: 'Members', to: '/admin/members' }, { label: 'Not found' }]} />
        <EmptyState
          title="Member not found"
          description="This member may have been removed."
          action={
            <Button onClick={() => navigate('/admin/members')} icon={FiArrowLeft}>
              Back to Members
            </Button>
          }
        />
      </div>
    )
  }

  const memberId = member._id || member.id
  const contributions = getContributionsByMember(id)
  const loans = getLoansByMember(id)
  const activeLoan = loans.find((l) => l.status === 'active')
  const isActive = member.status === 'Active'
  const isExited = member.status === 'Exited'

  /** Toggle member status between Active and Inactive. */
  const handleToggleStatus = async () => {
    setTogglingStatus(true)
    try {
      await updateMemberStatus(memberId, isActive ? 'Inactive' : 'Active')
    } catch {
      // Error handled by DataContext
    } finally {
      setTogglingStatus(false)
    }
  }

  /** Soft-delete the member with confirmation. */
  const handleDelete = async () => {
    setDeleting(true)
    try {
      await deleteMember(memberId)
      navigate('/admin/members')
    } catch {
      setDeleting(false)
      setDeleteModalOpen(false)
    }
  }

  return (
    <div>
      <Breadcrumb
        items={[
          { label: 'Members', to: '/admin/members' },
          { label: member.name },
        ]}
      />

      <PageHeader
        title="Member Details"
        action={
          <Button
            variant="secondary"
            icon={FiArrowLeft}
            onClick={() => navigate('/admin/members')}
          >
            Back
          </Button>
        }
      />

      {/* Identity header */}
      <Card className="mb-6">
        <CardBody className="flex flex-col items-start gap-4 sm:flex-row sm:items-center">
          <span
            className="flex h-16 w-16 items-center justify-center rounded-full text-xl font-semibold text-white"
            style={{ backgroundColor: member.avatarColor || '#3563ff' }}
          >
            {getInitials(member.name)}
          </span>
          <div className="flex-1">
            <div className="flex items-center gap-3">
              <h2 className="text-xl font-bold text-slate-800">{member.name}</h2>
              <Badge>{isActive ? 'Active' : 'Inactive'}</Badge>
            </div>
            <p className="text-sm text-slate-400">Member ID · {memberId}</p>
          </div>
          <div className="grid grid-cols-2 gap-6 text-sm sm:grid-cols-3">
            <div>
              <p className="text-slate-400">Total Contribution</p>
              <p className="font-semibold text-slate-800">
                {formatCurrency(member.totalContribution || 0)}
              </p>
            </div>
            <div>
              <p className="text-slate-400">Active Loan</p>
              <p className="font-semibold text-slate-800">
                {formatCurrency(member.activeLoan || 0)}
              </p>
            </div>
          </div>
        </CardBody>
      </Card>

      <Tabs tabs={TABS} active={tab} onChange={setTab} />

      <div className="mt-5">
        {tab === 'profile' ? (
          <Card>
            <CardBody>
              <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <Detail icon={FiUser} label="Full Name" value={member.name} />
                <Detail icon={FiPhone} label="Mobile" value={member.mobile} />
                <Detail icon={FiMail} label="Email" value={member.email} />
                <Detail
                  icon={FiCalendar}
                  label="Joining Date"
                  value={formatDate(member.joiningDate)}
                />
              </dl>
            </CardBody>
          </Card>
        ) : null}

        {tab === 'contributions' ? (
          <Card>
            {contributions.length === 0 ? (
              <EmptyState title="No contributions yet" />
            ) : (
              <ContributionsTable contributions={contributions} />
            )}
          </Card>
        ) : null}

        {tab === 'loans' ? (
          <Card>
            {loans.length === 0 ? (
              <EmptyState
                icon={FiCreditCard}
                title="No loans"
                description="This member has not taken any loans."
              />
            ) : (
              <LoansTable loans={loans} showMember={false} />
            )}
          </Card>
        ) : null}

        {tab === 'passbook' ? (
          activeLoan ? (
            <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
              <LoanSummaryCard loan={activeLoan} />
              <Card>
                <CardBody>
                  <h3 className="mb-4 text-sm font-semibold text-slate-700">
                    Payment History
                  </h3>
                  <PaymentTimeline repayments={activeLoan.repayments} />
                </CardBody>
              </Card>
            </div>
          ) : (
            <Card>
              <EmptyState
                icon={FiBookOpen}
                title="No active loan"
                description="The passbook is available for members with an active loan."
              />
            </Card>
          )
        ) : null}
      </div>

      {/* Action buttons */}
      <Card className="mt-6">
        <CardBody>
          <h3 className="mb-3 text-sm font-semibold text-slate-700">Actions</h3>
          <div className="flex flex-wrap gap-3">
            <Button
              size="sm"
              icon={isActive ? FiToggleLeft : FiToggleRight}
              onClick={handleToggleStatus}
              disabled={togglingStatus}
              variant={isActive ? 'danger' : 'secondary'}
            >
              {togglingStatus
                ? 'Updating...'
                : isActive
                  ? 'Deactivate Member'
                  : 'Activate Member'}
            </Button>
            <Button
              size="sm"
              icon={FiEdit3}
              variant="secondary"
              onClick={() => navigate(`/admin/members/${memberId}/edit`)}
            >
              Edit Member
            </Button>
            {!isExited && (
              <Button
                size="sm"
                icon={FiDollarSign}
                variant="danger"
                onClick={() => setSettleModalOpen(true)}
              >
                Settle Member
              </Button>
            )}
            <Button
              size="sm"
              icon={FiTrash2}
              variant="danger"
              onClick={() => setDeleteModalOpen(true)}
            >
              Delete Member
            </Button>
          </div>
        </CardBody>
      </Card>

      <SettlementModal
        memberId={memberId}
        memberName={member.name}
        open={settleModalOpen}
        onClose={() => setSettleModalOpen(false)}
        onSettled={() => setSettled(true)}
      />

      {/* Delete confirmation modal */}
      <Modal
        open={deleteModalOpen}
        onClose={() => !deleting && setDeleteModalOpen(false)}
        title="Delete Member"
        size="sm"
        footer={
          <>
            <Button
              variant="secondary"
              onClick={() => setDeleteModalOpen(false)}
              disabled={deleting}
            >
              Cancel
            </Button>
            <Button variant="danger" onClick={handleDelete} disabled={deleting}>
              {deleting ? 'Deleting...' : 'Yes, Delete'}
            </Button>
          </>
        }
      >
        <div className="py-2 text-center">
          <span className="flex h-14 w-14 items-center justify-center rounded-full bg-red-100 text-red-600 mx-auto">
            <FiTrash2 className="h-7 w-7" />
          </span>
          <p className="mt-4 text-base font-semibold text-slate-800">
            Delete {member?.name}?
          </p>
          <p className="mt-2 text-sm text-slate-500">
            This action will mark the member as deleted. Their data will be
            preserved but hidden from active lists. You can restore them later
            if needed.
          </p>
        </div>
      </Modal>
    </div>
  )
}

/** Small labelled detail row with an icon. */
function Detail({ icon: Icon, label, value }) {
  return (
    <div className="flex items-start gap-3">
      <span className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-500">
        <Icon className="h-4 w-4" />
      </span>
      <div>
        <dt className="text-xs text-slate-400">{label}</dt>
        <dd className="text-sm font-medium text-slate-800">{value}</dd>
      </div>
    </div>
  )
}
