// Generated by GitHub Copilot
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiDollarSign, FiCheckCircle, FiArrowLeft } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Input from '../../components/ui/Input.jsx'
import Button from '../../components/ui/Button.jsx'
import { useSettings } from '../../hooks/useSettings.js'
import { formatCurrency } from '../../utils/format.js'

/** Settings page for the universal monthly contribution amount. */
export default function Settings() {
  const navigate = useNavigate()
  const { monthlyAmount, setMonthlyAmount, loading } = useSettings()
  const [value, setValue] = useState(String(monthlyAmount))
  const [error, setError] = useState('')
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)

  const handleSave = async (e) => {
    e.preventDefault()
    const amount = Number(value)
    if (!amount || amount <= 0) {
      setError('Enter a valid amount greater than zero.')
      return
    }
    setSaving(true)
    setError('')
    try {
      await setMonthlyAmount(amount)
      setSaved(true)
      setTimeout(() => setSaved(false), 2500)
    } catch {
      setError('Failed to save. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <PageHeader
        title="Settings"
        description="Configure fund-wide preferences."
        action={
          <Button variant="secondary" icon={FiArrowLeft} onClick={() => navigate('/admin/dashboard')}>
            Back
          </Button>
        }
      />

      <Card className="max-w-xl">
        <CardHeader
          title="Monthly Contribution"
          subtitle="Applied universally to all members."
        />
        <CardBody>
          <div className="mb-5 rounded-lg bg-brand-50 px-4 py-3">
            <p className="text-sm text-brand-700">
              Current amount:{' '}
              <span className="font-semibold">
                {formatCurrency(monthlyAmount)}
              </span>{' '}
              per member / month
            </p>
          </div>

          <form onSubmit={handleSave} className="space-y-4">
            <Input
              label="Universal Monthly Contribution Amount (₹)"
              name="monthlyAmount"
              type="number"
              min="0"
              icon={FiDollarSign}
              value={value}
              onChange={(e) => {
                setValue(e.target.value)
                setError('')
              }}
              error={error}
            />

            <div className="flex items-center gap-3">
              <Button type="submit" disabled={saving || loading}>
                {saving ? 'Saving...' : 'Save Changes'}
              </Button>
              {saved ? (
                <span className="inline-flex items-center gap-1.5 text-sm font-medium text-green-600">
                  <FiCheckCircle className="h-4 w-4" />
                  Saved
                </span>
              ) : null}
            </div>
          </form>
        </CardBody>
      </Card>
    </div>
  )
}
