// Generated by GitHub Copilot
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FiDollarSign, FiCheckCircle, FiArrowLeft, FiAlertTriangle } from 'react-icons/fi'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx'
import Input from '../../components/ui/Input.jsx'
import Button from '../../components/ui/Button.jsx'
import Modal from '../../components/ui/Modal.jsx'
import { useSettings } from '../../hooks/useSettings.js'
import { settingsApi } from '../../api/settingsApi.js'
import { formatCurrency } from '../../utils/format.js'

/** Settings page for the universal monthly contribution amount. */
export default function Settings() {
  const navigate = useNavigate()
  const { monthlyAmount, setMonthlyAmount, loading } = useSettings()
  const [value, setValue] = useState(String(monthlyAmount))
  const [error, setError] = useState('')
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)
  const [cleanupModalOpen, setCleanupModalOpen] = useState(false)
  const [cleaningUp, setCleaningUp] = useState(false)
  const [cleanupMessage, setCleanupMessage] = useState('')

  const handleSave = async (e) => {
    e.preventDefault()
    const amount = Number(value)
    if (!amount || amount <= 0) {
      setError('Enter a valid amount greater than zero.')
      return
    }
    setSaving(true)
    setError('')
    try {
      await setMonthlyAmount(amount)
      setSaved(true)
      setTimeout(() => setSaved(false), 2500)
    } catch {
      setError('Failed to save. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  const handleCleanup = async () => {
    setCleaningUp(true)
    setCleanupMessage('')
    try {
      const result = await settingsApi.cleanup()
      setCleanupMessage(result.message || 'Database cleaned successfully!')
      setTimeout(() => {
        setCleanupModalOpen(false)
        // Refresh the page to clear all cached data
        window.location.reload()
      }, 2000)
    } catch (err) {
      setCleanupMessage(err.message || 'Failed to cleanup database')
    } finally {
      setCleaningUp(false)
    }
  }

  return (
    <div>
      <PageHeader
        title="Settings"
        description="Configure fund-wide preferences."
        action={
          <Button variant="secondary" icon={FiArrowLeft} onClick={() => navigate('/admin/dashboard')}>
            Back
          </Button>
        }
      />

      <Card className="max-w-xl">
        <CardHeader
          title="Monthly Contribution"
          subtitle="Applied universally to all members."
        />
        <CardBody>
          <div className="mb-5 rounded-lg bg-brand-50 px-4 py-3">
            <p className="text-sm text-brand-700">
              Current amount:{' '}
              <span className="font-semibold">
                {formatCurrency(monthlyAmount)}
              </span>{' '}
              per member / month
            </p>
          </div>

          <form onSubmit={handleSave} className="space-y-4">
            <Input
              label="Universal Monthly Contribution Amount (₹)"
              name="monthlyAmount"
              type="number"
              min="0"
              icon={FiDollarSign}
              value={value}
              onChange={(e) => {
                setValue(e.target.value)
                setError('')
              }}
              error={error}
            />

            <div className="flex items-center gap-3">
              <Button type="submit" disabled={saving || loading}>
                {saving ? 'Saving...' : 'Save Changes'}
              </Button>
              {saved ? (
                <span className="inline-flex items-center gap-1.5 text-sm font-medium text-green-600">
                  <FiCheckCircle className="h-4 w-4" />
                  Saved
                </span>
              ) : null}
            </div>
          </form>
        </CardBody>
      </Card>

      {/* Danger Zone */}
      <Card className="mt-6 max-w-xl">
        <CardHeader
          title="Danger Zone"
          subtitle="Irreversible actions that affect the entire database."
        />
        <CardBody>
          <div className="rounded-lg border border-red-200 bg-red-50 p-4">
            <h3 className="text-sm font-semibold text-red-900">Reset Database</h3>
            <p className="mt-1 text-sm text-red-700">
              This will delete all members, contributions, loans, repayments, notifications, and settlements.
              Admin accounts will be preserved.
            </p>
            <Button
              variant="danger"
              size="sm"
              icon={FiAlertTriangle}
              onClick={() => setCleanupModalOpen(true)}
              className="mt-3"
            >
              Reset Database
            </Button>
          </div>
        </CardBody>
      </Card>

      {/* Cleanup Confirmation Modal */}
      <Modal
        open={cleanupModalOpen}
        onClose={() => !cleaningUp && setCleanupModalOpen(false)}
        title="Reset Database"
        size="sm"
        footer={
          <>
            <Button
              variant="secondary"
              onClick={() => setCleanupModalOpen(false)}
              disabled={cleaningUp}
            >
              Cancel
            </Button>
            <Button variant="danger" onClick={handleCleanup} disabled={cleaningUp}>
              {cleaningUp ? 'Resetting...' : 'Yes, Reset Database'}
            </Button>
          </>
        }
      >
        <div className="py-2 text-center">
          <span className="flex h-14 w-14 items-center justify-center rounded-full bg-red-100 text-red-600 mx-auto">
            <FiAlertTriangle className="h-7 w-7" />
          </span>
          <p className="mt-4 text-base font-semibold text-slate-800">
            Are you sure you want to reset the database?
          </p>
          <p className="mt-2 text-sm text-slate-500">
            This will permanently delete all members, contributions, loans, repayments, notifications, and settlements.
            Admin accounts will be preserved. This action cannot be undone.
          </p>
          {cleanupMessage && (
            <div className={`mt-4 rounded-lg px-4 py-3 text-sm ${cleanupMessage.includes('Failed') ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'}`}>
              {cleanupMessage}
            </div>
          )}
        </div>
      </Modal>
    </div>
  )
}
