// Generated by GitHub Copilot

const TONES = {
  green: 'bg-green-100 text-green-700',
  red: 'bg-red-100 text-red-700',
  amber: 'bg-amber-100 text-amber-700',
  blue: 'bg-blue-100 text-blue-700',
  slate: 'bg-slate-100 text-slate-600',
  brand: 'bg-brand-100 text-brand-700',
}

/** Small status pill. Pass a tone or let it map common status strings. */
export default function Badge({ children, tone, className = '' }) {
  const resolved = tone ?? mapStatus(String(children).toLowerCase())
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ${TONES[resolved] ?? TONES.slate} ${className}`}
    >
      {children}
    </span>
  )
}

function mapStatus(status) {
  if (['paid', 'active', 'closed'].includes(status)) {
    return status === 'closed' ? 'slate' : status === 'active' ? 'blue' : 'green'
  }
  if (['unpaid', 'inactive', 'overdue'].includes(status)) return 'red'
  if (['pending', 'due'].includes(status)) return 'amber'
  return 'slate'
}
