// Generated by GitHub Copilot

/** Simple surface container with consistent padding, radius and border. */
export default function Card({ children, className = '', ...props }) {
  return (
    <div
      className={`rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}
      {...props}
    >
      {children}
    </div>
  )
}

/** Optional header row for a Card. */
export function CardHeader({ title, subtitle, action, className = '' }) {
  return (
    <div
      className={`flex items-start justify-between gap-4 border-b border-slate-100 px-5 py-4 ${className}`}
    >
      <div>
        <h3 className="text-base font-semibold text-slate-800">{title}</h3>
        {subtitle ? (
          <p className="mt-0.5 text-sm text-slate-500">{subtitle}</p>
        ) : null}
      </div>
      {action}
    </div>
  )
}

/** Padded body region for a Card. */
export function CardBody({ children, className = '' }) {
  return <div className={`px-5 py-4 ${className}`}>{children}</div>
}
