// Generated by GitHub Copilot

/**
 * Labelled text input. Associates the label with the control for screen
 * readers and shows an optional validation error message.
 */
export default function Input({
  label,
  id,
  error,
  icon: Icon,
  className = '',
  ...props
}) {
  const inputId = id || props.name
  return (
    <div className={className}>
      {label ? (
        <label
          htmlFor={inputId}
          className="mb-1.5 block text-sm font-medium text-slate-700"
        >
          {label}
        </label>
      ) : null}
      <div className="relative">
        {Icon ? (
          <Icon
            className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"
            aria-hidden="true"
          />
        ) : null}
        <input
          id={inputId}
          className={`w-full rounded-lg border bg-white px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
            Icon ? 'pl-9' : ''
          } ${error ? 'border-red-400' : 'border-slate-300'}`}
          aria-invalid={!!error}
          {...props}
        />
      </div>
      {error ? <p className="mt-1 text-xs text-red-600">{error}</p> : null}
    </div>
  )
}
