// Generated by GitHub Copilot
import { FiChevronLeft, FiChevronRight } from 'react-icons/fi'

/** Compact pagination control driven by the usePagination hook. */
export default function Pagination({ page, totalPages, onPrev, onNext, onGoTo }) {
  if (totalPages <= 1) return null

  const pages = Array.from({ length: totalPages }, (_, i) => i + 1)

  return (
    <nav
      className="flex items-center justify-between gap-2 px-1 pt-3"
      aria-label="Pagination"
    >
      <p className="text-sm text-slate-500">
        Page <span className="font-medium text-slate-700">{page}</span> of{' '}
        {totalPages}
      </p>
      <div className="flex items-center gap-1">
        <button
          type="button"
          onClick={onPrev}
          disabled={page === 1}
          aria-label="Previous page"
          className="rounded-lg border border-slate-300 p-1.5 text-slate-600 transition-colors hover:bg-slate-50 disabled:opacity-40 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
        >
          <FiChevronLeft className="h-4 w-4" />
        </button>
        {pages.map((p) => (
          <button
            key={p}
            type="button"
            onClick={() => onGoTo(p)}
            aria-current={p === page ? 'page' : undefined}
            className={`min-w-[2rem] rounded-lg px-2.5 py-1.5 text-sm font-medium transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
              p === page
                ? 'bg-brand-600 text-white'
                : 'text-slate-600 hover:bg-slate-100'
            }`}
          >
            {p}
          </button>
        ))}
        <button
          type="button"
          onClick={onNext}
          disabled={page === totalPages}
          aria-label="Next page"
          className="rounded-lg border border-slate-300 p-1.5 text-slate-600 transition-colors hover:bg-slate-50 disabled:opacity-40 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
        >
          <FiChevronRight className="h-4 w-4" />
        </button>
      </div>
    </nav>
  )
}
