// Generated by GitHub Copilot

/** Labelled select control with the same styling language as Input. */
export default function Select({
  label,
  id,
  error,
  options = [],
  placeholder,
  className = '',
  children,
  ...props
}) {
  const selectId = id || props.name
  return (
    <div className={className}>
      {label ? (
        <label
          htmlFor={selectId}
          className="mb-1.5 block text-sm font-medium text-slate-700"
        >
          {label}
        </label>
      ) : null}
      <select
        id={selectId}
        className={`w-full rounded-lg border bg-white px-3 py-2 text-sm text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
          error ? 'border-red-400' : 'border-slate-300'
        }`}
        aria-invalid={!!error}
        {...props}
      >
        {placeholder ? (
          <option value="" disabled>
            {placeholder}
          </option>
        ) : null}
        {children ??
          options.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
      </select>
      {error ? <p className="mt-1 text-xs text-red-600">{error}</p> : null}
    </div>
  )
}
