// Generated by GitHub Copilot

/**
 * Thin table primitives that provide consistent styling. Compose them as:
 * <Table><THead>...</THead><TBody>...</TBody></Table>
 */
export default function Table({ children, className = '' }) {
  return (
    <div className="w-full overflow-x-auto">
      <table className={`w-full border-collapse text-sm ${className}`}>
        {children}
      </table>
    </div>
  )
}

export function THead({ children }) {
  return (
    <thead className="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
      {children}
    </thead>
  )
}

export function TBody({ children }) {
  return <tbody className="divide-y divide-slate-100">{children}</tbody>
}

export function TR({ children, className = '', ...props }) {
  return (
    <tr className={`transition-colors hover:bg-slate-50/70 ${className}`} {...props}>
      {children}
    </tr>
  )
}

export function TH({ children, className = '' }) {
  return <th className={`whitespace-nowrap px-4 py-3 ${className}`}>{children}</th>
}

export function TD({ children, className = '' }) {
  return (
    <td className={`whitespace-nowrap px-4 py-3 text-slate-700 ${className}`}>
      {children}
    </td>
  )
}
