// Generated by GitHub Copilot
import { useState } from 'react'
import { FiUser, FiPhone, FiMail, FiCalendar, FiLock } from 'react-icons/fi'
import Input from '../ui/Input.jsx'
import Button from '../ui/Button.jsx'

/**
 * Controlled form for creating a member. Performs light client-side validation
 * (required fields, basic mobile/email shape) before calling onSubmit.
 */
export default function AddMemberForm({ onSubmit, onCancel }) {
  const [values, setValues] = useState({
    name: '',
    mobile: '',
    email: '',
    password: '',
    joiningDate: new Date().toISOString().slice(0, 10),
  })
  const [errors, setErrors] = useState({})

  const setField = (name, value) => {
    setValues((prev) => ({ ...prev, [name]: value }))
    setErrors((prev) => ({ ...prev, [name]: undefined }))
  }

  const validate = () => {
    const next = {}
    if (!values.name.trim()) next.name = 'Name is required.'
    if (!/^\d{10}$/.test(values.mobile.trim()))
      next.mobile = 'Enter a valid 10-digit mobile number.'
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim()))
      next.email = 'Enter a valid email address.'
    if (!values.password || values.password.length < 6)
      next.password = 'Password must be at least 6 characters.'
    if (!values.joiningDate) next.joiningDate = 'Joining date is required.'
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (validate()) onSubmit(values)
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <Input
        label="Full Name"
        name="name"
        icon={FiUser}
        placeholder="e.g. Rahul Sharma"
        value={values.name}
        onChange={(e) => setField('name', e.target.value)}
        error={errors.name}
      />
      <Input
        label="Mobile Number"
        name="mobile"
        icon={FiPhone}
        placeholder="10-digit number"
        inputMode="numeric"
        maxLength={10}
        value={values.mobile}
        onChange={(e) => setField('mobile', e.target.value.replace(/\D/g, ''))}
        error={errors.mobile}
      />
      <Input
        label="Email Address"
        name="email"
        type="email"
        icon={FiMail}
        placeholder="you@example.com"
        value={values.email}
        onChange={(e) => setField('email', e.target.value)}
        error={errors.email}
      />
      <Input
        label="Password"
        name="password"
        type="password"
        icon={FiLock}
        placeholder="Minimum 6 characters"
        value={values.password}
        onChange={(e) => setField('password', e.target.value)}
        error={errors.password}
      />
      <Input
        label="Joining Date"
        name="joiningDate"
        type="date"
        icon={FiCalendar}
        value={values.joiningDate}
        onChange={(e) => setField('joiningDate', e.target.value)}
        error={errors.joiningDate}
      />

      <div className="flex justify-end gap-3 pt-2">
        {onCancel ? (
          <Button type="button" variant="secondary" onClick={onCancel}>
            Cancel
          </Button>
        ) : null}
        <Button type="submit">Add Member</Button>
      </div>
    </form>
  )
}
