// Generated by GitHub Copilot
import { useState } from 'react'
import { FiDollarSign, FiCalendar } from 'react-icons/fi'
import Select from '../ui/Select.jsx'
import Input from '../ui/Input.jsx'
import Button from '../ui/Button.jsx'

/**
 * Assign-loan form. Validates the selected member, a positive amount and an
 * issue date before invoking onSubmit with the loan payload.
 */
export default function AssignLoanForm({ members, onSubmit, onCancel }) {
  const [values, setValues] = useState({
    memberId: '',
    amount: '',
    issueDate: new Date().toISOString().slice(0, 10),
    notes: '',
  })
  const [errors, setErrors] = useState({})

  const setField = (name, value) => {
    setValues((prev) => ({ ...prev, [name]: value }))
    setErrors((prev) => ({ ...prev, [name]: undefined }))
  }

  const validate = () => {
    const next = {}
    if (!values.memberId) next.memberId = 'Select a member.'
    if (!values.amount || Number(values.amount) <= 0)
      next.amount = 'Enter a valid loan amount.'
    if (!values.issueDate) next.issueDate = 'Issue date is required.'
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (validate()) onSubmit(values)
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <Select
        label="Select Member"
        name="memberId"
        placeholder="Choose a member"
        value={values.memberId}
        onChange={(e) => setField('memberId', e.target.value)}
        error={errors.memberId}
        options={members.map((m) => ({ value: m.id, label: m.name }))}
      />
      <Input
        label="Loan Amount"
        name="amount"
        type="number"
        min="0"
        icon={FiDollarSign}
        placeholder="e.g. 50000"
        value={values.amount}
        onChange={(e) => setField('amount', e.target.value)}
        error={errors.amount}
      />
      <Input
        label="Issue Date"
        name="issueDate"
        type="date"
        icon={FiCalendar}
        value={values.issueDate}
        onChange={(e) => setField('issueDate', e.target.value)}
        error={errors.issueDate}
      />
      <div>
        <label
          htmlFor="notes"
          className="mb-1.5 block text-sm font-medium text-slate-700"
        >
          Notes
        </label>
        <textarea
          id="notes"
          name="notes"
          rows={3}
          placeholder="Optional notes about this loan"
          value={values.notes}
          onChange={(e) => setField('notes', e.target.value)}
          className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
        />
      </div>

      <div className="flex justify-end gap-3 pt-1">
        <Button type="button" variant="secondary" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit">Assign Loan</Button>
      </div>
    </form>
  )
}
